name = "ranking-municipios-esp"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "./dist/client/_worker.js"

[[d1_databases]]
binding = "DB"
database_name = "ranking-municipios"
database_id = "d664746a-8439-488d-a42c-73aaf17b2140"

routes = [
  { pattern = "rankingspain.com/*", zone_name = "rankingspain.com" },
  { pattern = "www.rankingspain.com/*", zone_name = "rankingspain.com" }
]

[site]
bucket = "./dist/client"
