UPDATE municipios SET nombre_search='a coruna' WHERE codigo_ine='01001';
UPDATE municipios SET nombre_search='a pobra do caraminal' WHERE codigo_ine='01002';
UPDATE municipios SET nombre_search='betanzos' WHERE codigo_ine='01003';
UPDATE municipios SET nombre_search='boiro' WHERE codigo_ine='01004';
UPDATE municipios SET nombre_search='camarinas' WHERE codigo_ine='01005';
UPDATE municipios SET nombre_search='carballo' WHERE codigo_ine='01006';
UPDATE municipios SET nombre_search='carnota' WHERE codigo_ine='01007';
UPDATE municipios SET nombre_search='cedeira' WHERE codigo_ine='01008';
UPDATE municipios SET nombre_search='corcubion' WHERE codigo_ine='01009';
UPDATE municipios SET nombre_search='ferrol' WHERE codigo_ine='01010';
UPDATE municipios SET nombre_search='fisterra' WHERE codigo_ine='01011';
UPDATE municipios SET nombre_search='muros' WHERE codigo_ine='01012';
UPDATE municipios SET nombre_search='muxia' WHERE codigo_ine='01013';
UPDATE municipios SET nombre_search='noia' WHERE codigo_ine='01014';
UPDATE municipios SET nombre_search='ortigueira' WHERE codigo_ine='01015';
UPDATE municipios SET nombre_search='padron' WHERE codigo_ine='01016';
UPDATE municipios SET nombre_search='pontedeume' WHERE codigo_ine='01017';
UPDATE municipios SET nombre_search='rianxo' WHERE codigo_ine='01018';
UPDATE municipios SET nombre_search='ribeira' WHERE codigo_ine='01019';
UPDATE municipios SET nombre_search='santiago de compostela' WHERE codigo_ine='01020';
UPDATE municipios SET nombre_search='albacete' WHERE codigo_ine='02001';
UPDATE municipios SET nombre_search='alcadozo' WHERE codigo_ine='02002';
UPDATE municipios SET nombre_search='alcala del jucar' WHERE codigo_ine='02003';
UPDATE municipios SET nombre_search='alcaraz' WHERE codigo_ine='02004';
UPDATE municipios SET nombre_search='almansa' WHERE codigo_ine='02005';
UPDATE municipios SET nombre_search='ayna' WHERE codigo_ine='02006';
UPDATE municipios SET nombre_search='balazote' WHERE codigo_ine='02007';
UPDATE municipios SET nombre_search='casas ibanez' WHERE codigo_ine='02008';
UPDATE municipios SET nombre_search='caudete' WHERE codigo_ine='02009';
UPDATE municipios SET nombre_search='chinchilla de montearagon' WHERE codigo_ine='02010';
UPDATE municipios SET nombre_search='elche de la sierra' WHERE codigo_ine='02011';
UPDATE municipios SET nombre_search='fuentealamo' WHERE codigo_ine='02012';
UPDATE municipios SET nombre_search='ferez' WHERE codigo_ine='02013';
UPDATE municipios SET nombre_search='hellin' WHERE codigo_ine='02014';
UPDATE municipios SET nombre_search='la roda' WHERE codigo_ine='02015';
UPDATE municipios SET nombre_search='letur' WHERE codigo_ine='02016';
UPDATE municipios SET nombre_search='montealegre del castillo' WHERE codigo_ine='02017';
UPDATE municipios SET nombre_search='nerpio' WHERE codigo_ine='02018';
UPDATE municipios SET nombre_search='ossa de montiel' WHERE codigo_ine='02019';
UPDATE municipios SET nombre_search='paterna del madera' WHERE codigo_ine='02020';
UPDATE municipios SET nombre_search='penascosa' WHERE codigo_ine='02021';
UPDATE municipios SET nombre_search='pozohondo' WHERE codigo_ine='02022';
UPDATE municipios SET nombre_search='riopar' WHERE codigo_ine='02023';
UPDATE municipios SET nombre_search='socovos' WHERE codigo_ine='02024';
UPDATE municipios SET nombre_search='tobarra' WHERE codigo_ine='02025';
UPDATE municipios SET nombre_search='villamalea' WHERE codigo_ine='02026';
UPDATE municipios SET nombre_search='villarrobledo' WHERE codigo_ine='02027';
UPDATE municipios SET nombre_search='villavaliente' WHERE codigo_ine='02028';
UPDATE municipios SET nombre_search='viveros' WHERE codigo_ine='02029';
UPDATE municipios SET nombre_search='yeste' WHERE codigo_ine='02030';
UPDATE municipios SET nombre_search='agost' WHERE codigo_ine='03001';
UPDATE municipios SET nombre_search='alcoy/alcoi' WHERE codigo_ine='03002';
UPDATE municipios SET nombre_search='alicante/alacant' WHERE codigo_ine='03003';
UPDATE municipios SET nombre_search='altea' WHERE codigo_ine='03004';
UPDATE municipios SET nombre_search='aspe' WHERE codigo_ine='03005';
UPDATE municipios SET nombre_search='banyeres de mariola' WHERE codigo_ine='03006';
UPDATE municipios SET nombre_search='benidorm' WHERE codigo_ine='03007';
UPDATE municipios SET nombre_search='benimassot' WHERE codigo_ine='03008';
UPDATE municipios SET nombre_search='benissa' WHERE codigo_ine='03009';
UPDATE municipios SET nombre_search='calpe' WHERE codigo_ine='03010';
UPDATE municipios SET nombre_search='castalla' WHERE codigo_ine='03011';
UPDATE municipios SET nombre_search='cocentaina' WHERE codigo_ine='03012';
UPDATE municipios SET nombre_search='crevillent' WHERE codigo_ine='03013';
UPDATE municipios SET nombre_search='denia' WHERE codigo_ine='03014';
UPDATE municipios SET nombre_search='el campello' WHERE codigo_ine='03015';
UPDATE municipios SET nombre_search='elche/elx' WHERE codigo_ine='03016';
UPDATE municipios SET nombre_search='elda' WHERE codigo_ine='03017';
UPDATE municipios SET nombre_search='finestrat' WHERE codigo_ine='03018';
UPDATE municipios SET nombre_search='guadalest' WHERE codigo_ine='03019';
UPDATE municipios SET nombre_search='guardamar del segura' WHERE codigo_ine='03020';
UPDATE municipios SET nombre_search='ibi' WHERE codigo_ine='03021';
UPDATE municipios SET nombre_search='javea/xabia' WHERE codigo_ine='03022';
UPDATE municipios SET nombre_search='moraira' WHERE codigo_ine='03023';
UPDATE municipios SET nombre_search='muro de alcoy' WHERE codigo_ine='03024';
UPDATE municipios SET nombre_search='mutxamel' WHERE codigo_ine='03025';
UPDATE municipios SET nombre_search='novelda' WHERE codigo_ine='03026';
UPDATE municipios SET nombre_search='orihuela' WHERE codigo_ine='03027';
UPDATE municipios SET nombre_search='pego' WHERE codigo_ine='03028';
UPDATE municipios SET nombre_search='petrer' WHERE codigo_ine='03029';
UPDATE municipios SET nombre_search='planes' WHERE codigo_ine='03030';
UPDATE municipios SET nombre_search='polop' WHERE codigo_ine='03031';
UPDATE municipios SET nombre_search='relleu' WHERE codigo_ine='03032';
UPDATE municipios SET nombre_search='rojales' WHERE codigo_ine='03033';
UPDATE municipios SET nombre_search='san vicente del raspeig' WHERE codigo_ine='03034';
UPDATE municipios SET nombre_search='santa pola' WHERE codigo_ine='03035';
UPDATE municipios SET nombre_search='sella' WHERE codigo_ine='03036';
UPDATE municipios SET nombre_search='teulada' WHERE codigo_ine='03037';
UPDATE municipios SET nombre_search='torrevieja' WHERE codigo_ine='03038';
UPDATE municipios SET nombre_search='villajoyosa/la vila joiosa' WHERE codigo_ine='03039';
UPDATE municipios SET nombre_search='villena' WHERE codigo_ine='03040';
UPDATE municipios SET nombre_search='abla' WHERE codigo_ine='04001';
UPDATE municipios SET nombre_search='adra' WHERE codigo_ine='04002';
UPDATE municipios SET nombre_search='albox' WHERE codigo_ine='04003';
UPDATE municipios SET nombre_search='almeria' WHERE codigo_ine='04004';
UPDATE municipios SET nombre_search='bedar' WHERE codigo_ine='04005';
UPDATE municipios SET nombre_search='carboneras' WHERE codigo_ine='04006';
UPDATE municipios SET nombre_search='cuevas de vera' WHERE codigo_ine='04007';
UPDATE municipios SET nombre_search='el ejido' WHERE codigo_ine='04008';
UPDATE municipios SET nombre_search='finana' WHERE codigo_ine='04009';
UPDATE municipios SET nombre_search='fondon' WHERE codigo_ine='04010';
UPDATE municipios SET nombre_search='garrucha' WHERE codigo_ine='04011';
UPDATE municipios SET nombre_search='gergal' WHERE codigo_ine='04012';
UPDATE municipios SET nombre_search='huercal-overa' WHERE codigo_ine='04013';
UPDATE municipios SET nombre_search='laujar de andarax' WHERE codigo_ine='04014';
UPDATE municipios SET nombre_search='macael' WHERE codigo_ine='04015';
UPDATE municipios SET nombre_search='mojacar' WHERE codigo_ine='04016';
UPDATE municipios SET nombre_search='nijar' WHERE codigo_ine='04017';
UPDATE municipios SET nombre_search='ohanes' WHERE codigo_ine='04018';
UPDATE municipios SET nombre_search='olula del rio' WHERE codigo_ine='04019';
UPDATE municipios SET nombre_search='paterna del rio' WHERE codigo_ine='04020';
UPDATE municipios SET nombre_search='pulpi' WHERE codigo_ine='04021';
UPDATE municipios SET nombre_search='purchena' WHERE codigo_ine='04022';
UPDATE municipios SET nombre_search='roquetas de mar' WHERE codigo_ine='04023';
UPDATE municipios SET nombre_search='san jose (nijar)' WHERE codigo_ine='04024';
UPDATE municipios SET nombre_search='seron' WHERE codigo_ine='04025';
UPDATE municipios SET nombre_search='sorbas' WHERE codigo_ine='04026';
UPDATE municipios SET nombre_search='tahal' WHERE codigo_ine='04027';
UPDATE municipios SET nombre_search='turre' WHERE codigo_ine='04028';
UPDATE municipios SET nombre_search='vera' WHERE codigo_ine='04029';
UPDATE municipios SET nombre_search='vicar' WHERE codigo_ine='04030';
UPDATE municipios SET nombre_search='amieva' WHERE codigo_ine='05001';
UPDATE municipios SET nombre_search='aviles' WHERE codigo_ine='05002';
UPDATE municipios SET nombre_search='belmonte de miranda' WHERE codigo_ine='05003';
UPDATE municipios SET nombre_search='cabrales' WHERE codigo_ine='05004';
UPDATE municipios SET nombre_search='cangas de onis' WHERE codigo_ine='05005';
UPDATE municipios SET nombre_search='cangas del narcea' WHERE codigo_ine='05006';
UPDATE municipios SET nombre_search='covadonga' WHERE codigo_ine='05007';
UPDATE municipios SET nombre_search='cudillero' WHERE codigo_ine='05008';
UPDATE municipios SET nombre_search='gijon' WHERE codigo_ine='05009';
UPDATE municipios SET nombre_search='llanes' WHERE codigo_ine='05010';
UPDATE municipios SET nombre_search='luarca (valdes)' WHERE codigo_ine='05011';
UPDATE municipios SET nombre_search='onis' WHERE codigo_ine='05012';
UPDATE municipios SET nombre_search='oviedo' WHERE codigo_ine='05013';
UPDATE municipios SET nombre_search='parres' WHERE codigo_ine='05014';
UPDATE municipios SET nombre_search='penamellera alta' WHERE codigo_ine='05015';
UPDATE municipios SET nombre_search='penamellera baja' WHERE codigo_ine='05016';
UPDATE municipios SET nombre_search='pola de somiedo' WHERE codigo_ine='05017';
UPDATE municipios SET nombre_search='quiros' WHERE codigo_ine='05018';
UPDATE municipios SET nombre_search='ribadedeva' WHERE codigo_ine='05019';
UPDATE municipios SET nombre_search='ribadesella' WHERE codigo_ine='05020';
UPDATE municipios SET nombre_search='somiedo' WHERE codigo_ine='05021';
UPDATE municipios SET nombre_search='taramundi' WHERE codigo_ine='05022';
UPDATE municipios SET nombre_search='teverga' WHERE codigo_ine='05023';
UPDATE municipios SET nombre_search='tineo' WHERE codigo_ine='05024';
UPDATE municipios SET nombre_search='alburquerque' WHERE codigo_ine='06001';
UPDATE municipios SET nombre_search='alconchel' WHERE codigo_ine='06002';
UPDATE municipios SET nombre_search='alcantara' WHERE codigo_ine='06003';
UPDATE municipios SET nombre_search='almendralejo' WHERE codigo_ine='06004';
UPDATE municipios SET nombre_search='azuaga' WHERE codigo_ine='06005';
UPDATE municipios SET nombre_search='badajoz' WHERE codigo_ine='06006';
UPDATE municipios SET nombre_search='cabeza del buey' WHERE codigo_ine='06007';
UPDATE municipios SET nombre_search='cheles' WHERE codigo_ine='06008';
UPDATE municipios SET nombre_search='don benito' WHERE codigo_ine='06009';
UPDATE municipios SET nombre_search='fregenal de la sierra' WHERE codigo_ine='06010';
UPDATE municipios SET nombre_search='fuente de cantos' WHERE codigo_ine='06011';
UPDATE municipios SET nombre_search='guarena' WHERE codigo_ine='06012';
UPDATE municipios SET nombre_search='herrera del duque' WHERE codigo_ine='06013';
UPDATE municipios SET nombre_search='jerez de los caballeros' WHERE codigo_ine='06014';
UPDATE municipios SET nombre_search='llerena' WHERE codigo_ine='06015';
UPDATE municipios SET nombre_search='monesterio' WHERE codigo_ine='06016';
UPDATE municipios SET nombre_search='montijo' WHERE codigo_ine='06017';
UPDATE municipios SET nombre_search='merida' WHERE codigo_ine='06018';
UPDATE municipios SET nombre_search='olivenza' WHERE codigo_ine='06019';
UPDATE municipios SET nombre_search='taliga' WHERE codigo_ine='06020';
UPDATE municipios SET nombre_search='valencia de alcantara' WHERE codigo_ine='06021';
UPDATE municipios SET nombre_search='villanueva de la serena' WHERE codigo_ine='06022';
UPDATE municipios SET nombre_search='zafra' WHERE codigo_ine='06023';
UPDATE municipios SET nombre_search='zahinos' WHERE codigo_ine='06024';
UPDATE municipios SET nombre_search='alcudia' WHERE codigo_ine='07001';
UPDATE municipios SET nombre_search='algaida' WHERE codigo_ine='07002';
UPDATE municipios SET nombre_search='ariany' WHERE codigo_ine='07003';
UPDATE municipios SET nombre_search='arta' WHERE codigo_ine='07004';
UPDATE municipios SET nombre_search='campos' WHERE codigo_ine='07005';
UPDATE municipios SET nombre_search='ciutadella de menorca' WHERE codigo_ine='07006';
UPDATE municipios SET nombre_search='costitx' WHERE codigo_ine='07007';
UPDATE municipios SET nombre_search='felanitx' WHERE codigo_ine='07008';
UPDATE municipios SET nombre_search='formentera' WHERE codigo_ine='07009';
UPDATE municipios SET nombre_search='ibiza' WHERE codigo_ine='07010';
UPDATE municipios SET nombre_search='lloret de vistalegre' WHERE codigo_ine='07011';
UPDATE municipios SET nombre_search='manacor' WHERE codigo_ine='07012';
UPDATE municipios SET nombre_search='mao' WHERE codigo_ine='07013';
UPDATE municipios SET nombre_search='montuiri' WHERE codigo_ine='07014';
UPDATE municipios SET nombre_search='palma' WHERE codigo_ine='07015';
UPDATE municipios SET nombre_search='petra' WHERE codigo_ine='07016';
UPDATE municipios SET nombre_search='pollenca' WHERE codigo_ine='07017';
UPDATE municipios SET nombre_search='porreres' WHERE codigo_ine='07018';
UPDATE municipios SET nombre_search='sant joan' WHERE codigo_ine='07019';
UPDATE municipios SET nombre_search='santanyi' WHERE codigo_ine='07020';
UPDATE municipios SET nombre_search='ses salines' WHERE codigo_ine='07021';
UPDATE municipios SET nombre_search='sineu' WHERE codigo_ine='07022';
UPDATE municipios SET nombre_search='soller' WHERE codigo_ine='07023';
UPDATE municipios SET nombre_search='vilafranca de bonany' WHERE codigo_ine='07024';
UPDATE municipios SET nombre_search='arenys de mar' WHERE codigo_ine='08001';
UPDATE municipios SET nombre_search='baga' WHERE codigo_ine='08002';
UPDATE municipios SET nombre_search='barcelona' WHERE codigo_ine='08003';
UPDATE municipios SET nombre_search='beget' WHERE codigo_ine='08004';
UPDATE municipios SET nombre_search='berga' WHERE codigo_ine='08005';
UPDATE municipios SET nombre_search='blanes' WHERE codigo_ine='08006';
UPDATE municipios SET nombre_search='calella' WHERE codigo_ine='08007';
UPDATE municipios SET nombre_search='canet de mar' WHERE codigo_ine='08008';
UPDATE municipios SET nombre_search='cardona' WHERE codigo_ine='08009';
UPDATE municipios SET nombre_search='castellfollit de la roca' WHERE codigo_ine='08010';
UPDATE municipios SET nombre_search='l''estany' WHERE codigo_ine='08011';
UPDATE municipios SET nombre_search='malgrat de mar' WHERE codigo_ine='08012';
UPDATE municipios SET nombre_search='manlleu' WHERE codigo_ine='08013';
UPDATE municipios SET nombre_search='montserrat' WHERE codigo_ine='08014';
UPDATE municipios SET nombre_search='olot' WHERE codigo_ine='08015';
UPDATE municipios SET nombre_search='pineda de mar' WHERE codigo_ine='08016';
UPDATE municipios SET nombre_search='prats de llucanes' WHERE codigo_ine='08017';
UPDATE municipios SET nombre_search='ripoll' WHERE codigo_ine='08018';
UPDATE municipios SET nombre_search='rupit i pruit' WHERE codigo_ine='08019';
UPDATE municipios SET nombre_search='sant hipolit de voltrega' WHERE codigo_ine='08020';
UPDATE municipios SET nombre_search='sant joan de les abadesses' WHERE codigo_ine='08021';
UPDATE municipios SET nombre_search='santa pau' WHERE codigo_ine='08022';
UPDATE municipios SET nombre_search='sitges' WHERE codigo_ine='08023';
UPDATE municipios SET nombre_search='tavertet' WHERE codigo_ine='08024';
UPDATE municipios SET nombre_search='torello' WHERE codigo_ine='08025';
UPDATE municipios SET nombre_search='vic' WHERE codigo_ine='08026';
UPDATE municipios SET nombre_search='aranda de duero' WHERE codigo_ine='09001';
UPDATE municipios SET nombre_search='briviesca' WHERE codigo_ine='09002';
UPDATE municipios SET nombre_search='burgos' WHERE codigo_ine='09003';
UPDATE municipios SET nombre_search='caleruega' WHERE codigo_ine='09004';
UPDATE municipios SET nombre_search='covarrubias' WHERE codigo_ine='09005';
UPDATE municipios SET nombre_search='espinosa de los monteros' WHERE codigo_ine='09006';
UPDATE municipios SET nombre_search='frias' WHERE codigo_ine='09007';
UPDATE municipios SET nombre_search='lerma' WHERE codigo_ine='09008';
UPDATE municipios SET nombre_search='medina de pomar' WHERE codigo_ine='09009';
UPDATE municipios SET nombre_search='miranda de ebro' WHERE codigo_ine='09010';
UPDATE municipios SET nombre_search='ona' WHERE codigo_ine='09011';
UPDATE municipios SET nombre_search='pancorbo' WHERE codigo_ine='09012';
UPDATE municipios SET nombre_search='penaranda de duero' WHERE codigo_ine='09013';
UPDATE municipios SET nombre_search='poza de la sal' WHERE codigo_ine='09014';
UPDATE municipios SET nombre_search='quintanilla de vivar' WHERE codigo_ine='09015';
UPDATE municipios SET nombre_search='roa' WHERE codigo_ine='09016';
UPDATE municipios SET nombre_search='salas de los infantes' WHERE codigo_ine='09017';
UPDATE municipios SET nombre_search='santo domingo de silos' WHERE codigo_ine='09018';
UPDATE municipios SET nombre_search='trespaderne' WHERE codigo_ine='09019';
UPDATE municipios SET nombre_search='villarcayo' WHERE codigo_ine='09020';
UPDATE municipios SET nombre_search='alto campoo' WHERE codigo_ine='10001';
UPDATE municipios SET nombre_search='barcena de cicero' WHERE codigo_ine='10002';
UPDATE municipios SET nombre_search='cabezon de la sal' WHERE codigo_ine='10003';
UPDATE municipios SET nombre_search='camargo' WHERE codigo_ine='10004';
UPDATE municipios SET nombre_search='campoo de enmedio' WHERE codigo_ine='10005';
UPDATE municipios SET nombre_search='castro-urdiales' WHERE codigo_ine='10006';
UPDATE municipios SET nombre_search='comillas' WHERE codigo_ine='10007';
UPDATE municipios SET nombre_search='hermandad de campoo de suso' WHERE codigo_ine='10008';
UPDATE municipios SET nombre_search='laredo' WHERE codigo_ine='10009';
UPDATE municipios SET nombre_search='los corrales de buelna' WHERE codigo_ine='10010';
UPDATE municipios SET nombre_search='pesquera' WHERE codigo_ine='10011';
UPDATE municipios SET nombre_search='potes' WHERE codigo_ine='10012';
UPDATE municipios SET nombre_search='reinosa' WHERE codigo_ine='10013';
UPDATE municipios SET nombre_search='ruiloba' WHERE codigo_ine='10014';
UPDATE municipios SET nombre_search='san vicente de la barquera' WHERE codigo_ine='10015';
UPDATE municipios SET nombre_search='santander' WHERE codigo_ine='10016';
UPDATE municipios SET nombre_search='santillana del mar' WHERE codigo_ine='10017';
UPDATE municipios SET nombre_search='santona' WHERE codigo_ine='10018';
UPDATE municipios SET nombre_search='torrelavega' WHERE codigo_ine='10019';
UPDATE municipios SET nombre_search='voto' WHERE codigo_ine='10020';
UPDATE municipios SET nombre_search='alcala de xivert' WHERE codigo_ine='11001';
UPDATE municipios SET nombre_search='ares del maestrat' WHERE codigo_ine='11002';
UPDATE municipios SET nombre_search='benicarlo' WHERE codigo_ine='11003';
UPDATE municipios SET nombre_search='benicassim' WHERE codigo_ine='11004';
UPDATE municipios SET nombre_search='castellon de la plana' WHERE codigo_ine='11005';
UPDATE municipios SET nombre_search='culla' WHERE codigo_ine='11006';
UPDATE municipios SET nombre_search='la iglesuela del cid' WHERE codigo_ine='11007';
UPDATE municipios SET nombre_search='lucena del cid' WHERE codigo_ine='11008';
UPDATE municipios SET nombre_search='montanejos' WHERE codigo_ine='11009';
UPDATE municipios SET nombre_search='morella' WHERE codigo_ine='11010';
UPDATE municipios SET nombre_search='mosqueruela' WHERE codigo_ine='11011';
UPDATE municipios SET nombre_search='oropesa del mar' WHERE codigo_ine='11012';
UPDATE municipios SET nombre_search='peniscola' WHERE codigo_ine='11013';
UPDATE municipios SET nombre_search='sant mateu' WHERE codigo_ine='11014';
UPDATE municipios SET nombre_search='segorbe' WHERE codigo_ine='11015';
UPDATE municipios SET nombre_search='traiguera' WHERE codigo_ine='11016';
UPDATE municipios SET nombre_search='villafranca del cid' WHERE codigo_ine='11017';
UPDATE municipios SET nombre_search='vinaros' WHERE codigo_ine='11018';
UPDATE municipios SET nombre_search='ceuta' WHERE codigo_ine='12001';
UPDATE municipios SET nombre_search='alcazar de san juan' WHERE codigo_ine='13001';
UPDATE municipios SET nombre_search='almagro' WHERE codigo_ine='13002';
UPDATE municipios SET nombre_search='argamasilla de alba' WHERE codigo_ine='13003';
UPDATE municipios SET nombre_search='ciudad real' WHERE codigo_ine='13004';
UPDATE municipios SET nombre_search='daimiel' WHERE codigo_ine='13005';
UPDATE municipios SET nombre_search='infantes (villanueva)' WHERE codigo_ine='13006';
UPDATE municipios SET nombre_search='la solana' WHERE codigo_ine='13007';
UPDATE municipios SET nombre_search='malagon' WHERE codigo_ine='13008';
UPDATE municipios SET nombre_search='manzanares' WHERE codigo_ine='13009';
UPDATE municipios SET nombre_search='membrilla' WHERE codigo_ine='13010';
UPDATE municipios SET nombre_search='miguelturra' WHERE codigo_ine='13011';
UPDATE municipios SET nombre_search='moral de calatrava' WHERE codigo_ine='13012';
UPDATE municipios SET nombre_search='puertollano' WHERE codigo_ine='13013';
UPDATE municipios SET nombre_search='ruidera' WHERE codigo_ine='13014';
UPDATE municipios SET nombre_search='santa cruz de mudela' WHERE codigo_ine='13015';
UPDATE municipios SET nombre_search='socuellamos' WHERE codigo_ine='13016';
UPDATE municipios SET nombre_search='tomelloso' WHERE codigo_ine='13017';
UPDATE municipios SET nombre_search='valdepenas' WHERE codigo_ine='13018';
UPDATE municipios SET nombre_search='villanueva de los infantes' WHERE codigo_ine='13019';
UPDATE municipios SET nombre_search='viso del marques' WHERE codigo_ine='13020';
UPDATE municipios SET nombre_search='alarcon' WHERE codigo_ine='14001';
UPDATE municipios SET nombre_search='beteta' WHERE codigo_ine='14002';
UPDATE municipios SET nombre_search='canamares' WHERE codigo_ine='14003';
UPDATE municipios SET nombre_search='cuenca' WHERE codigo_ine='14004';
UPDATE municipios SET nombre_search='cuenca (ciudad encantada)' WHERE codigo_ine='14005';
UPDATE municipios SET nombre_search='fuertescusa' WHERE codigo_ine='14006';
UPDATE municipios SET nombre_search='minglanilla' WHERE codigo_ine='14007';
UPDATE municipios SET nombre_search='mota del cuervo' WHERE codigo_ine='14008';
UPDATE municipios SET nombre_search='motilla del palancar' WHERE codigo_ine='14009';
UPDATE municipios SET nombre_search='priego' WHERE codigo_ine='14010';
UPDATE municipios SET nombre_search='san clemente' WHERE codigo_ine='14011';
UPDATE municipios SET nombre_search='tarancon' WHERE codigo_ine='14012';
UPDATE municipios SET nombre_search='tragacete' WHERE codigo_ine='14013';
UPDATE municipios SET nombre_search='una' WHERE codigo_ine='14014';
UPDATE municipios SET nombre_search='valeria' WHERE codigo_ine='14015';
UPDATE municipios SET nombre_search='villalba de la sierra' WHERE codigo_ine='14016';
UPDATE municipios SET nombre_search='brozas' WHERE codigo_ine='15001';
UPDATE municipios SET nombre_search='bejar' WHERE codigo_ine='15002';
UPDATE municipios SET nombre_search='coria' WHERE codigo_ine='15003';
UPDATE municipios SET nombre_search='cuacos de yuste' WHERE codigo_ine='15004';
UPDATE municipios SET nombre_search='caceres' WHERE codigo_ine='15005';
UPDATE municipios SET nombre_search='garrovillas de alconetar' WHERE codigo_ine='15006';
UPDATE municipios SET nombre_search='guadalupe' WHERE codigo_ine='15007';
UPDATE municipios SET nombre_search='hervas' WHERE codigo_ine='15008';
UPDATE municipios SET nombre_search='jarandilla de la vera' WHERE codigo_ine='15009';
UPDATE municipios SET nombre_search='jaraiz de la vera' WHERE codigo_ine='15010';
UPDATE municipios SET nombre_search='losar de la vera' WHERE codigo_ine='15011';
UPDATE municipios SET nombre_search='monfrague' WHERE codigo_ine='15012';
UPDATE municipios SET nombre_search='montanchez' WHERE codigo_ine='15013';
UPDATE municipios SET nombre_search='moraleja' WHERE codigo_ine='15014';
UPDATE municipios SET nombre_search='navalmoral de la mata' WHERE codigo_ine='15015';
UPDATE municipios SET nombre_search='plasencia' WHERE codigo_ine='15016';
UPDATE municipios SET nombre_search='talayuela' WHERE codigo_ine='15017';
UPDATE municipios SET nombre_search='trujillo' WHERE codigo_ine='15018';
UPDATE municipios SET nombre_search='villanueva de la vera' WHERE codigo_ine='15019';
UPDATE municipios SET nombre_search='yuste (monasterio)' WHERE codigo_ine='15020';
UPDATE municipios SET nombre_search='zarza la mayor' WHERE codigo_ine='15021';
UPDATE municipios SET nombre_search='alcala de los gazules' WHERE codigo_ine='16001';
UPDATE municipios SET nombre_search='algeciras' WHERE codigo_ine='16002';
UPDATE municipios SET nombre_search='algodonales' WHERE codigo_ine='16003';
UPDATE municipios SET nombre_search='arcos de la frontera' WHERE codigo_ine='16004';
UPDATE municipios SET nombre_search='benalup-casas viejas' WHERE codigo_ine='16005';
UPDATE municipios SET nombre_search='castellar de la frontera' WHERE codigo_ine='16006';
UPDATE municipios SET nombre_search='chiclana de la frontera' WHERE codigo_ine='16007';
UPDATE municipios SET nombre_search='conil de la frontera' WHERE codigo_ine='16008';
UPDATE municipios SET nombre_search='cadiz' WHERE codigo_ine='16009';
UPDATE municipios SET nombre_search='el puerto de santa maria' WHERE codigo_ine='16010';
UPDATE municipios SET nombre_search='grazalema' WHERE codigo_ine='16011';
UPDATE municipios SET nombre_search='jerez de la frontera' WHERE codigo_ine='16012';
UPDATE municipios SET nombre_search='jimena de la frontera' WHERE codigo_ine='16013';
UPDATE municipios SET nombre_search='la linea de la concepcion' WHERE codigo_ine='16014';
UPDATE municipios SET nombre_search='la silla' WHERE codigo_ine='16015';
UPDATE municipios SET nombre_search='los barrios' WHERE codigo_ine='16016';
UPDATE municipios SET nombre_search='medina sidonia' WHERE codigo_ine='16017';
UPDATE municipios SET nombre_search='olvera' WHERE codigo_ine='16018';
UPDATE municipios SET nombre_search='puerto serrano' WHERE codigo_ine='16019';
UPDATE municipios SET nombre_search='rota' WHERE codigo_ine='16020';
UPDATE municipios SET nombre_search='san fernando' WHERE codigo_ine='16021';
UPDATE municipios SET nombre_search='san roque' WHERE codigo_ine='16022';
UPDATE municipios SET nombre_search='sanlucar de barrameda' WHERE codigo_ine='16023';
UPDATE municipios SET nombre_search='setenil de las bodegas' WHERE codigo_ine='16024';
UPDATE municipios SET nombre_search='tarifa' WHERE codigo_ine='16025';
UPDATE municipios SET nombre_search='ubrique' WHERE codigo_ine='16026';
UPDATE municipios SET nombre_search='vejer de la frontera' WHERE codigo_ine='16027';
UPDATE municipios SET nombre_search='zahara de la sierra' WHERE codigo_ine='16028';
UPDATE municipios SET nombre_search='aguilar de la frontera' WHERE codigo_ine='17001';
UPDATE municipios SET nombre_search='almodovar del rio' WHERE codigo_ine='17002';
UPDATE municipios SET nombre_search='baena' WHERE codigo_ine='17003';
UPDATE municipios SET nombre_search='belalcazar' WHERE codigo_ine='17004';
UPDATE municipios SET nombre_search='bujalance' WHERE codigo_ine='17005';
UPDATE municipios SET nombre_search='cabra' WHERE codigo_ine='17006';
UPDATE municipios SET nombre_search='castro del rio' WHERE codigo_ine='17007';
UPDATE municipios SET nombre_search='cordoba' WHERE codigo_ine='17008';
UPDATE municipios SET nombre_search='espejo' WHERE codigo_ine='17009';
UPDATE municipios SET nombre_search='fernan-nunez' WHERE codigo_ine='17010';
UPDATE municipios SET nombre_search='fuente obejuna' WHERE codigo_ine='17011';
UPDATE municipios SET nombre_search='hinojosa del duque' WHERE codigo_ine='17012';
UPDATE municipios SET nombre_search='iznajar' WHERE codigo_ine='17013';
UPDATE municipios SET nombre_search='la carlota' WHERE codigo_ine='17014';
UPDATE municipios SET nombre_search='lucena' WHERE codigo_ine='17015';
UPDATE municipios SET nombre_search='montilla' WHERE codigo_ine='17016';
UPDATE municipios SET nombre_search='montoro' WHERE codigo_ine='17017';
UPDATE municipios SET nombre_search='palma del rio' WHERE codigo_ine='17018';
UPDATE municipios SET nombre_search='penarroya-pueblonuevo' WHERE codigo_ine='17019';
UPDATE municipios SET nombre_search='posadas' WHERE codigo_ine='17020';
UPDATE municipios SET nombre_search='pozoblanco' WHERE codigo_ine='17021';
UPDATE municipios SET nombre_search='priego de cordoba' WHERE codigo_ine='17022';
UPDATE municipios SET nombre_search='puente genil' WHERE codigo_ine='17023';
UPDATE municipios SET nombre_search='rute' WHERE codigo_ine='17024';
UPDATE municipios SET nombre_search='villanueva de cordoba' WHERE codigo_ine='17025';
UPDATE municipios SET nombre_search='begur' WHERE codigo_ine='18001';
UPDATE municipios SET nombre_search='besalu' WHERE codigo_ine='18002';
UPDATE municipios SET nombre_search='cadaques' WHERE codigo_ine='18003';
UPDATE municipios SET nombre_search='camprodon' WHERE codigo_ine='18004';
UPDATE municipios SET nombre_search='girona' WHERE codigo_ine='18005';
UPDATE municipios SET nombre_search='l''escala' WHERE codigo_ine='18006';
UPDATE municipios SET nombre_search='lloret de mar' WHERE codigo_ine='18007';
UPDATE municipios SET nombre_search='llivia' WHERE codigo_ine='18008';
UPDATE municipios SET nombre_search='palamos' WHERE codigo_ine='18009';
UPDATE municipios SET nombre_search='pals' WHERE codigo_ine='18010';
UPDATE municipios SET nombre_search='peratallada' WHERE codigo_ine='18011';
UPDATE municipios SET nombre_search='puigcerda' WHERE codigo_ine='18012';
UPDATE municipios SET nombre_search='queralbs' WHERE codigo_ine='18013';
UPDATE municipios SET nombre_search='roses' WHERE codigo_ine='18014';
UPDATE municipios SET nombre_search='setcases' WHERE codigo_ine='18015';
UPDATE municipios SET nombre_search='torroella de montgri' WHERE codigo_ine='18016';
UPDATE municipios SET nombre_search='tossa de mar' WHERE codigo_ine='18017';
UPDATE municipios SET nombre_search='alhama de granada' WHERE codigo_ine='19001';
UPDATE municipios SET nombre_search='almunecar' WHERE codigo_ine='19002';
UPDATE municipios SET nombre_search='baza' WHERE codigo_ine='19003';
UPDATE municipios SET nombre_search='bubion' WHERE codigo_ine='19004';
UPDATE municipios SET nombre_search='berchules' WHERE codigo_ine='19005';
UPDATE municipios SET nombre_search='capileira' WHERE codigo_ine='19006';
UPDATE municipios SET nombre_search='castril' WHERE codigo_ine='19007';
UPDATE municipios SET nombre_search='cadiar' WHERE codigo_ine='19008';
UPDATE municipios SET nombre_search='granada' WHERE codigo_ine='19009';
UPDATE municipios SET nombre_search='guadix' WHERE codigo_ine='19010';
UPDATE municipios SET nombre_search='guejar sierra' WHERE codigo_ine='19011';
UPDATE municipios SET nombre_search='huescar' WHERE codigo_ine='19012';
UPDATE municipios SET nombre_search='lanjaron' WHERE codigo_ine='19013';
UPDATE municipios SET nombre_search='loja' WHERE codigo_ine='19014';
UPDATE municipios SET nombre_search='mecina fondales' WHERE codigo_ine='19015';
UPDATE municipios SET nombre_search='monachil' WHERE codigo_ine='19016';
UPDATE municipios SET nombre_search='montefrio' WHERE codigo_ine='19017';
UPDATE municipios SET nombre_search='motril' WHERE codigo_ine='19018';
UPDATE municipios SET nombre_search='nerja (limite con malaga)' WHERE codigo_ine='19019';
UPDATE municipios SET nombre_search='orce' WHERE codigo_ine='19020';
UPDATE municipios SET nombre_search='orgiva' WHERE codigo_ine='19021';
UPDATE municipios SET nombre_search='pitres' WHERE codigo_ine='19022';
UPDATE municipios SET nombre_search='portugos' WHERE codigo_ine='19023';
UPDATE municipios SET nombre_search='salobrena' WHERE codigo_ine='19024';
UPDATE municipios SET nombre_search='santa fe' WHERE codigo_ine='19025';
UPDATE municipios SET nombre_search='trevelez' WHERE codigo_ine='19026';
UPDATE municipios SET nombre_search='ugijar' WHERE codigo_ine='19027';
UPDATE municipios SET nombre_search='valor' WHERE codigo_ine='19028';
UPDATE municipios SET nombre_search='yegen' WHERE codigo_ine='19029';
UPDATE municipios SET nombre_search='atienza' WHERE codigo_ine='20001';
UPDATE municipios SET nombre_search='azuqueca de henares' WHERE codigo_ine='20002';
UPDATE municipios SET nombre_search='brihuega' WHERE codigo_ine='20003';
UPDATE municipios SET nombre_search='budia' WHERE codigo_ine='20004';
UPDATE municipios SET nombre_search='cabanillas del campo' WHERE codigo_ine='20005';
UPDATE municipios SET nombre_search='cifuentes' WHERE codigo_ine='20006';
UPDATE municipios SET nombre_search='guadalajara' WHERE codigo_ine='20007';
UPDATE municipios SET nombre_search='hita' WHERE codigo_ine='20008';
UPDATE municipios SET nombre_search='horche' WHERE codigo_ine='20009';
UPDATE municipios SET nombre_search='medinaceli' WHERE codigo_ine='20010';
UPDATE municipios SET nombre_search='molina de aragon' WHERE codigo_ine='20011';
UPDATE municipios SET nombre_search='mondejar' WHERE codigo_ine='20012';
UPDATE municipios SET nombre_search='pastrana' WHERE codigo_ine='20013';
UPDATE municipios SET nombre_search='sacedon' WHERE codigo_ine='20014';
UPDATE municipios SET nombre_search='siguenza' WHERE codigo_ine='20015';
UPDATE municipios SET nombre_search='torija' WHERE codigo_ine='20016';
UPDATE municipios SET nombre_search='trillo' WHERE codigo_ine='20017';
UPDATE municipios SET nombre_search='yunquera de henares' WHERE codigo_ine='20018';
UPDATE municipios SET nombre_search='aretxabaleta' WHERE codigo_ine='21001';
UPDATE municipios SET nombre_search='arrasate/mondragon' WHERE codigo_ine='21002';
UPDATE municipios SET nombre_search='azkoitia' WHERE codigo_ine='21003';
UPDATE municipios SET nombre_search='azpeitia' WHERE codigo_ine='21004';
UPDATE municipios SET nombre_search='beasain' WHERE codigo_ine='21005';
UPDATE municipios SET nombre_search='bergara' WHERE codigo_ine='21006';
UPDATE municipios SET nombre_search='deba' WHERE codigo_ine='21007';
UPDATE municipios SET nombre_search='eibar' WHERE codigo_ine='21008';
UPDATE municipios SET nombre_search='eskoriatza' WHERE codigo_ine='21009';
UPDATE municipios SET nombre_search='getaria' WHERE codigo_ine='21010';
UPDATE municipios SET nombre_search='hondarribia' WHERE codigo_ine='21011';
UPDATE municipios SET nombre_search='irun' WHERE codigo_ine='21012';
UPDATE municipios SET nombre_search='loyola' WHERE codigo_ine='21013';
UPDATE municipios SET nombre_search='onati' WHERE codigo_ine='21014';
UPDATE municipios SET nombre_search='pasaia' WHERE codigo_ine='21015';
UPDATE municipios SET nombre_search='san sebastian/donostia' WHERE codigo_ine='21016';
UPDATE municipios SET nombre_search='tolosa' WHERE codigo_ine='21017';
UPDATE municipios SET nombre_search='zarautz' WHERE codigo_ine='21018';
UPDATE municipios SET nombre_search='zumaia' WHERE codigo_ine='21019';
UPDATE municipios SET nombre_search='zumarraga' WHERE codigo_ine='21020';
UPDATE municipios SET nombre_search='almonaster la real' WHERE codigo_ine='22001';
UPDATE municipios SET nombre_search='almonte' WHERE codigo_ine='22002';
UPDATE municipios SET nombre_search='alajar' WHERE codigo_ine='22003';
UPDATE municipios SET nombre_search='aracena' WHERE codigo_ine='22004';
UPDATE municipios SET nombre_search='aroche' WHERE codigo_ine='22005';
UPDATE municipios SET nombre_search='ayamonte' WHERE codigo_ine='22006';
UPDATE municipios SET nombre_search='cartaya' WHERE codigo_ine='22007';
UPDATE municipios SET nombre_search='castano del robledo' WHERE codigo_ine='22008';
UPDATE municipios SET nombre_search='cortegana' WHERE codigo_ine='22009';
UPDATE municipios SET nombre_search='cumbres mayores' WHERE codigo_ine='22010';
UPDATE municipios SET nombre_search='el rocio' WHERE codigo_ine='22011';
UPDATE municipios SET nombre_search='fuenteheridos' WHERE codigo_ine='22012';
UPDATE municipios SET nombre_search='huelva' WHERE codigo_ine='22013';
UPDATE municipios SET nombre_search='isla cristina' WHERE codigo_ine='22014';
UPDATE municipios SET nombre_search='jabugo' WHERE codigo_ine='22015';
UPDATE municipios SET nombre_search='la palma del condado' WHERE codigo_ine='22016';
UPDATE municipios SET nombre_search='lepe' WHERE codigo_ine='22017';
UPDATE municipios SET nombre_search='matalascanas' WHERE codigo_ine='22018';
UPDATE municipios SET nombre_search='mazagon' WHERE codigo_ine='22019';
UPDATE municipios SET nombre_search='moguer' WHERE codigo_ine='22020';
UPDATE municipios SET nombre_search='palos de la frontera' WHERE codigo_ine='22021';
UPDATE municipios SET nombre_search='punta umbria' WHERE codigo_ine='22022';
UPDATE municipios SET nombre_search='valverde del camino' WHERE codigo_ine='22023';
UPDATE municipios SET nombre_search='zufre' WHERE codigo_ine='22024';
UPDATE municipios SET nombre_search='ainsa-sobrarbe' WHERE codigo_ine='23001';
UPDATE municipios SET nombre_search='anso' WHERE codigo_ine='23002';
UPDATE municipios SET nombre_search='barbastro' WHERE codigo_ine='23003';
UPDATE municipios SET nombre_search='benasque' WHERE codigo_ine='23004';
UPDATE municipios SET nombre_search='bielsa' WHERE codigo_ine='23005';
UPDATE municipios SET nombre_search='boltana' WHERE codigo_ine='23006';
UPDATE municipios SET nombre_search='broto' WHERE codigo_ine='23007';
UPDATE municipios SET nombre_search='gistain' WHERE codigo_ine='23008';
UPDATE municipios SET nombre_search='hecho' WHERE codigo_ine='23009';
UPDATE municipios SET nombre_search='huesca' WHERE codigo_ine='23010';
UPDATE municipios SET nombre_search='jaca' WHERE codigo_ine='23011';
UPDATE municipios SET nombre_search='monzon' WHERE codigo_ine='23012';
UPDATE municipios SET nombre_search='panticosa' WHERE codigo_ine='23013';
UPDATE municipios SET nombre_search='plan' WHERE codigo_ine='23014';
UPDATE municipios SET nombre_search='sabinanigo' WHERE codigo_ine='23015';
UPDATE municipios SET nombre_search='torla-ordesa' WHERE codigo_ine='23016';
UPDATE municipios SET nombre_search='aldeanueva de ebro' WHERE codigo_ine='24001';
UPDATE municipios SET nombre_search='alfaro' WHERE codigo_ine='24002';
UPDATE municipios SET nombre_search='arnedo' WHERE codigo_ine='24003';
UPDATE municipios SET nombre_search='autol' WHERE codigo_ine='24004';
UPDATE municipios SET nombre_search='briones' WHERE codigo_ine='24005';
UPDATE municipios SET nombre_search='calahorra' WHERE codigo_ine='24006';
UPDATE municipios SET nombre_search='cenicero' WHERE codigo_ine='24007';
UPDATE municipios SET nombre_search='cervera del rio alhama' WHERE codigo_ine='24008';
UPDATE municipios SET nombre_search='ezcaray' WHERE codigo_ine='24009';
UPDATE municipios SET nombre_search='haro' WHERE codigo_ine='24010';
UPDATE municipios SET nombre_search='logrono' WHERE codigo_ine='24011';
UPDATE municipios SET nombre_search='najera' WHERE codigo_ine='24012';
UPDATE municipios SET nombre_search='quel' WHERE codigo_ine='24013';
UPDATE municipios SET nombre_search='san asensio' WHERE codigo_ine='24014';
UPDATE municipios SET nombre_search='santo domingo de la calzada' WHERE codigo_ine='24015';
UPDATE municipios SET nombre_search='valverde en rioja' WHERE codigo_ine='24016';
UPDATE municipios SET nombre_search='abalos' WHERE codigo_ine='24017';
UPDATE municipios SET nombre_search='antigua' WHERE codigo_ine='25001';
UPDATE municipios SET nombre_search='artenara' WHERE codigo_ine='25002';
UPDATE municipios SET nombre_search='arucas' WHERE codigo_ine='25003';
UPDATE municipios SET nombre_search='betancuria' WHERE codigo_ine='25004';
UPDATE municipios SET nombre_search='galdar' WHERE codigo_ine='25005';
UPDATE municipios SET nombre_search='la oliva' WHERE codigo_ine='25006';
UPDATE municipios SET nombre_search='las palmas de gran canaria' WHERE codigo_ine='25007';
UPDATE municipios SET nombre_search='maspalomas-san bartolome de tirajana' WHERE codigo_ine='25008';
UPDATE municipios SET nombre_search='mogan' WHERE codigo_ine='25009';
UPDATE municipios SET nombre_search='puerto del rosario' WHERE codigo_ine='25010';
UPDATE municipios SET nombre_search='pajara' WHERE codigo_ine='25011';
UPDATE municipios SET nombre_search='tejeda' WHERE codigo_ine='25012';
UPDATE municipios SET nombre_search='telde' WHERE codigo_ine='25013';
UPDATE municipios SET nombre_search='tuineje' WHERE codigo_ine='25014';
UPDATE municipios SET nombre_search='acebedo' WHERE codigo_ine='26001';
UPDATE municipios SET nombre_search='astorga' WHERE codigo_ine='26002';
UPDATE municipios SET nombre_search='babia' WHERE codigo_ine='26003';
UPDATE municipios SET nombre_search='bembibre' WHERE codigo_ine='26004';
UPDATE municipios SET nombre_search='bonar' WHERE codigo_ine='26005';
UPDATE municipios SET nombre_search='cabrillanes' WHERE codigo_ine='26006';
UPDATE municipios SET nombre_search='cacabelos' WHERE codigo_ine='26007';
UPDATE municipios SET nombre_search='cistierna' WHERE codigo_ine='26008';
UPDATE municipios SET nombre_search='la baneza' WHERE codigo_ine='26009';
UPDATE municipios SET nombre_search='leon' WHERE codigo_ine='26010';
UPDATE municipios SET nombre_search='mansilla de las mulas' WHERE codigo_ine='26011';
UPDATE municipios SET nombre_search='ponferrada' WHERE codigo_ine='26012';
UPDATE municipios SET nombre_search='puebla de sanabria' WHERE codigo_ine='26013';
UPDATE municipios SET nombre_search='riano' WHERE codigo_ine='26014';
UPDATE municipios SET nombre_search='sahagun' WHERE codigo_ine='26015';
UPDATE municipios SET nombre_search='san andres del rabanedo' WHERE codigo_ine='26016';
UPDATE municipios SET nombre_search='valencia de don juan' WHERE codigo_ine='26017';
UPDATE municipios SET nombre_search='valverde de la virgen' WHERE codigo_ine='26018';
UPDATE municipios SET nombre_search='villafranca del bierzo' WHERE codigo_ine='26019';
UPDATE municipios SET nombre_search='balaguer' WHERE codigo_ine='27001';
UPDATE municipios SET nombre_search='baqueira-beret' WHERE codigo_ine='27002';
UPDATE municipios SET nombre_search='cervera' WHERE codigo_ine='27003';
UPDATE municipios SET nombre_search='espot' WHERE codigo_ine='27004';
UPDATE municipios SET nombre_search='esterri d''aneu' WHERE codigo_ine='27005';
UPDATE municipios SET nombre_search='la seu d''urgell' WHERE codigo_ine='27006';
UPDATE municipios SET nombre_search='les (val d''aran)' WHERE codigo_ine='27007';
UPDATE municipios SET nombre_search='lleida' WHERE codigo_ine='27008';
UPDATE municipios SET nombre_search='mollerussa' WHERE codigo_ine='27009';
UPDATE municipios SET nombre_search='solsona' WHERE codigo_ine='27010';
UPDATE municipios SET nombre_search='sort' WHERE codigo_ine='27011';
UPDATE municipios SET nombre_search='tremp' WHERE codigo_ine='27012';
UPDATE municipios SET nombre_search='tarrega' WHERE codigo_ine='27013';
UPDATE municipios SET nombre_search='vielha e mijaran' WHERE codigo_ine='27014';
UPDATE municipios SET nombre_search='ager' WHERE codigo_ine='27015';
UPDATE municipios SET nombre_search='becerrea' WHERE codigo_ine='28001';
UPDATE municipios SET nombre_search='burela' WHERE codigo_ine='28002';
UPDATE municipios SET nombre_search='chantada' WHERE codigo_ine='28003';
UPDATE municipios SET nombre_search='fonsagrada (a)' WHERE codigo_ine='28004';
UPDATE municipios SET nombre_search='foz' WHERE codigo_ine='28005';
UPDATE municipios SET nombre_search='lugo' WHERE codigo_ine='28006';
UPDATE municipios SET nombre_search='monforte de lemos' WHERE codigo_ine='28007';
UPDATE municipios SET nombre_search='navia de suarna' WHERE codigo_ine='28008';
UPDATE municipios SET nombre_search='pedrafita do cebreiro' WHERE codigo_ine='28009';
UPDATE municipios SET nombre_search='ribadeo' WHERE codigo_ine='28010';
UPDATE municipios SET nombre_search='sarria' WHERE codigo_ine='28011';
UPDATE municipios SET nombre_search='vilalba' WHERE codigo_ine='28012';
UPDATE municipios SET nombre_search='viveiro' WHERE codigo_ine='28013';
UPDATE municipios SET nombre_search='alcala de henares' WHERE codigo_ine='29001';
UPDATE municipios SET nombre_search='alcorcon' WHERE codigo_ine='29002';
UPDATE municipios SET nombre_search='aranjuez' WHERE codigo_ine='29003';
UPDATE municipios SET nombre_search='buitrago del lozoya' WHERE codigo_ine='29004';
UPDATE municipios SET nombre_search='cercedilla' WHERE codigo_ine='29005';
UPDATE municipios SET nombre_search='chinchon' WHERE codigo_ine='29006';
UPDATE municipios SET nombre_search='colmenar viejo' WHERE codigo_ine='29007';
UPDATE municipios SET nombre_search='el escorial' WHERE codigo_ine='29008';
UPDATE municipios SET nombre_search='el paular' WHERE codigo_ine='29009';
UPDATE municipios SET nombre_search='fuenlabrada' WHERE codigo_ine='29010';
UPDATE municipios SET nombre_search='getafe' WHERE codigo_ine='29011';
UPDATE municipios SET nombre_search='leganes' WHERE codigo_ine='29012';
UPDATE municipios SET nombre_search='los molinos' WHERE codigo_ine='29013';
UPDATE municipios SET nombre_search='madrid' WHERE codigo_ine='29014';
UPDATE municipios SET nombre_search='manzanares el real' WHERE codigo_ine='29015';
UPDATE municipios SET nombre_search='mostoles' WHERE codigo_ine='29016';
UPDATE municipios SET nombre_search='navacerrada' WHERE codigo_ine='29017';
UPDATE municipios SET nombre_search='patones' WHERE codigo_ine='29018';
UPDATE municipios SET nombre_search='rascafria' WHERE codigo_ine='29019';
UPDATE municipios SET nombre_search='san lorenzo de el escorial' WHERE codigo_ine='29020';
UPDATE municipios SET nombre_search='melilla' WHERE codigo_ine='30001';
UPDATE municipios SET nombre_search='abaran' WHERE codigo_ine='31001';
UPDATE municipios SET nombre_search='archena' WHERE codigo_ine='31002';
UPDATE municipios SET nombre_search='calasparra' WHERE codigo_ine='31003';
UPDATE municipios SET nombre_search='caravaca de la cruz' WHERE codigo_ine='31004';
UPDATE municipios SET nombre_search='cartagena' WHERE codigo_ine='31005';
UPDATE municipios SET nombre_search='cehegin' WHERE codigo_ine='31006';
UPDATE municipios SET nombre_search='cieza' WHERE codigo_ine='31007';
UPDATE municipios SET nombre_search='fortuna' WHERE codigo_ine='31008';
UPDATE municipios SET nombre_search='jumilla' WHERE codigo_ine='31009';
UPDATE municipios SET nombre_search='la union' WHERE codigo_ine='31010';
UPDATE municipios SET nombre_search='lorca' WHERE codigo_ine='31011';
UPDATE municipios SET nombre_search='mazarron' WHERE codigo_ine='31012';
UPDATE municipios SET nombre_search='moratalla' WHERE codigo_ine='31013';
UPDATE municipios SET nombre_search='mula' WHERE codigo_ine='31014';
UPDATE municipios SET nombre_search='murcia' WHERE codigo_ine='31015';
UPDATE municipios SET nombre_search='san javier' WHERE codigo_ine='31016';
UPDATE municipios SET nombre_search='torre-pacheco' WHERE codigo_ine='31017';
UPDATE municipios SET nombre_search='yecla' WHERE codigo_ine='31018';
UPDATE municipios SET nombre_search='aguilas' WHERE codigo_ine='31019';
UPDATE municipios SET nombre_search='alozaina' WHERE codigo_ine='32001';
UPDATE municipios SET nombre_search='antequera' WHERE codigo_ine='32002';
UPDATE municipios SET nombre_search='archidona' WHERE codigo_ine='32003';
UPDATE municipios SET nombre_search='ardales' WHERE codigo_ine='32004';
UPDATE municipios SET nombre_search='canillas de aceituno' WHERE codigo_ine='32005';
UPDATE municipios SET nombre_search='casares' WHERE codigo_ine='32006';
UPDATE municipios SET nombre_search='competa' WHERE codigo_ine='32007';
UPDATE municipios SET nombre_search='el burgo' WHERE codigo_ine='32008';
UPDATE municipios SET nombre_search='estepona' WHERE codigo_ine='32009';
UPDATE municipios SET nombre_search='frigiliana' WHERE codigo_ine='32010';
UPDATE municipios SET nombre_search='fuengirola' WHERE codigo_ine='32011';
UPDATE municipios SET nombre_search='gaucin' WHERE codigo_ine='32012';
UPDATE municipios SET nombre_search='istan' WHERE codigo_ine='32013';
UPDATE municipios SET nombre_search='marbella' WHERE codigo_ine='32014';
UPDATE municipios SET nombre_search='mijas' WHERE codigo_ine='32015';
UPDATE municipios SET nombre_search='malaga' WHERE codigo_ine='32016';
UPDATE municipios SET nombre_search='nerja' WHERE codigo_ine='32017';
UPDATE municipios SET nombre_search='ojen' WHERE codigo_ine='32018';
UPDATE municipios SET nombre_search='ronda' WHERE codigo_ine='32019';
UPDATE municipios SET nombre_search='sayalonga' WHERE codigo_ine='32020';
UPDATE municipios SET nombre_search='tolox' WHERE codigo_ine='32021';
UPDATE municipios SET nombre_search='torrox' WHERE codigo_ine='32022';
UPDATE municipios SET nombre_search='velez-malaga' WHERE codigo_ine='32023';
UPDATE municipios SET nombre_search='yunquera' WHERE codigo_ine='32024';
UPDATE municipios SET nombre_search='alora' WHERE codigo_ine='32025';
UPDATE municipios SET nombre_search='abarzuza' WHERE codigo_ine='33001';
UPDATE municipios SET nombre_search='alsasua/altsasu' WHERE codigo_ine='33002';
UPDATE municipios SET nombre_search='aoiz/agoitz' WHERE codigo_ine='33003';
UPDATE municipios SET nombre_search='artajona' WHERE codigo_ine='33004';
UPDATE municipios SET nombre_search='burguete/auritz' WHERE codigo_ine='33005';
UPDATE municipios SET nombre_search='erronkari' WHERE codigo_ine='33006';
UPDATE municipios SET nombre_search='estella-lizarra' WHERE codigo_ine='33007';
UPDATE municipios SET nombre_search='isaba' WHERE codigo_ine='33008';
UPDATE municipios SET nombre_search='lekunberri' WHERE codigo_ine='33009';
UPDATE municipios SET nombre_search='lumbier' WHERE codigo_ine='33010';
UPDATE municipios SET nombre_search='mendigorria' WHERE codigo_ine='33011';
UPDATE municipios SET nombre_search='ochagavia' WHERE codigo_ine='33012';
UPDATE municipios SET nombre_search='olite/erriberri' WHERE codigo_ine='33013';
UPDATE municipios SET nombre_search='pamplona/iruna' WHERE codigo_ine='33014';
UPDATE municipios SET nombre_search='puente la reina/gares' WHERE codigo_ine='33015';
UPDATE municipios SET nombre_search='roncal' WHERE codigo_ine='33016';
UPDATE municipios SET nombre_search='roncesvalles' WHERE codigo_ine='33017';
UPDATE municipios SET nombre_search='sanguesa' WHERE codigo_ine='33018';
UPDATE municipios SET nombre_search='tudela' WHERE codigo_ine='33019';
UPDATE municipios SET nombre_search='ujue' WHERE codigo_ine='33020';
UPDATE municipios SET nombre_search='uncastillo' WHERE codigo_ine='33021';
UPDATE municipios SET nombre_search='a gudina' WHERE codigo_ine='34001';
UPDATE municipios SET nombre_search='allariz' WHERE codigo_ine='34002';
UPDATE municipios SET nombre_search='castro caldelas' WHERE codigo_ine='34003';
UPDATE municipios SET nombre_search='celanova' WHERE codigo_ine='34004';
UPDATE municipios SET nombre_search='manzaneda' WHERE codigo_ine='34005';
UPDATE municipios SET nombre_search='montederramo' WHERE codigo_ine='34006';
UPDATE municipios SET nombre_search='o carballino' WHERE codigo_ine='34007';
UPDATE municipios SET nombre_search='ourense' WHERE codigo_ine='34008';
UPDATE municipios SET nombre_search='ribadavia' WHERE codigo_ine='34009';
UPDATE municipios SET nombre_search='trives' WHERE codigo_ine='34010';
UPDATE municipios SET nombre_search='verin' WHERE codigo_ine='34011';
UPDATE municipios SET nombre_search='viana do bolo' WHERE codigo_ine='34012';
UPDATE municipios SET nombre_search='xinzo de limia' WHERE codigo_ine='34013';
UPDATE municipios SET nombre_search='aguilar de campoo' WHERE codigo_ine='35001';
UPDATE municipios SET nombre_search='becerril de campos' WHERE codigo_ine='35002';
UPDATE municipios SET nombre_search='carrion de los condes' WHERE codigo_ine='35003';
UPDATE municipios SET nombre_search='cervera de pisuerga' WHERE codigo_ine='35004';
UPDATE municipios SET nombre_search='duenas' WHERE codigo_ine='35005';
UPDATE municipios SET nombre_search='fromista' WHERE codigo_ine='35006';
UPDATE municipios SET nombre_search='guardo' WHERE codigo_ine='35007';
UPDATE municipios SET nombre_search='palencia' WHERE codigo_ine='35008';
UPDATE municipios SET nombre_search='saldana' WHERE codigo_ine='35009';
UPDATE municipios SET nombre_search='villalcazar de sirga' WHERE codigo_ine='35010';
UPDATE municipios SET nombre_search='a guarda' WHERE codigo_ine='36001';
UPDATE municipios SET nombre_search='baiona' WHERE codigo_ine='36002';
UPDATE municipios SET nombre_search='bueu' WHERE codigo_ine='36003';
UPDATE municipios SET nombre_search='cambados' WHERE codigo_ine='36004';
UPDATE municipios SET nombre_search='cangas' WHERE codigo_ine='36005';
UPDATE municipios SET nombre_search='combarro' WHERE codigo_ine='36006';
UPDATE municipios SET nombre_search='marin' WHERE codigo_ine='36007';
UPDATE municipios SET nombre_search='moana' WHERE codigo_ine='36008';
UPDATE municipios SET nombre_search='o grove' WHERE codigo_ine='36009';
UPDATE municipios SET nombre_search='oia' WHERE codigo_ine='36010';
UPDATE municipios SET nombre_search='pontevedra' WHERE codigo_ine='36011';
UPDATE municipios SET nombre_search='redondela' WHERE codigo_ine='36012';
UPDATE municipios SET nombre_search='sanxenxo' WHERE codigo_ine='36013';
UPDATE municipios SET nombre_search='tui' WHERE codigo_ine='36014';
UPDATE municipios SET nombre_search='vigo' WHERE codigo_ine='36015';
UPDATE municipios SET nombre_search='vilagarcia de arousa' WHERE codigo_ine='36016';
UPDATE municipios SET nombre_search='candelario' WHERE codigo_ine='37001';
UPDATE municipios SET nombre_search='cepeda' WHERE codigo_ine='37002';
UPDATE municipios SET nombre_search='ciudad rodrigo' WHERE codigo_ine='37003';
UPDATE municipios SET nombre_search='hinojosa de duero' WHERE codigo_ine='37004';
UPDATE municipios SET nombre_search='la alberca' WHERE codigo_ine='37005';
UPDATE municipios SET nombre_search='ledesma' WHERE codigo_ine='37006';
UPDATE municipios SET nombre_search='lumbrales' WHERE codigo_ine='37007';
UPDATE municipios SET nombre_search='miranda del castanar' WHERE codigo_ine='37008';
UPDATE municipios SET nombre_search='mogarraz' WHERE codigo_ine='37009';
UPDATE municipios SET nombre_search='pena de francia' WHERE codigo_ine='37010';
UPDATE municipios SET nombre_search='salamanca' WHERE codigo_ine='37011';
UPDATE municipios SET nombre_search='san martin del castanar' WHERE codigo_ine='37012';
UPDATE municipios SET nombre_search='vitigudino' WHERE codigo_ine='37013';
UPDATE municipios SET nombre_search='adeje' WHERE codigo_ine='38001';
UPDATE municipios SET nombre_search='anaga' WHERE codigo_ine='38002';
UPDATE municipios SET nombre_search='buenavista del norte' WHERE codigo_ine='38003';
UPDATE municipios SET nombre_search='el hierro' WHERE codigo_ine='38004';
UPDATE municipios SET nombre_search='garachico' WHERE codigo_ine='38005';
UPDATE municipios SET nombre_search='icod de los vinos' WHERE codigo_ine='38006';
UPDATE municipios SET nombre_search='la gomera' WHERE codigo_ine='38007';
UPDATE municipios SET nombre_search='la laguna' WHERE codigo_ine='38008';
UPDATE municipios SET nombre_search='la palma' WHERE codigo_ine='38009';
UPDATE municipios SET nombre_search='los realejos' WHERE codigo_ine='38010';
UPDATE municipios SET nombre_search='puerto de la cruz' WHERE codigo_ine='38011';
UPDATE municipios SET nombre_search='santa cruz de tenerife' WHERE codigo_ine='38012';
UPDATE municipios SET nombre_search='santiago del teide' WHERE codigo_ine='38013';
UPDATE municipios SET nombre_search='vilaflor' WHERE codigo_ine='38014';
UPDATE municipios SET nombre_search='ayllon' WHERE codigo_ine='39001';
UPDATE municipios SET nombre_search='carbonero el mayor' WHERE codigo_ine='39002';
UPDATE municipios SET nombre_search='cuellar' WHERE codigo_ine='39003';
UPDATE municipios SET nombre_search='la granja de san ildefonso' WHERE codigo_ine='39004';
UPDATE municipios SET nombre_search='navas de riofrio' WHERE codigo_ine='39005';
UPDATE municipios SET nombre_search='pedraza de la sierra' WHERE codigo_ine='39006';
UPDATE municipios SET nombre_search='riaza' WHERE codigo_ine='39007';
UPDATE municipios SET nombre_search='san ildefonso' WHERE codigo_ine='39008';
UPDATE municipios SET nombre_search='segovia' WHERE codigo_ine='39009';
UPDATE municipios SET nombre_search='sepulveda' WHERE codigo_ine='39010';
UPDATE municipios SET nombre_search='turegano' WHERE codigo_ine='39011';
UPDATE municipios SET nombre_search='alanis' WHERE codigo_ine='40001';
UPDATE municipios SET nombre_search='alcala de guadaira' WHERE codigo_ine='40002';
UPDATE municipios SET nombre_search='carmona' WHERE codigo_ine='40003';
UPDATE municipios SET nombre_search='cazalla de la sierra' WHERE codigo_ine='40004';
UPDATE municipios SET nombre_search='constantina' WHERE codigo_ine='40005';
UPDATE municipios SET nombre_search='dos hermanas' WHERE codigo_ine='40006';
UPDATE municipios SET nombre_search='el pedroso' WHERE codigo_ine='40007';
UPDATE municipios SET nombre_search='el ronquillo' WHERE codigo_ine='40008';
UPDATE municipios SET nombre_search='estepa' WHERE codigo_ine='40009';
UPDATE municipios SET nombre_search='guadalcanal' WHERE codigo_ine='40010';
UPDATE municipios SET nombre_search='lebrija' WHERE codigo_ine='40011';
UPDATE municipios SET nombre_search='lora del rio' WHERE codigo_ine='40012';
UPDATE municipios SET nombre_search='marchena' WHERE codigo_ine='40013';
UPDATE municipios SET nombre_search='moron de la frontera' WHERE codigo_ine='40014';
UPDATE municipios SET nombre_search='osuna' WHERE codigo_ine='40015';
UPDATE municipios SET nombre_search='palomares del rio' WHERE codigo_ine='40016';
UPDATE municipios SET nombre_search='penaflor' WHERE codigo_ine='40017';
UPDATE municipios SET nombre_search='sevilla' WHERE codigo_ine='40018';
UPDATE municipios SET nombre_search='utrera' WHERE codigo_ine='40019';
UPDATE municipios SET nombre_search='ecija' WHERE codigo_ine='40020';
UPDATE municipios SET nombre_search='almazan' WHERE codigo_ine='41001';
UPDATE municipios SET nombre_search='berlanga de duero' WHERE codigo_ine='41002';
UPDATE municipios SET nombre_search='covaleda' WHERE codigo_ine='41003';
UPDATE municipios SET nombre_search='el burgo de osma' WHERE codigo_ine='41004';
UPDATE municipios SET nombre_search='laguna negra' WHERE codigo_ine='41005';
UPDATE municipios SET nombre_search='navaleno' WHERE codigo_ine='41006';
UPDATE municipios SET nombre_search='olvega' WHERE codigo_ine='41007';
UPDATE municipios SET nombre_search='san esteban de gormaz' WHERE codigo_ine='41008';
UPDATE municipios SET nombre_search='soria' WHERE codigo_ine='41009';
UPDATE municipios SET nombre_search='vinuesa' WHERE codigo_ine='41010';
UPDATE municipios SET nombre_search='agreda' WHERE codigo_ine='41011';
UPDATE municipios SET nombre_search='amposta' WHERE codigo_ine='42001';
UPDATE municipios SET nombre_search='calafell' WHERE codigo_ine='42002';
UPDATE municipios SET nombre_search='cambrils' WHERE codigo_ine='42003';
UPDATE municipios SET nombre_search='deltebre' WHERE codigo_ine='42004';
UPDATE municipios SET nombre_search='el vendrell' WHERE codigo_ine='42005';
UPDATE municipios SET nombre_search='falset' WHERE codigo_ine='42006';
UPDATE municipios SET nombre_search='gandesa' WHERE codigo_ine='42007';
UPDATE municipios SET nombre_search='l''espluga de francoli' WHERE codigo_ine='42008';
UPDATE municipios SET nombre_search='montblanc' WHERE codigo_ine='42009';
UPDATE municipios SET nombre_search='poblet' WHERE codigo_ine='42010';
UPDATE municipios SET nombre_search='reus' WHERE codigo_ine='42011';
UPDATE municipios SET nombre_search='salou' WHERE codigo_ine='42012';
UPDATE municipios SET nombre_search='tarragona' WHERE codigo_ine='42013';
UPDATE municipios SET nombre_search='tortosa' WHERE codigo_ine='42014';
UPDATE municipios SET nombre_search='valls' WHERE codigo_ine='42015';
UPDATE municipios SET nombre_search='vila-seca' WHERE codigo_ine='42016';
UPDATE municipios SET nombre_search='albarracin' WHERE codigo_ine='43001';
UPDATE municipios SET nombre_search='alcaniz' WHERE codigo_ine='43002';
UPDATE municipios SET nombre_search='beceite' WHERE codigo_ine='43003';
UPDATE municipios SET nombre_search='calaceite' WHERE codigo_ine='43004';
UPDATE municipios SET nombre_search='cretas' WHERE codigo_ine='43005';
UPDATE municipios SET nombre_search='molinos' WHERE codigo_ine='43006';
UPDATE municipios SET nombre_search='mora de rubielos' WHERE codigo_ine='43007';
UPDATE municipios SET nombre_search='penagolosa' WHERE codigo_ine='43008';
UPDATE municipios SET nombre_search='penarroya de tastavins' WHERE codigo_ine='43009';
UPDATE municipios SET nombre_search='puertomingalvo' WHERE codigo_ine='43010';
UPDATE municipios SET nombre_search='teruel' WHERE codigo_ine='43011';
UPDATE municipios SET nombre_search='valderrobres' WHERE codigo_ine='43012';
UPDATE municipios SET nombre_search='villarluengo' WHERE codigo_ine='43013';
UPDATE municipios SET nombre_search='consuegra' WHERE codigo_ine='44001';
UPDATE municipios SET nombre_search='illescas' WHERE codigo_ine='44002';
UPDATE municipios SET nombre_search='lagartera' WHERE codigo_ine='44003';
UPDATE municipios SET nombre_search='madridejos' WHERE codigo_ine='44004';
UPDATE municipios SET nombre_search='mora' WHERE codigo_ine='44005';
UPDATE municipios SET nombre_search='ocana' WHERE codigo_ine='44006';
UPDATE municipios SET nombre_search='orgaz' WHERE codigo_ine='44007';
UPDATE municipios SET nombre_search='oropesa' WHERE codigo_ine='44008';
UPDATE municipios SET nombre_search='quintanar de la orden' WHERE codigo_ine='44009';
UPDATE municipios SET nombre_search='talavera de la reina' WHERE codigo_ine='44010';
UPDATE municipios SET nombre_search='tembleque' WHERE codigo_ine='44011';
UPDATE municipios SET nombre_search='toledo' WHERE codigo_ine='44012';
UPDATE municipios SET nombre_search='urda' WHERE codigo_ine='44013';
UPDATE municipios SET nombre_search='alcoi/alcoy' WHERE codigo_ine='45001';
UPDATE municipios SET nombre_search='alzira' WHERE codigo_ine='45002';
UPDATE municipios SET nombre_search='burjassot' WHERE codigo_ine='45003';
UPDATE municipios SET nombre_search='denia' WHERE codigo_ine='45004';
UPDATE municipios SET nombre_search='el puig de santa maria' WHERE codigo_ine='45005';
UPDATE municipios SET nombre_search='gandia' WHERE codigo_ine='45006';
UPDATE municipios SET nombre_search='lliria' WHERE codigo_ine='45007';
UPDATE municipios SET nombre_search='mislata' WHERE codigo_ine='45008';
UPDATE municipios SET nombre_search='oliva' WHERE codigo_ine='45009';
UPDATE municipios SET nombre_search='ontinyent' WHERE codigo_ine='45010';
UPDATE municipios SET nombre_search='paterna' WHERE codigo_ine='45011';
UPDATE municipios SET nombre_search='requena' WHERE codigo_ine='45012';
UPDATE municipios SET nombre_search='sagunto/sagunt' WHERE codigo_ine='45013';
UPDATE municipios SET nombre_search='torrent' WHERE codigo_ine='45014';
UPDATE municipios SET nombre_search='valencia' WHERE codigo_ine='45015';
UPDATE municipios SET nombre_search='xabia/javea' WHERE codigo_ine='45016';
UPDATE municipios SET nombre_search='xativa' WHERE codigo_ine='45017';
UPDATE municipios SET nombre_search='cigales' WHERE codigo_ine='46001';
UPDATE municipios SET nombre_search='laguna de duero' WHERE codigo_ine='46002';
UPDATE municipios SET nombre_search='medina de rioseco' WHERE codigo_ine='46003';
UPDATE municipios SET nombre_search='medina del campo' WHERE codigo_ine='46004';
UPDATE municipios SET nombre_search='olmedo' WHERE codigo_ine='46005';
UPDATE municipios SET nombre_search='pesquera de duero' WHERE codigo_ine='46006';
UPDATE municipios SET nombre_search='penafiel' WHERE codigo_ine='46007';
UPDATE municipios SET nombre_search='simancas' WHERE codigo_ine='46008';
UPDATE municipios SET nombre_search='tordesillas' WHERE codigo_ine='46009';
UPDATE municipios SET nombre_search='valladolid' WHERE codigo_ine='46010';
UPDATE municipios SET nombre_search='balmaseda' WHERE codigo_ine='47001';
UPDATE municipios SET nombre_search='barakaldo' WHERE codigo_ine='47002';
UPDATE municipios SET nombre_search='bermeo' WHERE codigo_ine='47003';
UPDATE municipios SET nombre_search='bilbao' WHERE codigo_ine='47004';
UPDATE municipios SET nombre_search='ea' WHERE codigo_ine='47005';
UPDATE municipios SET nombre_search='elantxobe' WHERE codigo_ine='47006';
UPDATE municipios SET nombre_search='gernika-lumo' WHERE codigo_ine='47007';
UPDATE municipios SET nombre_search='getxo' WHERE codigo_ine='47008';
UPDATE municipios SET nombre_search='leioa' WHERE codigo_ine='47009';
UPDATE municipios SET nombre_search='lekeitio' WHERE codigo_ine='47010';
UPDATE municipios SET nombre_search='mundaka' WHERE codigo_ine='47011';
UPDATE municipios SET nombre_search='ondarroa' WHERE codigo_ine='47012';
UPDATE municipios SET nombre_search='alcanices' WHERE codigo_ine='48001';
UPDATE municipios SET nombre_search='benavente' WHERE codigo_ine='48002';
UPDATE municipios SET nombre_search='fermoselle' WHERE codigo_ine='48003';
UPDATE municipios SET nombre_search='sanabria' WHERE codigo_ine='48004';
UPDATE municipios SET nombre_search='toro' WHERE codigo_ine='48005';
UPDATE municipios SET nombre_search='villafafila' WHERE codigo_ine='48006';
UPDATE municipios SET nombre_search='villalpando' WHERE codigo_ine='48007';
UPDATE municipios SET nombre_search='zamora' WHERE codigo_ine='48008';
UPDATE municipios SET nombre_search='ainzon' WHERE codigo_ine='49001';
UPDATE municipios SET nombre_search='belchite' WHERE codigo_ine='49002';
UPDATE municipios SET nombre_search='borja' WHERE codigo_ine='49003';
UPDATE municipios SET nombre_search='calatayud' WHERE codigo_ine='49004';
UPDATE municipios SET nombre_search='caspe' WHERE codigo_ine='49005';
UPDATE municipios SET nombre_search='daroca' WHERE codigo_ine='49006';
UPDATE municipios SET nombre_search='ejea de los caballeros' WHERE codigo_ine='49007';
UPDATE municipios SET nombre_search='fuendetodos' WHERE codigo_ine='49008';
UPDATE municipios SET nombre_search='muel' WHERE codigo_ine='49009';
UPDATE municipios SET nombre_search='sos del rey catolico' WHERE codigo_ine='49010';
UPDATE municipios SET nombre_search='tarazona' WHERE codigo_ine='49011';
UPDATE municipios SET nombre_search='veruela' WHERE codigo_ine='49012';
UPDATE municipios SET nombre_search='zaragoza' WHERE codigo_ine='49013';
UPDATE municipios SET nombre_search='alegria-dulantzi' WHERE codigo_ine='50001';
UPDATE municipios SET nombre_search='amurrio' WHERE codigo_ine='50002';
UPDATE municipios SET nombre_search='areatza' WHERE codigo_ine='50003';
UPDATE municipios SET nombre_search='arraia-maeztu' WHERE codigo_ine='50004';
UPDATE municipios SET nombre_search='arrazua-ubarrundia' WHERE codigo_ine='50005';
UPDATE municipios SET nombre_search='artziniega' WHERE codigo_ine='50006';
UPDATE municipios SET nombre_search='asparrena' WHERE codigo_ine='50007';
UPDATE municipios SET nombre_search='ayala' WHERE codigo_ine='50008';
UPDATE municipios SET nombre_search='barrundia' WHERE codigo_ine='50009';
UPDATE municipios SET nombre_search='banos de ebro' WHERE codigo_ine='50010';
UPDATE municipios SET nombre_search='bernedo' WHERE codigo_ine='50011';
UPDATE municipios SET nombre_search='campezo/kanpezu' WHERE codigo_ine='50012';
UPDATE municipios SET nombre_search='elburgo/burgelu' WHERE codigo_ine='50013';
UPDATE municipios SET nombre_search='elciego' WHERE codigo_ine='50014';
UPDATE municipios SET nombre_search='erriberagoitia/ribera alta' WHERE codigo_ine='50015';
UPDATE municipios SET nombre_search='gasteiz/vitoria' WHERE codigo_ine='50016';
UPDATE municipios SET nombre_search='iruraiz-gauna' WHERE codigo_ine='50017';
UPDATE municipios SET nombre_search='iruna de oca' WHERE codigo_ine='50018';
UPDATE municipios SET nombre_search='kripan' WHERE codigo_ine='50019';
UPDATE municipios SET nombre_search='kuartango' WHERE codigo_ine='50020';
UPDATE municipios SET nombre_search='labastida' WHERE codigo_ine='50021';
UPDATE municipios SET nombre_search='lagran' WHERE codigo_ine='50022';
UPDATE municipios SET nombre_search='laguardia' WHERE codigo_ine='50023';
UPDATE municipios SET nombre_search='lanciego' WHERE codigo_ine='50024';
UPDATE municipios SET nombre_search='lantaron' WHERE codigo_ine='50025';
UPDATE municipios SET nombre_search='lapuebla de labarca' WHERE codigo_ine='50026';
UPDATE municipios SET nombre_search='llodio' WHERE codigo_ine='50027';
UPDATE municipios SET nombre_search='moreda de alava' WHERE codigo_ine='50028';
UPDATE municipios SET nombre_search='navaridas' WHERE codigo_ine='50029';
UPDATE municipios SET nombre_search='okondo' WHERE codigo_ine='50030';
UPDATE municipios SET nombre_search='oyon-oion' WHERE codigo_ine='50031';
UPDATE municipios SET nombre_search='penacerrada' WHERE codigo_ine='50032';
UPDATE municipios SET nombre_search='ribera alta' WHERE codigo_ine='50033';
UPDATE municipios SET nombre_search='salinas de anana' WHERE codigo_ine='50034';
UPDATE municipios SET nombre_search='salvatierra/agurain' WHERE codigo_ine='50035';
UPDATE municipios SET nombre_search='urkabustaiz' WHERE codigo_ine='50036';
UPDATE municipios SET nombre_search='valdegovia/gaubea' WHERE codigo_ine='50037';
UPDATE municipios SET nombre_search='villabuena de alava' WHERE codigo_ine='50038';
UPDATE municipios SET nombre_search='vitoria-gasteiz' WHERE codigo_ine='50039';
UPDATE municipios SET nombre_search='yecora' WHERE codigo_ine='50040';
UPDATE municipios SET nombre_search='zigoitia' WHERE codigo_ine='50041';
UPDATE municipios SET nombre_search='zuia' WHERE codigo_ine='50042';
UPDATE municipios SET nombre_search='arenas de san pedro' WHERE codigo_ine='51001';
UPDATE municipios SET nombre_search='arevalo' WHERE codigo_ine='51002';
UPDATE municipios SET nombre_search='barco de avila (el)' WHERE codigo_ine='51003';
UPDATE municipios SET nombre_search='bohoyo' WHERE codigo_ine='51004';
UPDATE municipios SET nombre_search='candeleda' WHERE codigo_ine='51005';
UPDATE municipios SET nombre_search='cebreros' WHERE codigo_ine='51006';
UPDATE municipios SET nombre_search='cepeda la mora' WHERE codigo_ine='51007';
UPDATE municipios SET nombre_search='el arenal' WHERE codigo_ine='51008';
UPDATE municipios SET nombre_search='el barco de avila' WHERE codigo_ine='51009';
UPDATE municipios SET nombre_search='el espinar' WHERE codigo_ine='51010';
UPDATE municipios SET nombre_search='el tiemblo' WHERE codigo_ine='51011';
UPDATE municipios SET nombre_search='fontiveros' WHERE codigo_ine='51012';
UPDATE municipios SET nombre_search='guisando' WHERE codigo_ine='51013';
UPDATE municipios SET nombre_search='hoyos del espino' WHERE codigo_ine='51014';
UPDATE municipios SET nombre_search='la adrada' WHERE codigo_ine='51015';
UPDATE municipios SET nombre_search='madrigal de las altas torres' WHERE codigo_ine='51016';
UPDATE municipios SET nombre_search='navarredonda de gredos' WHERE codigo_ine='51017';
UPDATE municipios SET nombre_search='navarrevisca' WHERE codigo_ine='51018';
UPDATE municipios SET nombre_search='pedro bernardo' WHERE codigo_ine='51019';
UPDATE municipios SET nombre_search='peguerinos' WHERE codigo_ine='51020';
UPDATE municipios SET nombre_search='piedrahita' WHERE codigo_ine='51021';
UPDATE municipios SET nombre_search='piedralaves' WHERE codigo_ine='51022';
UPDATE municipios SET nombre_search='san esteban del valle' WHERE codigo_ine='51023';
UPDATE municipios SET nombre_search='sotillo de la adrada' WHERE codigo_ine='51024';
UPDATE municipios SET nombre_search='avila' WHERE codigo_ine='51025';