-- Enriquecimiento festivales SEMrush
-- Generado: 2026-06-07T00:42:27.773556
-- Municipios: 49

UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 52.7) WHERE codigo_ine='01059' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('01059', 'festival', 'Azkena Rock Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 50.3) WHERE codigo_ine='02083' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('02083', 'festival', 'Festival Viña Rock', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('02083', 'festival', 'Viña Rock Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 45.3) WHERE codigo_ine='03003' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('03003', 'festival', 'Bravas Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 57.6) WHERE codigo_ine='03031' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('03031', 'festival', 'Zevra Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('03031', 'festival', 'Reggaeton Beach Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('03031', 'festival', 'Low Cost Benidorm Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('03031', 'festival', 'Low Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('03031', 'festival', 'Festival Benidorm', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 43.0) WHERE codigo_ine='03065' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('03065', 'festival', 'Oasis Festival Elche', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 43.0) WHERE codigo_ine='04036' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('04036', 'festival', 'Dreambeach Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 47.8) WHERE codigo_ine='06083' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('06083', 'festival', 'Festival De Merida', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('06083', 'festival', 'Festival Teatro Merida', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('06083', 'festival', 'Festival Teatro De Merida', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('06083', 'festival', 'Festival Teatro Mérida', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 54.0) WHERE codigo_ine='07015' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('07015', 'festival', 'Mallorca Live Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 45.3) WHERE codigo_ine='07026' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('07026', 'festival', 'Ibiza Rocks Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 49.1) WHERE codigo_ine='08003' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08003', 'festival', 'Festival B', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08003', 'festival', 'Primavera Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08003', 'festival', 'Cruilla Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08003', 'festival', 'Festival Cruilla', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08003', 'festival', 'Barcelona Festival Primavera', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 44.2) WHERE codigo_ine='08015' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08015', 'festival', 'Itaca Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08015', 'festival', 'Festival Itaca', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 46.7) WHERE codigo_ine='08035' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08035', 'festival', 'Canet Rock Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 49.1) WHERE codigo_ine='08270' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08270', 'festival', 'Sitges Film Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08270', 'festival', 'Sitges Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08270', 'festival', 'Festival De Sitges', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08270', 'festival', 'Festival Sitges', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08270', 'festival', 'Sitges International Film Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 47.8) WHERE codigo_ine='08279' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08279', 'festival', 'Mira Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 51.5) WHERE codigo_ine='08305' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08305', 'festival', 'Vida Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('08305', 'festival', 'Festival Vida', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 43.0) WHERE codigo_ine='09017' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('09017', 'festival', 'Festival Aranda De Duero', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 55.2) WHERE codigo_ine='10008' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('10008', 'festival', 'Festival De Teatro Clásico De Alcántara', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 41.4) WHERE codigo_ine='10901' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('10901', 'festival', 'Festival Nacional De Los Cerezos En Flor', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 49.1) WHERE codigo_ine='11020' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('11020', 'festival', 'Tio Pepe Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('11020', 'festival', 'Festival Tio Pepe', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('11020', 'festival', 'Tío Pepe Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 51.5) WHERE codigo_ine='12027' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('12027', 'festival', 'Festival Benicassim', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('12027', 'festival', 'Festival Fib', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('12027', 'festival', 'Fib Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('12027', 'festival', 'San San Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('12027', 'festival', 'Fib Benicàssim Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 49.1) WHERE codigo_ine='12034' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('12034', 'festival', 'Festival Arenal Sound', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('12034', 'festival', 'Arenal Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 50.3) WHERE codigo_ine='15062' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('15062', 'festival', 'Ortigueira Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('15062', 'festival', 'Festival De Ortigueira', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('15062', 'festival', 'Festival Ortigueira', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('15062', 'festival', 'Festival Celta Ortigueira', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 45.3) WHERE codigo_ine='16009' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('16009', 'festival', 'Brisa Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 44.2) WHERE codigo_ine='17095' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('17095', 'festival', 'Idilic Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 50.3) WHERE codigo_ine='17126' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('17126', 'festival', 'Cap Roig Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('17126', 'festival', 'Festival Cap Roig', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('17126', 'festival', 'Festival De Cap Roig', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 51.5) WHERE codigo_ine='17152' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('17152', 'festival', 'Mediterranea Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('17152', 'festival', 'Mediterranea Festival Roses', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 43.0) WHERE codigo_ine='17155' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('17155', 'festival', 'Festival Porta Ferrada', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 49.1) WHERE codigo_ine='20069' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('20069', 'festival', 'Festival De Cine De San Sebastian', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('20069', 'festival', 'Festival De San Sebastian', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('20069', 'festival', 'Festival De Donosti', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('20069', 'festival', 'Festival San Sebastián', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('20069', 'festival', 'Festival De Cine De San Sebastián', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 45.3) WHERE codigo_ine='22059' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('22059', 'festival', 'Festival Pirineos Sur', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 54.0) WHERE codigo_ine='22902' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('22902', 'festival', 'Monegros Desert Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('22902', 'festival', 'Monegros Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 49.1) WHERE codigo_ine='29014' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('29014', 'festival', 'Festival De La Luz', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('29014', 'festival', 'Mad Cool Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('29014', 'festival', 'Festival Rio Babel', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('29014', 'festival', 'Look Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('29014', 'festival', 'Festival Mad Cool', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 52.7) WHERE codigo_ine='29067' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('29067', 'festival', 'Starlite Festival Auditorio Marbella', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('29067', 'festival', 'Starlite Festival Marbella', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 46.7) WHERE codigo_ine='29901' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('29901', 'festival', 'Weekend Beach Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 44.2) WHERE codigo_ine='30021' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('30021', 'festival', 'Rock Imperium Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 55.2) WHERE codigo_ine='30027' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('30027', 'festival', 'Duro Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 49.1) WHERE codigo_ine='32016' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('32016', 'festival', 'Festival De Malaga', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('32016', 'festival', 'Festival De Cine De Malaga', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('32016', 'festival', 'Festival Cine Español Malaga', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('32016', 'festival', 'Festival Cine Malaga', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('32016', 'festival', 'Festival Málaga', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 46.7) WHERE codigo_ine='33024' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('33024', 'festival', 'Festival Aereo Gijon', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('33024', 'festival', 'Caudal Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 44.2) WHERE codigo_ine='33045' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('33045', 'festival', 'Aquasella Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 41.4) WHERE codigo_ine='36034' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('36034', 'festival', 'Reggaeton Beach Festival Nigran', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 45.3) WHERE codigo_ine='36038' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('36038', 'festival', 'Morriña Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('36038', 'festival', 'Big Sound Festival Pontevedra', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 41.4) WHERE codigo_ine='37011' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('37011', 'festival', 'Negrita Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 41.4) WHERE codigo_ine='38012' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('38012', 'festival', 'Reggaeton Beach Festival Tenerife', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 43.0) WHERE codigo_ine='40018' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('40018', 'festival', 'Iconica Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('40018', 'festival', 'Festival Sevilla', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 41.4) WHERE codigo_ine='40172' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('40172', 'festival', 'Huercasa Country Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 54.0) WHERE codigo_ine='43137' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('43137', 'festival', 'Pirata Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('43137', 'festival', 'Pirata Beach Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('43137', 'festival', 'Som Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('43137', 'festival', 'Festival Village Salou', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('43137', 'festival', 'Festival Salou', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 49.1) WHERE codigo_ine='44012' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('44012', 'festival', 'Toledo Beat Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 51.5) WHERE codigo_ine='45015' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('45015', 'festival', 'Festival De Les Arts', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('45015', 'festival', 'Festival Valencia', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 60.0) WHERE codigo_ine='46107' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('46107', 'festival', 'Medusa Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
UPDATE puntuaciones SET puntuacion=MAX(puntuacion, 51.5) WHERE codigo_ine='47004' AND categoria='festivales';
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('47004', 'festival', 'Bbk Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('47004', 'festival', 'Bbk Live Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
INSERT INTO entidades (codigo_ine, tipo, nombre, fuente) VALUES ('47004', 'festival', 'Bilbao Bbk Live Festival', 'semrush') ON CONFLICT(codigo_ine, tipo, nombre) DO NOTHING;
