-- Gastronomía Murcia — generado desde guías gastronómicas Excel
-- Provincias: Murcia
-- Municipios con datos: 63

-- 1. Reset
UPDATE puntuaciones SET puntuacion=0 WHERE categoria='gastronomia'
  AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE provincia IN ('Murcia'));

-- 2. Limpiar entidades automáticas OSM/wikidata
DELETE FROM entidades WHERE tipo IN ('gastronomia','producto')
  AND fuente IN ('wikidata','OSM')
  AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE provincia IN ('Murcia'));

-- 3. Default 12 para todos
UPDATE puntuaciones SET puntuacion=12 WHERE categoria='gastronomia'
  AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE provincia IN ('Murcia'));

-- 4. Scores individuales (62 municipios con datos)
UPDATE puntuaciones SET puntuacion=88 WHERE codigo_ine IN ('30030', '31015') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=80 WHERE codigo_ine IN ('30016', '31005') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=72 WHERE codigo_ine IN ('30013', '31003') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=64 WHERE codigo_ine IN ('30003', '30022', '31009', '31019') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=60 WHERE codigo_ine IN ('30015', '30024', '30036', '30043', '31004', '31011', '31018') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=56 WHERE codigo_ine='30012' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=52 WHERE codigo_ine IN ('30902', '30026', '30035', '31012', '31016') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=48 WHERE codigo_ine IN ('30017', '30028', '31006', '31013') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=44 WHERE codigo_ine IN ('30019', '31007') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=40 WHERE codigo_ine IN ('30027', '30029', '30039', '31014') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=36 WHERE codigo_ine='30008' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=32 WHERE codigo_ine IN ('30005', '30009', '30034', '30037', '30041', '31002', '31010', '31017') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=28 WHERE codigo_ine IN ('30002', '30021', '30033', '30901', '31001') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=24 WHERE codigo_ine IN ('30007', '30011', '30018', '30023', '30031', '30038', '30042') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=20 WHERE codigo_ine IN ('30010', '30006', '30020', '30025', '30032', '30040', '31008') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=16 WHERE codigo_ine='30014' AND categoria='gastronomia';

-- 5. Entidades gastronómicas
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30010','gastronomia','Cocina rural','Cocina rural.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30002','gastronomia','Arroz con conejo, paparajotes, frutas de la Vega Alta','Arroz con conejo, paparajotes, frutas de la Vega Alta. Tradición de norias históricas de la huerta.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30003','gastronomia','Cuajadera de pescado, Gamba roja, embutidos marineros','Cuajadera de pescado, Gamba roja, embutidos marineros. Producto marino premium de la costa sur.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30005','gastronomia','Pastel de carne murciano, zarangollo, embutidos','Pastel de carne murciano, zarangollo, embutidos. Tradición huertana e industria alimentaria.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30902','gastronomia','Caldero del Mar Menor, pescados de la laguna, michirones','Caldero del Mar Menor, pescados de la laguna, michirones. Especialidades marineras icónicas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30006','gastronomia','Gachasmigas, Mantellina (licor dulce), carnes a la brasa','Gachasmigas, Mantellina (licor dulce), carnes a la brasa. Cocina medieval bajo la sierra.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30007','gastronomia','Zarangollo murciano, arroces de verduras, bizcochos','Zarangollo murciano, arroces de verduras, bizcochos. Gastronomía tradicional de la Vega Media.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30008','gastronomia','Arroz con costillejas, Jallullo, Chato Murciano','Arroz con costillejas, Jallullo, Chato Murciano. Especialistas en cerdo autóctono en Sierra Espuña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30009','gastronomia','Guiso de trigo, arroz con conejo y caracoles, paparajotes','Guiso de trigo, arroz con conejo y caracoles, paparajotes. Cocina vinculada a su histórico Balneario.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30011','gastronomia','Arroz con verduras de la vega, migas, frutales','Arroz con verduras de la vega, migas, frutales. Cocina tradicional de herencia árabe.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30012','gastronomia','Vino de la D','Vino de la D.O. Bullas, ajocandil, torrijas, cordero asado. Capital vitivinícola de interior.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30013','gastronomia','Arroz de Calasparra (D','Arroz de Calasparra (D.O.P.), cordero segureño. Primer arroz del mundo con D.O.P.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30014','gastronomia','Quesos de cabra artesanales, migas rústicas, potajes','Quesos de cabra artesanales, migas rústicas, potajes. Tradición ganadera y quesera caprina.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30015','gastronomia','Tartera de Caravaca, Yemas de Caravaca, alfajor','Tartera de Caravaca, Yemas de Caravaca, alfajor. Dulces conventuales y cocina de Año Jubilar.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30016','gastronomia','Caldero cartagenero, Café Asiático, michirones, salazones','Caldero cartagenero, Café Asiático, michirones, salazones. Restaurante Magoga (1* Michelin) y puerto histórico.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30017','gastronomia','Arroz de San Antón, Chamorro, empedrao, embutidos','Arroz de San Antón, Chamorro, empedrao, embutidos. Ruta de la tapa y cocina tradicional del Noroeste.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30018','gastronomia','Olla gitana, zarangollo, conservas vegetales','Olla gitana, zarangollo, conservas vegetales. Cocina ligada a la huerta y la industria conservera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30019','gastronomia','Melocotón de Cieza (I','Melocotón de Cieza (I.G.P.), caracoles chupaeros, gachamiga. Referente mundial en fruta de hueso; floración.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30020','gastronomia','Trigo picado, tortas de pascua, asados a la leña','Trigo picado, tortas de pascua, asados a la leña. Cocina de secano y turismo termal.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30021','gastronomia','Migas con tropezones, embutidos de cerdo, legumbres','Migas con tropezones, embutidos de cerdo, legumbres. Gastronomía ganadera del Campo de Cartagena.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30022','gastronomia','Vino de la D','Vino de la D.O.P. Jumilla, gazpachos jumillanos, mortirigüelo. Potencia vinícola y cocina recia de campo.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30023','gastronomia','Pitanzas (pan tradicional), zarangollo, guisados','Pitanzas (pan tradicional), zarangollo, guisados. Tradición panadera artesanal histórica.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30024','gastronomia','Crespillos lorquinos, tortada de Lorca, embutidos, jarote','Crespillos lorquinos, tortada de Lorca, embutidos, jarote. Cocina monumental y asados selectos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30025','gastronomia','Arroz con verduras, magra con tomate, dulces tradicionales','Arroz con verduras, magra con tomate, dulces tradicionales. Cocina clásica de la Vega Media.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30026','gastronomia','Atún rojo de almadraba, cazuela de pescado, moragas','Atún rojo de almadraba, cazuela de pescado, moragas. Tradición pesquera ancestral de bahía y salazones.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30027','gastronomia','Pisto murciano, michirones, repostería artesana','Pisto murciano, michirones, repostería artesana. Capital conservera y cocina de mercado.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30028','gastronomia','Mazapán de Moratalla, cordero segureño, setas, licores','Mazapán de Moratalla, cordero segureño, setas, licores. Alta repostería navideña y carnes de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30029','gastronomia','Arroz con habitas, cazuela de San Juan, talvinas','Arroz con habitas, cazuela de San Juan, talvinas. Riqueza culinaria de secano y regadío.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30030','gastronomia','Pastel de carne, zarangollo, marinera, paparajotes','Pastel de carne, zarangollo, marinera, paparajotes. Cabaña Buenavista (2* Michelin), Huerta de Europa.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30031','gastronomia','Bizcochos de Ojós, arroz con conejo, hortalizas selectas','Bizcochos de Ojós, arroz con conejo, hortalizas selectas. Repostería tradicional morisca del Valle de Ricote.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30032','gastronomia','Zarangollo, carnes asadas a la brasa, dulces de almendra','Zarangollo, carnes asadas a la brasa, dulces de almendra. Cocina de montaña de interior.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30033','gastronomia','Migas de harina con tropezones, cordero asado, embutidos','Migas de harina con tropezones, cordero asado, embutidos. Cocina fronteriza con influencia andaluza.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30034','gastronomia','Cordero al horno de leña, vino de Ricote, olivas mollar','Cordero al horno de leña, vino de Ricote, olivas mollar. Herencia árabe en el Valle de Ricote.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30035','gastronomia','Pastel de Cierva, caldero, langostinos del Mar Menor','Pastel de Cierva, caldero, langostinos del Mar Menor. Cuna del pastel dulce-salado icónico.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30036','gastronomia','Pescado a la sal, huevas de mújol, gamba del Mar Menor','Pescado a la sal, huevas de mújol, gamba del Mar Menor. Templo de los salazones mediterráneos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30901','gastronomia','Platos e infusiones al limón, zarangollo, guisos vegetales','Platos e infusiones al limón, zarangollo, guisos vegetales. Capital del limón; integración de cítricos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30037','gastronomia','Melón de Torre-Pacheco, michirones, guisos de campo','Melón de Torre-Pacheco, michirones, guisos de campo. Despensa hortícola e invernaderos de alta gama.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30038','gastronomia','Olla gitana, ensalada murciana, paparajotes','Olla gitana, ensalada murciana, paparajotes. Cocina huertana clásica metropolitana.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30039','gastronomia','Torta de pimentón, sémola, Pimentón de Murcia (D','Torta de pimentón, sémola, Pimentón de Murcia (D.O.). Cultivo y molienda del pimentón de bola artesanal.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30040','gastronomia','Guisos de verduras finas, migas con fruta, dulces de leña','Guisos de verduras finas, migas con fruta, dulces de leña. Entorno protegido del río Segura.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30041','gastronomia','Pescaito frito, michirones, cocina de los mineros','Pescaito frito, michirones, cocina de los mineros. Gastronomía de raíces mineras de la costa.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30042','gastronomia','Cocina de ribera','Cocina de ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('30043','gastronomia','Vino de la D','Vino de la D.O. Yecla, gazpachos yeclanos, Libricos. Influencia manchega y repostería fina de obrador.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31001','gastronomia','Arroz con conejo, paparajotes, frutas de la Vega Alta','Arroz con conejo, paparajotes, frutas de la Vega Alta. Tradición de norias históricas de la huerta.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31002','gastronomia','Guiso de trigo, arroz con conejo y caracoles, paparajotes','Guiso de trigo, arroz con conejo y caracoles, paparajotes. Cocina vinculada a su histórico Balneario.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31003','gastronomia','Arroz de Calasparra (D','Arroz de Calasparra (D.O.P.), cordero segureño. Primer arroz del mundo con D.O.P.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31004','gastronomia','Tartera de Caravaca, Yemas de Caravaca, alfajor','Tartera de Caravaca, Yemas de Caravaca, alfajor. Dulces conventuales y cocina de Año Jubilar.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31005','gastronomia','Caldero cartagenero, Café Asiático, michirones, salazones','Caldero cartagenero, Café Asiático, michirones, salazones. Restaurante Magoga (1* Michelin) y puerto histórico.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31006','gastronomia','Arroz de San Antón, Chamorro, empedrao, embutidos','Arroz de San Antón, Chamorro, empedrao, embutidos. Ruta de la tapa y cocina tradicional del Noroeste.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31007','gastronomia','Melocotón de Cieza (I','Melocotón de Cieza (I.G.P.), caracoles chupaeros, gachamiga. Referente mundial en fruta de hueso; floración.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31008','gastronomia','Trigo picado, tortas de pascua, asados a la leña','Trigo picado, tortas de pascua, asados a la leña. Cocina de secano y turismo termal.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31009','gastronomia','Vino de la D','Vino de la D.O.P. Jumilla, gazpachos jumillanos, mortirigüelo. Potencia vinícola y cocina recia de campo.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31010','gastronomia','Pescaito frito, michirones, cocina de los mineros','Pescaito frito, michirones, cocina de los mineros. Gastronomía de raíces mineras de la costa.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31011','gastronomia','Crespillos lorquinos, tortada de Lorca, embutidos, jarote','Crespillos lorquinos, tortada de Lorca, embutidos, jarote. Cocina monumental y asados selectos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31012','gastronomia','Atún rojo de almadraba, cazuela de pescado, moragas','Atún rojo de almadraba, cazuela de pescado, moragas. Tradición pesquera ancestral de bahía y salazones.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31013','gastronomia','Mazapán de Moratalla, cordero segureño, setas, licores','Mazapán de Moratalla, cordero segureño, setas, licores. Alta repostería navideña y carnes de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31014','gastronomia','Arroz con habitas, cazuela de San Juan, talvinas','Arroz con habitas, cazuela de San Juan, talvinas. Riqueza culinaria de secano y regadío.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31015','gastronomia','Pastel de carne, zarangollo, marinera, paparajotes','Pastel de carne, zarangollo, marinera, paparajotes. Cabaña Buenavista (2* Michelin), Huerta de Europa.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31016','gastronomia','Pastel de Cierva, caldero, langostinos del Mar Menor','Pastel de Cierva, caldero, langostinos del Mar Menor. Cuna del pastel dulce-salado icónico.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31017','gastronomia','Melón de Torre-Pacheco, michirones, guisos de campo','Melón de Torre-Pacheco, michirones, guisos de campo. Despensa hortícola e invernaderos de alta gama.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31018','gastronomia','Vino de la D','Vino de la D.O. Yecla, gazpachos yeclanos, Libricos. Influencia manchega y repostería fina de obrador.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31019','gastronomia','Cuajadera de pescado, Gamba roja, embutidos marineros','Cuajadera de pescado, Gamba roja, embutidos marineros. Producto marino premium de la costa sur.','excel_curado',date('now'));