-- Gastronomía Navarra — generado desde guías gastronómicas Excel
-- Provincias: Navarra
-- Municipios con datos: 198

-- 1. Reset
UPDATE puntuaciones SET puntuacion=0 WHERE categoria='gastronomia'
  AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE provincia IN ('Navarra'));

-- 2. Limpiar entidades automáticas OSM/wikidata
DELETE FROM entidades WHERE tipo IN ('gastronomia','producto')
  AND fuente IN ('wikidata','OSM')
  AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE provincia IN ('Navarra'));

-- 3. Default 12 para todos
UPDATE puntuaciones SET puntuacion=12 WHERE categoria='gastronomia'
  AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE provincia IN ('Navarra'));

-- 4. Scores individuales (198 municipios con datos)
UPDATE puntuaciones SET puntuacion=88 WHERE codigo_ine='33014' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=84 WHERE codigo_ine IN ('31232', '33019') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine='33013' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=72 WHERE codigo_ine='33007' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=68 WHERE codigo_ine='31050' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=64 WHERE codigo_ine='31227' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=60 WHERE codigo_ine='31077' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=56 WHERE codigo_ine IN ('31235', '31251', '33020') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=52 WHERE codigo_ine='31157' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=48 WHERE codigo_ine IN ('31165', '33015') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=44 WHERE codigo_ine IN ('31042', '31068', '31072', '31215', '31217') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=40 WHERE codigo_ine IN ('31254', '31038', '31078', '31104', '31105', '31149', '31176', '31223', '31236', '33004') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=36 WHERE codigo_ine IN ('31029', '31032', '31036', '31901', '31065', '31070', '31107', '31142', '33009', '31152', '31163', '31169', '31173', '31208', '31224', '31249', '31264') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=32 WHERE codigo_ine IN ('31062', '33003', '31023', '31033', '31905', '31902', '31903', '31057', '33005', '31064', '31066', '31067', '31084', '31098', '31101', '31106', '31108', '31109', '31904', '31135', '31159', '31161', '31164', '31167', '31171', '31183', '31195', '31200', '31226', '31255', '31257', '33010', '33011') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=28 WHERE codigo_ine IN ('33001', '31020', '31027', '31049', '31054', '31055', '31069', '31080', '31081', '31085', '31091', '31092', '31115', '31117', '31125', '31126', '31129', '31131', '31134', '31136', '31144', '31145', '31154', '31155', '31168', '31177', '31178', '31179', '31180', '31205', '31207', '31220', '31228', '31231', '31233', '31240', '31243', '31246', '31261', '31263') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=24 WHERE codigo_ine IN ('31022', '31024', '31026', '31030', '31031', '31037', '31039', '31040', '31047', '31048', '31137', '31051', '31052', '31253', '31056', '31075', '31079', '31083', '31087', '31090', '31096', '31099', '31100', '31102', '31114', '31116', '31118', '31120', '31121', '31124', '31127', '31130', '31132', '31139', '31140', '31141', '31143', '31147', '31148', '31156', '31160', '31162', '31166', '31174', '31175', '31182', '31184', '31186', '31187', '31192', '31196', '31199', '31203', '31209', '31212', '31213', '31219', '31225', '31229', '31230', '31234', '31237', '31238', '31241', '31242', '31262', '31073', '31265') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=20 WHERE codigo_ine IN ('31035', '31043', '31046', '31071', '31103', '31146', '31151', '31170', '31190', '31197', '31204') AND categoria='gastronomia';

-- 5. Entidades gastronómicas
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31254','gastronomia','Verduras, conservas','Verduras, conservas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31062','gastronomia','Verduras de Ribera','Verduras de Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33001','gastronomia','Cocina de monte, productos lácteos','Cocina de monte, productos lácteos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33003','gastronomia','Cocina de la Merindad, asados','Cocina de la Merindad, asados.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31020','gastronomia','Cocina atlántica, carnes de pasto','Cocina atlántica, carnes de pasto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31022','gastronomia','Productos tradicionales','Productos tradicionales.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31023','gastronomia','Cocina de cercanía, huerta','Cocina de cercanía, huerta.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31024','gastronomia','Productos atlánticos, lácteos','Productos atlánticos, lácteos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31026','gastronomia','Cocina de ribera y sierra','Cocina de ribera y sierra.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31027','gastronomia','Quesos de oveja, embutidos','Quesos de oveja, embutidos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31029','gastronomia','Vinos, legumbres, repostería','Vinos, legumbres, repostería.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31030','gastronomia','Cocina tradicional, vinos','Cocina tradicional, vinos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31031','gastronomia','Productos lácteos, carnes','Productos lácteos, carnes.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31032','gastronomia','Verduras, conservas, productos de Ribera','Verduras, conservas, productos de Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31033','gastronomia','Potajes de legumbres, papas con mojo','Potajes de legumbres, papas con mojo. Agricultura verde tradicional del norte de Lanzarote.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31035','gastronomia','Productos de campo','Productos de campo.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31036','gastronomia','Aceite de oliva virgen extra, asados','Aceite de oliva virgen extra, asados.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31037','gastronomia','Productos de la zona de Sakana','Productos de la zona de Sakana.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31038','gastronomia','Vinos, cordero al chilindrón','Vinos, cordero al chilindrón.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31039','gastronomia','Cocina de la Zona Media','Cocina de la Zona Media.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31040','gastronomia','Cocina rural, productos locales','Cocina rural, productos locales.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31042','gastronomia','Verduras de la Ribera, conservas de calidad','Verduras de la Ribera, conservas de calidad.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31043','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31901','gastronomia','Cocina moderna, pinchos','Cocina moderna, pinchos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31046','gastronomia','Cocina de secano','Cocina de secano.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31047','gastronomia','Cocina de viñedo, vinos','Cocina de viñedo, vinos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31048','gastronomia','Cocina de Ribera','Cocina de Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31049','gastronomia','Quesos, productos lácteos','Quesos, productos lácteos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31050','gastronomia','Queso Idiazábal, carnes de pasto, postres','Queso Idiazábal, carnes de pasto, postres.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31137','gastronomia','Cocina de montaña','Cocina de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31051','gastronomia','Cocina de la Zona Media','Cocina de la Zona Media.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31052','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31905','gastronomia','Cocina de cercanía','Cocina de cercanía.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31902','gastronomia','Cocina metropolitana','Cocina metropolitana.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31903','gastronomia','Cocina urbana, pinchos','Cocina urbana, pinchos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31054','gastronomia','Productos de valle, caza','Productos de valle, caza.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31055','gastronomia','Agua y productos de montaña','Agua y productos de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31253','gastronomia','Cocina de valle','Cocina de valle.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31056','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31057','gastronomia','Verduras de Ribera','Verduras de Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33005','gastronomia','Carnes, caza, setas de montaña','Carnes, caza, setas de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31064','gastronomia','Verduras, conservas','Verduras, conservas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31065','gastronomia','Cocina de la vega, vinos','Cocina de la vega, vinos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31066','gastronomia','Conservas, hortalizas','Conservas, hortalizas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31067','gastronomia','Vinos, productos de Ribera','Vinos, productos de Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31068','gastronomia','Verduras, conservas, aceite','Verduras, conservas, aceite.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31069','gastronomia','Cocina de la Merindad','Cocina de la Merindad.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31070','gastronomia','Cocina de paso, asados','Cocina de paso, asados.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31071','gastronomia','Cocina rural','Cocina rural.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31072','gastronomia','Aceite de oliva, verduras, vinos','Aceite de oliva, verduras, vinos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31075','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31077','gastronomia','Verduras de la Ribera, conservas','Verduras de la Ribera, conservas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31078','gastronomia','Verduras, aceite de oliva','Verduras, aceite de oliva.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31079','gastronomia','Cocina rural','Cocina rural.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31080','gastronomia','Vinos, productos de la tierra','Vinos, productos de la tierra.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31081','gastronomia','Cocina pirenaica','Cocina pirenaica.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31083','gastronomia','Productos de montaña','Productos de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31084','gastronomia','Quesos, embutidos','Quesos, embutidos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31085','gastronomia','Cocina de valle','Cocina de valle.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31087','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31090','gastronomia','Cocina de montaña','Cocina de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31091','gastronomia','Productos de Sakana','Productos de Sakana.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31092','gastronomia','Carnes de caza, setas','Carnes de caza, setas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31096','gastronomia','Cocina de sierra','Cocina de sierra.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33007','gastronomia','Trufa, vinos, asados','Trufa, vinos, asados.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31098','gastronomia','Carnes, cocina de montaña','Carnes, cocina de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31099','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31100','gastronomia','Cocina de monte','Cocina de monte.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31101','gastronomia','Cocina de cercanía','Cocina de cercanía.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31102','gastronomia','Cocina de montaña','Cocina de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31103','gastronomia','Cocina rural','Cocina rural.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31104','gastronomia','Cebolla de Falces, asados','Cebolla de Falces, asados.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31105','gastronomia','Verduras, repostería conventual','Verduras, repostería conventual.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31106','gastronomia','Verduras de Ribera','Verduras de Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31107','gastronomia','Verduras, conservas','Verduras, conservas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31108','gastronomia','Verduras de Ribera','Verduras de Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31109','gastronomia','Cocina de cercanía','Cocina de cercanía.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31114','gastronomia','Cocina de la Zona Media','Cocina de la Zona Media.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31115','gastronomia','Cocina de montaña, setas','Cocina de montaña, setas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31116','gastronomia','Cocina rural','Cocina rural.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31117','gastronomia','Cocina atlántica, carnes','Cocina atlántica, carnes.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31118','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31120','gastronomia','Cocina de valle','Cocina de valle.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31121','gastronomia','Cocina rural','Cocina rural.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31124','gastronomia','Cocina de la Merindad','Cocina de la Merindad.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31125','gastronomia','Productos de monte','Productos de monte.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31126','gastronomia','Carnes y lácteos','Carnes y lácteos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31127','gastronomia','Productos de Sakana','Productos de Sakana.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31904','gastronomia','Carnes, cocina de montaña','Carnes, cocina de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31129','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31130','gastronomia','Productos de montaña','Productos de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31131','gastronomia','Cocina de valle','Cocina de valle.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31132','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31134','gastronomia','Cocina de montaña','Cocina de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31135','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31136','gastronomia','Cocina de cercanía','Cocina de cercanía.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31139','gastronomia','Cocina de monte','Cocina de monte.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31140','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31141','gastronomia','Cocina de sierra','Cocina de sierra.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31142','gastronomia','Vinos, productos de Ribera','Vinos, productos de Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31143','gastronomia','Cocina de monte','Cocina de monte.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31144','gastronomia','Carnes, lácteos','Carnes, lácteos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31145','gastronomia','Cocina de Ribera','Cocina de Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31146','gastronomia','Cocina rural','Cocina rural.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31147','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31148','gastronomia','Cocina de valle','Cocina de valle.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31149','gastronomia','Carnes de pasto, quesos','Carnes de pasto, quesos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33009','gastronomia','Carnes, cocina de montaña','Carnes, cocina de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31151','gastronomia','Cocina rural','Cocina rural.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31152','gastronomia','Vinos, legumbres','Vinos, legumbres.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31154','gastronomia','Cocina de monte','Cocina de monte.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31155','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31156','gastronomia','Cocina de valle','Cocina de valle.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31157','gastronomia','Piquillo de Lodosa (D','Piquillo de Lodosa (D.O.), conservas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31159','gastronomia','Repostería, cocina de sierra','Repostería, cocina de sierra.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31160','gastronomia','Cocina de viñedo','Cocina de viñedo.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31161','gastronomia','Vinos de calidad','Vinos de calidad.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31162','gastronomia','Cocina de sierra','Cocina de sierra.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31163','gastronomia','Lechazo, cocina tradicional','Lechazo, cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31164','gastronomia','Productos de Ribera','Productos de Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31165','gastronomia','Piquillo, verduras, vinos','Piquillo, verduras, vinos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31166','gastronomia','Cocina de valle','Cocina de valle.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31167','gastronomia','Cocina de Zona Media','Cocina de Zona Media.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31168','gastronomia','Trufa negra, productos de monte','Trufa negra, productos de monte.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31169','gastronomia','Verduras, conservas','Verduras, conservas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31170','gastronomia','Cocina rural','Cocina rural.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31171','gastronomia','Cocina de la Ribera','Cocina de la Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31173','gastronomia','Verduras de Ribera','Verduras de Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31174','gastronomia','Cocina de valle','Cocina de valle.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31175','gastronomia','Cocina de viñedo','Cocina de viñedo.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31176','gastronomia','Verduras, aceite, vinos','Verduras, aceite, vinos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31177','gastronomia','Cocina de valle','Cocina de valle.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31178','gastronomia','Cocina de Ribera','Cocina de Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31179','gastronomia','Cocina de Ribera','Cocina de Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31180','gastronomia','Cocina del Camino','Cocina del Camino.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31182','gastronomia','Cocina de sierra','Cocina de sierra.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31183','gastronomia','Cocina del Camino, vinos','Cocina del Camino, vinos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31184','gastronomia','Cocina de valle','Cocina de valle.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31186','gastronomia','Cocina de valle','Cocina de valle.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31187','gastronomia','Cocina pirenaica','Cocina pirenaica.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31190','gastronomia','Cocina de monte','Cocina de monte.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33013','gastronomia','Vinos (D','Vinos (D.O. Navarra), asados.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31192','gastronomia','Cocina de Zona Media','Cocina de Zona Media.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31195','gastronomia','Quesos de montaña, caza','Quesos de montaña, caza.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31196','gastronomia','Cocina de montaña','Cocina de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31197','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31199','gastronomia','Cocina de montaña','Cocina de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31200','gastronomia','Cocina de la Ribera alta','Cocina de la Ribera alta.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33014','gastronomia','Gastronomía completa, pinchos, asados','Gastronomía completa, pinchos, asados.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31203','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31204','gastronomia','Cocina rural','Cocina rural.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31205','gastronomia','Cocina de la Laguna, vinos','Cocina de la Laguna, vinos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33015','gastronomia','Cocina del Camino, vinos, asados','Cocina del Camino, vinos, asados.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31207','gastronomia','Cocina de la Zona Media','Cocina de la Zona Media.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31208','gastronomia','Verduras, aceite','Verduras, aceite.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31209','gastronomia','Cocina de sierra','Cocina de sierra.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31212','gastronomia','Cocina de la Merindad','Cocina de la Merindad.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31213','gastronomia','Cocina de montaña','Cocina de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31215','gastronomia','Verduras, conservas','Verduras, conservas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31217','gastronomia','Vinos rosados de gran calidad','Vinos rosados de gran calidad.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31219','gastronomia','Cocina de viñedo','Cocina de viñedo.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31220','gastronomia','Cocina de Ribera','Cocina de Ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31223','gastronomia','Pimiento de Sartaguda, conservas','Pimiento de Sartaguda, conservas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31224','gastronomia','Legumbres, vinos','Legumbres, vinos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31225','gastronomia','Cocina de viñedo','Cocina de viñedo.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31226','gastronomia','Cocina atlántica','Cocina atlántica.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31227','gastronomia','Vinos, cordero al chilindrón','Vinos, cordero al chilindrón.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31228','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31229','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31230','gastronomia','Cocina de sierra','Cocina de sierra.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31231','gastronomia','Cocina del Camino','Cocina del Camino.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31232','gastronomia','Verduras (alcachofas, espárragos)','Verduras (alcachofas, espárragos).','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31233','gastronomia','Cocina conventual, conservas','Cocina conventual, conservas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31234','gastronomia','Cocina de la Zona Media','Cocina de la Zona Media.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31235','gastronomia','Migas de pastor, repostería','Migas de pastor, repostería.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31236','gastronomia','Cuajada, carnes de montaña','Cuajada, carnes de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31237','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31238','gastronomia','Cocina de Zona Media','Cocina de Zona Media.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31240','gastronomia','Quesos, embutidos','Quesos, embutidos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31241','gastronomia','Cocina de montaña','Cocina de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31242','gastronomia','Cocina tradicional','Cocina tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31243','gastronomia','Cocina de la Merindad','Cocina de la Merindad.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31246','gastronomia','Cocina del Camino','Cocina del Camino.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31249','gastronomia','Verduras, conservas','Verduras, conservas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31251','gastronomia','Vinos D','Vinos D.O.Ca. Rioja, asados.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31255','gastronomia','Vinos, cocina de bodega','Vinos, cocina de bodega.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31257','gastronomia','Cocina del Camino','Cocina del Camino.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31261','gastronomia','Cocina de sierra','Cocina de sierra.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31262','gastronomia','Cocina de valle','Cocina de valle.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31073','gastronomia','Cocina de montaña','Cocina de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31263','gastronomia','Cocina atlántica','Cocina atlántica.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31264','gastronomia','Carnes, cocina de montaña','Carnes, cocina de montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('31265','gastronomia','Cocina de monte','Cocina de monte.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33004','gastronomia','Vinos, cordero al chilindrón','Vinos, cordero al chilindrón.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33010','gastronomia','Repostería, cocina de sierra','Repostería, cocina de sierra.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33011','gastronomia','Cocina de Zona Media','Cocina de Zona Media.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33019','gastronomia','Verduras (alcachofas, espárragos)','Verduras (alcachofas, espárragos).','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33020','gastronomia','Migas de pastor, repostería','Migas de pastor, repostería.','excel_curado',date('now'));