-- Gastronomía País Vasco — generado desde guías gastronómicas Excel
-- Provincias: Álava, Vizcaya, Guipúzcoa
-- Municipios con datos: 177

-- 1. Reset
UPDATE puntuaciones SET puntuacion=0 WHERE categoria='gastronomia'
  AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE provincia IN ('Álava', 'Vizcaya', 'Guipúzcoa'));

-- 2. Limpiar entidades automáticas OSM/wikidata
DELETE FROM entidades WHERE tipo IN ('gastronomia','producto')
  AND fuente IN ('wikidata','OSM')
  AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE provincia IN ('Álava', 'Vizcaya', 'Guipúzcoa'));

-- 3. Default 12 para todos
UPDATE puntuaciones SET puntuacion=12 WHERE categoria='gastronomia'
  AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE provincia IN ('Álava', 'Vizcaya', 'Guipúzcoa'));

-- 4. Scores individuales (137 municipios con datos)
UPDATE puntuaciones SET puntuacion=83 WHERE codigo_ine IN ('48020', '47004') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=80 WHERE codigo_ine='20902' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=77 WHERE codigo_ine='48052' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=69 WHERE codigo_ine IN ('20071', '21017') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=63 WHERE codigo_ine='21018' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=59 WHERE codigo_ine IN ('01022', '50014') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=57 WHERE codigo_ine='21010' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=52 WHERE codigo_ine='47010' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=49 WHERE codigo_ine='21011' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=48 WHERE codigo_ine='20069' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=44 WHERE codigo_ine='50039' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=30 WHERE codigo_ine IN ('20906', '21001', '20903', '21003', '21004', '20904', '21005', '20019', '20020', '20021', '20022', '21006', '20023', '20024', '21007', '21008', '20030', '20033', '20032', '20067', '20038', '20037', '20907', '20040', '20041', '20042', '20043', '20044', '21012', '20045', '20046', '20047', '20048', '20050', '20051', '20052', '20054', '20901', '20057', '20058', '20905', '20061', '20062', '21014', '21015', '20070', '20072', '20073', '20075', '20078', '21019', '21020', '20080') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=28 WHERE codigo_ine='50003' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=24 WHERE codigo_ine='48021' AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=23 WHERE codigo_ine IN ('01035', '48911', '48912', '47002', '48009', '48010', '48011', '47001', '48014', '48015', '48092', '48016', '48017', '48018', '48019', '48901', '48026', '48027', '48028', '47006', '48032', '48902', '48034', '48906', '48035', '48037', '48038', '48041', '47007', '47008', '48047', '48043', '48045', '48048', '48049', '48910', '48050', '48907', '48051', '47009', '48055', '48056', '48081', '48058', '48061', '48059', '48062', '48063', '48066', '47011', '48069', '48909', '47012', '48073', '48083', '48078', '48085', '48086', '48088', '48089', '48095', '48096', '48905', '48097', '48024', '48025', '47003', '47005') AND categoria='gastronomia';

-- 5. Entidades gastronómicas
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('50003','gastronomia','Cocina de pasto, quesos artesanos','Cocina de pasto, quesos artesanos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('01022','gastronomia','Sede de la icónica bodega Marqués de Riscal (arquitectura de Frank Gehry) con restaurante de alto...','Sede de la icónica bodega Marqués de Riscal (arquitectura de Frank Gehry) con restaurante de alto nivel. Vinos de Rioja Alavesa, cocina de autor. Sí (históricamente). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('01035','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('50039','gastronomia','Capital de Álava con buena escena de restaurantes y fuerte tradición vasca + influencia de Rioja ...','Capital de Álava con buena escena de restaurantes y fuerte tradición vasca + influencia de Rioja Alavesa. Vinos de Rioja Alavesa, cocina vasca tradicional. Sí - Algunos 1★. Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('50014','gastronomia','Sede de la icónica bodega Marqués de Riscal (arquitectura de Frank Gehry) con restaurante de alto...','Sede de la icónica bodega Marqués de Riscal (arquitectura de Frank Gehry) con restaurante de alto nivel. Vinos de Rioja Alavesa, cocina de autor. Sí (históricamente). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48021','gastronomia','Cocina rural','Cocina rural.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48911','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48912','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('47002','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48009','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48010','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48011','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('47001','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48014','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48015','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48092','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48016','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48017','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48018','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48019','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48020','gastronomia','Revolución gastronómica urbana','Revolución gastronómica urbana. Excelente escena de pintxos modernos y alta cocina junto al producto del Cantábrico. Pintxos creativos, bacalao al pil-pil, marisco. Sí - Varios 1★ y 2★. Muy Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48901','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48026','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48027','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48028','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('47006','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48032','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48902','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48034','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48906','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48035','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48037','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48038','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48041','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('47007','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('47008','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48047','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48043','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48045','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48048','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48049','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48910','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48050','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48907','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48051','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48052','gastronomia','Sede de Azurmendi (Eneko Atxa, 3★)','Sede de Azurmendi (Eneko Atxa, 3★). Cocina sostenible, creativa y con fuerte identidad vasca. Cocina de autor sostenible, producto de temporada. Sí - Azurmendi 3★. Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('47009','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('47010','gastronomia','Pueblo pesquero auténtico con excelente marisco y pescado del Cantábrico','Pueblo pesquero auténtico con excelente marisco y pescado del Cantábrico. Muy buena calidad tradicional. Marisco fresco, pescado del día. No. Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48055','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48056','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48081','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48058','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48061','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48059','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48062','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48063','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48066','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('47011','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48069','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48909','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('47012','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48073','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48083','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48078','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48085','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48086','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48088','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48089','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48095','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48096','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48905','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48097','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48024','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('48025','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('47003','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('47004','gastronomia','Revolución gastronómica urbana','Revolución gastronómica urbana. Excelente escena de pintxos modernos y alta cocina junto al producto del Cantábrico. Pintxos creativos, bacalao al pil-pil, marisco. Sí - Varios 1★ y 2★. Muy Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('47005','gastronomia','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral','Buena escena de pintxos (especialmente cerca de Bilbao) y tradición costera en el litoral. Calidad general alta. Pintxos, bacalao, marisco del Cantábrico. No (salvo Larrabetzu). Medio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20906','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21001','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20903','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21003','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21004','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20904','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21005','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20019','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20020','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20021','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20022','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21006','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20023','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20024','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21007','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21008','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20030','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20033','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20032','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20067','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20038','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20037','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20907','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21010','gastronomia','Cuna del txakoli y famosa por su pescado a la brasa, especialmente txuleta de atún','Cuna del txakoli y famosa por su pescado a la brasa, especialmente txuleta de atún. Txakoli, atún a la brasa, anchoas. No. Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20040','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20041','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21011','gastronomia','Pueblo histórico con muy buena gastronomía vasca, tanto tradicional como moderna','Pueblo histórico con muy buena gastronomía vasca, tanto tradicional como moderna. Pintxos, pescado, cocina vasca de calidad. Sí - Algunos destacados. Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20042','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20043','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20044','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21012','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20045','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20046','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20047','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20048','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20902','gastronomia','Sede de Martín Berasategui (3★)','Sede de Martín Berasategui (3★). Uno de los grandes templos de la alta cocina vasca contemporánea. Cocina de autor de máximo nivel con producto local. Sí - Martín Berasategui 3★. Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20050','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20051','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20052','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20054','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20901','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20057','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20058','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20905','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20061','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20062','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21014','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21015','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20070','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20071','gastronomia','Referencia absoluta en txuleta a la brasa y alubias blancas','Referencia absoluta en txuleta a la brasa y alubias blancas. Uno de los pueblos donde mejor se come tradición vasca. Txuleta de buey, alubias de Tolosa, producto local. No. Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20072','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20073','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20075','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20078','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21018','gastronomia','Excelente combinación de producto del mar, txakoli y buena escena de restaurantes y pintxos','Excelente combinación de producto del mar, txakoli y buena escena de restaurantes y pintxos. Marisco, pescado fresco, txakoli de Getaria. Sí - Algunos 1★. Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21019','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21020','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20080','gastronomia','Fuerte cultura de pintxos y excelente producto del mar en la costa','Fuerte cultura de pintxos y excelente producto del mar en la costa. Tradición vasca muy viva. Pintxos, txakoli, pescado y marisco fresco. No (pero cerca de Donostia). Medio-Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('21017','gastronomia','Referencia absoluta en txuleta a la brasa y alubias blancas','Referencia absoluta en txuleta a la brasa y alubias blancas. Uno de los pueblos donde mejor se come tradición vasca. Txuleta de buey, alubias de Tolosa, producto local. No. Alto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('20069','gastronomia','Alogador, miel de palma, queso de cabra','Alogador, miel de palma, queso de cabra. Capital gomera; cocina de puerto histórico colombino.','excel_curado',date('now'));