-- Gastronomía Asturias — generado desde guías gastronómicas Excel
-- Provincias: Asturias
-- Municipios con datos: 78

-- 1. Reset
UPDATE puntuaciones SET puntuacion=0 WHERE categoria='gastronomia'
  AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE provincia IN ('Asturias'));

-- 2. Limpiar entidades automáticas OSM/wikidata
DELETE FROM entidades WHERE tipo IN ('gastronomia','producto')
  AND fuente IN ('wikidata','OSM')
  AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE provincia IN ('Asturias'));

-- 3. Default 12 para todos
UPDATE puntuaciones SET puntuacion=12 WHERE categoria='gastronomia'
  AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE provincia IN ('Asturias'));

-- 4. Scores individuales (77 municipios con datos)
UPDATE puntuaciones SET puntuacion=92 WHERE codigo_ine IN ('33044', '05013') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=88 WHERE codigo_ine IN ('33024', '05009') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=80 WHERE codigo_ine IN ('05004', '33036', '05010') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN ('05005', '33045', '05014') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=72 WHERE codigo_ine IN ('05002', '33056', '05020') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=68 WHERE codigo_ine IN ('05008', '33073', '33076', '05024') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=64 WHERE codigo_ine IN ('33043', '05012') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=60 WHERE codigo_ine IN ('05006', '33040', '33042', '33071', '33034', '05022') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=56 WHERE codigo_ine IN ('33025', '33066', '33070') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=48 WHERE codigo_ine IN ('33033', '33037') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=44 WHERE codigo_ine IN ('33038', '33041', '33047', '33068', '33069', '05016', '05021') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=40 WHERE codigo_ine IN ('33026', '33031', '33039', '33046', '33049', '33051', '33055', '33059', '33060', '05015', '05019') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=36 WHERE codigo_ine IN ('33030', '33032', '33035', '33050', '33053', '33067', '33072', '33074', '05018', '05023') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=32 WHERE codigo_ine IN ('33028', '33052', '33058') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=28 WHERE codigo_ine IN ('05001', '05003', '33023', '33027', '33054', '33057', '33065') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=24 WHERE codigo_ine IN ('33022', '33063', '33062', '33064', '33077') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=20 WHERE codigo_ine IN ('33061', '33075') AND categoria='gastronomia';
UPDATE puntuaciones SET puntuacion=16 WHERE codigo_ine IN ('33029', '33048') AND categoria='gastronomia';

-- 5. Entidades gastronómicas
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05001','gastronomia','Queso de Los Beyos (I','Queso de Los Beyos (I.G.P.); carne de cabrito; guisos de caza. Tradición quesera en el desfiladero de Los Beyos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05002','gastronomia','Longaniza de Avilés; pescados de la rula (lonja); pixín frito','Longaniza de Avilés; pescados de la rula (lonja); pixín frito. Restaurante Tataguyo (Histórico), gastrobares del casco antiguo.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05003','gastronomia','Pote de castañas; embutidos caseros; trucha de río','Pote de castañas; embutidos caseros; trucha de río. Cocina vinculada a la caza y los recursos del río Pigüeña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05004','gastronomia','Queso Cabrales (D','Queso Cabrales (D.O.P.); carne de cabrito; tortos con queso. Cuna del queso azul más famoso del mundo; certamen de Arenas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05005','gastronomia','Queso Gamonéu (D','Queso Gamonéu (D.O.P.); carne de caza; salmón del Sella. El Molín de la Pedrera, mercado dominical de quesos artesanos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05006','gastronomia','Pote de berzas; carne de los valles; Vino de Cangas (D','Pote de berzas; carne de los valles; Vino de Cangas (D.O.P.). Bodegas tradicionales, Fiesta de la Vendimia de alta montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05008','gastronomia','Curadillo (pescado seco); pixín; andaricas (nécoras)','Curadillo (pescado seco); pixín; andaricas (nécoras). El Pescador, sidrerías del anfiteatro marinero.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33022','gastronomia','Caza mayor (jabalí; corzo); potes de montaña; embutidos rústicos','Caza mayor (jabalí; corzo); potes de montaña; embutidos rústicos. Gastronomía de los valles más occidentales y recónditos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33023','gastronomia','Pescados de roca; pulpo a la gallega/asturiana; carnes locales','Pescados de roca; pulpo a la gallega/asturiana; carnes locales. Gastronomía marinera en el puerto de Viavélez.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33024','gastronomia','Pixín; caldereta; tortos; cazuelas de marisco; sidra natural','Pixín; caldereta; tortos; cazuelas de marisco; sidra natural. Auga (1*), La Salgar (1*), infinitas sidrerías tradicionales.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33025','gastronomia','Pescados y mariscos de Luanco; calamares; bonito en rollo','Pescados y mariscos de Luanco; calamares; bonito en rollo. Capital del cabo Peñas; cocina marinera de altísima calidad.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33026','gastronomia','Torta de Grado (dulce); escanda; hortalizas de la huerta','Torta de Grado (dulce); escanda; hortalizas de la huerta. Mercados tradicionales de hortalizas y panadería artesana.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33027','gastronomia','Embutidos secos; caldo de navizas; carnes de cerdo','Embutidos secos; caldo de navizas; carnes de cerdo. Cocina del Camino de Santiago Primitivo en el interior.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33028','gastronomia','Miel artesana; embutidos tradicionales; vino de la tierra','Miel artesana; embutidos tradicionales; vino de la tierra. Gastronomía de corte solanero e interior montañoso.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33029','gastronomia','Potes de berzas; carnes a la brasa; repostería de sartén','Potes de berzas; carnes a la brasa; repostería de sartén. Cocina rural de la cuenca media del Navia.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33030','gastronomia','Queso de La Peral (azul selecto); carnes de monte','Queso de La Peral (azul selecto); carnes de monte. Cuna de la quesería artesana de La Peral; tradición quesera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33031','gastronomia','Cortadillos; fabada asturiana; cebollas rellenas','Cortadillos; fabada asturiana; cebollas rellenas. Jornadas gastronómicas de la cocina minera tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33032','gastronomia','Cabrito con patatines; Bartolos (postre de almendra)','Cabrito con patatines; Bartolos (postre de almendra). Famoso por sus guisados tradicionales de fiesta y romería.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33033','gastronomia','Guisos de cordero a la estaca; embutidos de montaña; potes','Guisos de cordero a la estaca; embutidos de montaña; potes. Monte (1* Michelin en San Feliz; cocina de entorno radical).','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33035','gastronomia','Carne de ternera; fabada asturiana; tablas de quesos del centro','Carne de ternera; fabada asturiana; tablas de quesos del centro. Centro neurálgico de certámenes ganaderos y parrilladas.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33036','gastronomia','Verdinas con marisco; Queso de Pría; pescados de roca','Verdinas con marisco; Queso de Pría; pescados de roca. El Retiro (1* Michelin en Pancar), Chibiski, marisquerías.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33037','gastronomia','Cebollas rellenas de bonito; pote minero; sidra tradicional','Cebollas rellenas de bonito; pote minero; sidra tradicional. Tradición de chigres y sidrerías con arraigo obrero y minero.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33038','gastronomia','Queso de Afuega''l pitu (D','Queso de Afuega''l pitu (D.O.P.); potes de nabos. Certamen del quesu Afuega''l pitu en La Foz de Morcín.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33039','gastronomia','Angulas del Nalón; pescados de la costa; fritos de pixín','Angulas del Nalón; pescados de la costa; fritos de pixín. Alta cocina marinera en San Esteban de Praga.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33040','gastronomia','Sidra natural; platos cocinados a la sidra; fabada','Sidra natural; platos cocinados a la sidra; fabada. Capital de la Sidra, Museo de la Sidra, Festival de la Sidra.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33041','gastronomia','Veneras (postre de almendra); pescados y mariscos de lonja','Veneras (postre de almendra); pescados y mariscos de lonja. Alta repostería naviega y sidrerías de costa.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33042','gastronomia','Mondongo (morcilla); callos; sabadiegos; pies de cerdo','Mondongo (morcilla); callos; sabadiegos; pies de cerdo. Capital de la industria cárnica y la chacinería tradicional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33043','gastronomia','Queso Gamonéu de Onís; carne de cabrito asada','Queso Gamonéu de Onís; carne de cabrito asada. Certamen de los Quesos de los Picos de Europa en Benia.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33044','gastronomia','Carbayones; Moscovitas; fabada; Afuega''l pitu','Carbayones; Moscovitas; fabada; Afuega''l pitu. Capital gastronómica, Bulevar de la Sidra (Gascona), Casa Fermín.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33045','gastronomia','Salmón; trucha; caza; arroces de monte; platos tradicionales','Salmón; trucha; caza; arroces de monte; platos tradicionales. Casa Marcial (2* Michelin de Nacho Manzano en La Salgar).','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33046','gastronomia','Queso de Alles; truchas del Cares; cabrito asado','Queso de Alles; truchas del Cares; cabrito asado. Gastronomía rural de los Picos de Europa orientales.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33047','gastronomia','Queso de Panes; salmón; guisos de carne de caza','Queso de Panes; salmón; guisos de carne de caza. Gastronomía de frontera fluvial ligada al río Deva.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33048','gastronomia','Vino de la tierra; caldos gallegos; embutidos artesanos','Vino de la tierra; caldos gallegos; embutidos artesanos. Pequeña producción vitivinícola y cocina de subsistencia.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33049','gastronomia','Platos de caza (gamo; jabalí); avellanas; sidra natural','Platos de caza (gamo; jabalí); avellanas; sidra natural. Festival de la Avellana en Infiesto; jornadas de caza.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33050','gastronomia','Queso de Los Beyos; carne de monte; embutidos','Queso de Los Beyos; carne de monte; embutidos. Cocina rústica rodeada por el Parque Natural de Ponga.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33051','gastronomia','Hortalizas de la vega del Nalón; salmón; repostería de convento','Hortalizas de la vega del Nalón; salmón; repostería de convento. Famoso por sus cultivos de faba asturiana de alta calidad.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33052','gastronomia','Quesos de la zona; pote de castañas; jabalí estofado','Quesos de la zona; pote de castañas; jabalí estofado. Gastronomía de la Senda del Oso; cocina de los valles del Trubia.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33053','gastronomia','Cordero a la estaca; embutidos caseros; potes tradicionales','Cordero a la estaca; embutidos caseros; potes tradicionales. Famoso por la Fiesta del Cordero en el Prau Llagüezos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33054','gastronomia','Castañas asadas; fabada asturiana; carne a la parrilla','Castañas asadas; fabada asturiana; carne a la parrilla. Cocina tradicional casera en las cercanías de Oviedo.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33055','gastronomia','Pescados del Cantábrico; marisco de Colombres; corbatas','Pescados del Cantábrico; marisco de Colombres; corbatas. Gastronomía de costa limítrofe con Cantabria.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33057','gastronomia','Quesos del centro; hortalizas de huerta; potes de berza','Quesos del centro; hortalizas de huerta; potes de berza. Cocina de cercanía e ingredientes tradicionales de ribera.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33056','gastronomia','Salmón; angulas; arroz con bugre; repostería fina','Salmón; angulas; arroz con bugre; repostería fina. Ay國 / Arbidel (1* Michelin de Jaime Uz); cocina de puerto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33058','gastronomia','Pote de nabos; embutidos ahumados; carnes de montaña','Pote de nabos; embutidos ahumados; carnes de montaña. Gastronomía vinculada a la ascensión mítica del Angliru.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33059','gastronomia','Carajitos del Profesor (dulce de avellana); pote; ternera','Carajitos del Profesor (dulce de avellana); pote; ternera. Cuna de los carajitos artesanales más famosos de Asturias.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33061','gastronomia','Caldo de cimos; embutidos de matanza; carnes a la brasa','Caldo de cimos; embutidos de matanza; carnes a la brasa. Cocina tradicional de la comarca más occidental y protegida.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33060','gastronomia','Cebollas rellenas; patatas rellenas; casadielles','Cebollas rellenas; patatas rellenas; casadielles. Fiestas gastronómicas declaradas de interés turístico nacional.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33063','gastronomia','Trucha de río; salmón; repostería casera; embutidos','Trucha de río; salmón; repostería casera; embutidos. Cocina fluvial de la frontera occidental asturiana.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33062','gastronomia','Caldo gallego-asturiano; hogaza de pan de leña; embutidos','Caldo gallego-asturiano; hogaza de pan de leña; embutidos. Turismo rural gastronómico vinculado a los artesanos del hierro.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33064','gastronomia','Guisos de jabalí; fabada asturiana; tortos con huevos','Guisos de jabalí; fabada asturiana; tortos con huevos. Cocina tradicional de paso en pleno corazón de los valles verdes.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33065','gastronomia','Fabes con almejas; embutidos de caserío; sidra natural','Fabes con almejas; embutidos de caserío; sidra natural. Cocina integrada en la comarca de la sidra del interior.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33066','gastronomia','Les Flores (dulce); callos a la asturiana; parrilladas','Les Flores (dulce); callos a la asturiana; parrilladas. Capital mundial de los mercados de ganado; Pola de Siero.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33067','gastronomia','Pote de pucherín; truchas; caza mayor; miel selecta','Pote de pucherín; truchas; caza mayor; miel selecta. Gastronomía del Parque Natural de Redes.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33068','gastronomia','Carne de raza Asturiana de los Valles; potes de montaña','Carne de raza Asturiana de los Valles; potes de montaña. Ternera de altísima calidad criada en pastos de alta montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33069','gastronomia','Angulas del Nalón; pescado fresco; arroces marineros','Angulas del Nalón; pescado fresco; arroces marineros. Famoso por la pesca y preparación de la angula en San Juan de la Arena.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33070','gastronomia','Percebes; bonito del norte; arroces caldosos de marisco','Percebes; bonito del norte; arroces caldosos de marisco. Epicentro del marisco de roca del occidente asturiano.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33071','gastronomia','Queso de Taramundi (con nueces); pan artesano; embutidos','Queso de Taramundi (con nueces); pan artesano; embutidos. Pionero del turismo rural; asadores tradicionales de leña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33072','gastronomia','Pote tevergano (con compango ahumado); pan de escanda','Pote tevergano (con compango ahumado); pan de escanda. Jornadas del Pote Tevergano en otoño, cocina contundente.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33073','gastronomia','Chosco de Tineo (I','Chosco de Tineo (I.G.P.); embutidos; pote de huesos. Capital indiscutible de la chacinería de interior asturiana.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33034','gastronomia','Calamares de Luarca; pescados de roca; pote asturiano','Calamares de Luarca; pescados de roca; pote asturiano. Gran tradición de cocina marinera en el puerto de Luarca.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33074','gastronomia','Pescados de ría; embutidos secos; carnes a la brasa','Pescados de ría; embutidos secos; carnes a la brasa. Feria de muestras y gastronomía de la llanura del Eo.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33075','gastronomia','Caldos caseros; embutidos de cerdo asturcelta; ternera','Caldos caseros; embutidos de cerdo asturcelta; ternera. Cocina tradicional de montaña vinculada a su monasterio.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33076','gastronomia','Fabes con almejas; sidra con D','Fabes con almejas; sidra con D.O.P.; centollos de ría. Capital de la manzana y la sidra espumosa de alta gama.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('33077','gastronomia','Quesos artesanales; potes de berzas; carnes de ternera','Quesos artesanales; potes de berzas; carnes de ternera. Cocina de montaña del interior del occidente asturiano.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05009','gastronomia','Pixín; caldereta; tortos; cazuelas de marisco; sidra natural','Pixín; caldereta; tortos; cazuelas de marisco; sidra natural. Auga (1*), La Salgar (1*), infinitas sidrerías tradicionales.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05010','gastronomia','Verdinas con marisco; Queso de Pría; pescados de roca','Verdinas con marisco; Queso de Pría; pescados de roca. El Retiro (1* Michelin en Pancar), Chibiski, marisquerías.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05012','gastronomia','Queso Gamonéu de Onís; carne de cabrito asada','Queso Gamonéu de Onís; carne de cabrito asada. Certamen de los Quesos de los Picos de Europa en Benia.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05013','gastronomia','Carbayones; Moscovitas; fabada; Afuega''l pitu','Carbayones; Moscovitas; fabada; Afuega''l pitu. Capital gastronómica, Bulevar de la Sidra (Gascona), Casa Fermín.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05014','gastronomia','Salmón; trucha; caza; arroces de monte; platos tradicionales','Salmón; trucha; caza; arroces de monte; platos tradicionales. Casa Marcial (2* Michelin de Nacho Manzano en La Salgar).','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05015','gastronomia','Queso de Alles; truchas del Cares; cabrito asado','Queso de Alles; truchas del Cares; cabrito asado. Gastronomía rural de los Picos de Europa orientales.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05016','gastronomia','Queso de Panes; salmón; guisos de carne de caza','Queso de Panes; salmón; guisos de carne de caza. Gastronomía de frontera fluvial ligada al río Deva.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05018','gastronomia','Cordero a la estaca; embutidos caseros; potes tradicionales','Cordero a la estaca; embutidos caseros; potes tradicionales. Famoso por la Fiesta del Cordero en el Prau Llagüezos.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05019','gastronomia','Pescados del Cantábrico; marisco de Colombres; corbatas','Pescados del Cantábrico; marisco de Colombres; corbatas. Gastronomía de costa limítrofe con Cantabria.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05020','gastronomia','Salmón; angulas; arroz con bugre; repostería fina','Salmón; angulas; arroz con bugre; repostería fina. Ay國 / Arbidel (1* Michelin de Jaime Uz); cocina de puerto.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05021','gastronomia','Carne de raza Asturiana de los Valles; potes de montaña','Carne de raza Asturiana de los Valles; potes de montaña. Ternera de altísima calidad criada en pastos de alta montaña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05022','gastronomia','Queso de Taramundi (con nueces); pan artesano; embutidos','Queso de Taramundi (con nueces); pan artesano; embutidos. Pionero del turismo rural; asadores tradicionales de leña.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05023','gastronomia','Pote tevergano (con compango ahumado); pan de escanda','Pote tevergano (con compango ahumado); pan de escanda. Jornadas del Pote Tevergano en otoño, cocina contundente.','excel_curado',date('now'));
INSERT OR IGNORE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,fecha_ingesta) VALUES ('05024','gastronomia','Chosco de Tineo (I','Chosco de Tineo (I.G.P.); embutidos; pote de huesos. Capital indiscutible de la chacinería de interior asturiana.','excel_curado',date('now'));