-- Migration: 0203b_campings_scores.sql
-- Fecha: 2026-06-11
-- Descripción: Actualizar scores de campings por municipio

UPDATE puntuaciones SET puntuacion=76 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='A Guarda');
UPDATE puntuaciones SET puntuacion=75 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Abejar');
UPDATE puntuaciones SET puntuacion=65 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Aguimes / San Bartolomé de Tirajana');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Albarracín');
UPDATE puntuaciones SET puntuacion=80 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Alcossebre / Alcalà de Xivert');
UPDATE puntuaciones SET puntuacion=62 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Algeciras');
UPDATE puntuaciones SET puntuacion=68 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Allariz');
UPDATE puntuaciones SET puntuacion=81 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Alquézar');
UPDATE puntuaciones SET puntuacion=65 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Anna');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Arbizu');
UPDATE puntuaciones SET puntuacion=81 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Arnuero / Isla');
UPDATE puntuaciones SET puntuacion=62 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Ateca');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Auritz/Burguete');
UPDATE puntuaciones SET puntuacion=79 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Ayamonte');
UPDATE puntuaciones SET puntuacion=61 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Aznalcázar');
UPDATE puntuaciones SET puntuacion=88 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Aínsa-Sobrarbe / Boltaña');
UPDATE puntuaciones SET puntuacion=89 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Baiona');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Bareyo / Ajo');
UPDATE puntuaciones SET puntuacion=82 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Barreiros');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Baños de Montemayor / Hervás');
UPDATE puntuaciones SET puntuacion=64 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Baños de la Encina');
UPDATE puntuaciones SET puntuacion=86 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Benasque');
UPDATE puntuaciones SET puntuacion=82 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Benicàssim');
UPDATE puntuaciones SET puntuacion=88 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Benidorm');
UPDATE puntuaciones SET puntuacion=92 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Berga');
UPDATE puntuaciones SET puntuacion=75 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Bielsa');
UPDATE puntuaciones SET puntuacion=95 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Blanes');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Burgohondo');
UPDATE puntuaciones SET puntuacion=68 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Burgos');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Bétera');
UPDATE puntuaciones SET puntuacion=84 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Cadaqués');
UPDATE puntuaciones SET puntuacion=98 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Calonge / Sant Antoni de Calonge');
UPDATE puntuaciones SET puntuacion=83 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Calpe / Calp');
UPDATE puntuaciones SET puntuacion=93 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Cambrils');
UPDATE puntuaciones SET puntuacion=84 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Canet de Mar');
UPDATE puntuaciones SET puntuacion=87 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Cangas de Onís');
UPDATE puntuaciones SET puntuacion=84 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Cangas do Morrazo');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Cantalejo');
UPDATE puntuaciones SET puntuacion=75 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Caravia');
UPDATE puntuaciones SET puntuacion=60 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Carcabuey');
UPDATE puntuaciones SET puntuacion=86 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Cartagena / La Manga');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Castañares de Rioja');
UPDATE puntuaciones SET puntuacion=94 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Castell-Platja d''Aro');
UPDATE puntuaciones SET puntuacion=74 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Castro Urdiales');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Cañizares');
UPDATE puntuaciones SET puntuacion=68 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Cervera de Pisuerga');
UPDATE puntuaciones SET puntuacion=68 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Ciudad Rodrigo');
UPDATE puntuaciones SET puntuacion=86 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Comillas');
UPDATE puntuaciones SET puntuacion=89 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Conil de la Frontera');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Cortegana');
UPDATE puntuaciones SET puntuacion=95 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Crevillente');
UPDATE puntuaciones SET puntuacion=82 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Cuacos de Yuste / Aldeanueva de la Vera');
UPDATE puntuaciones SET puntuacion=85 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Cudillero');
UPDATE puntuaciones SET puntuacion=74 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Cuenca');
UPDATE puntuaciones SET puntuacion=67 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Cuevas del Almanzora');
UPDATE puntuaciones SET puntuacion=75 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Cáceres');
UPDATE puntuaciones SET puntuacion=65 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Córdoba');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Deltebre');
UPDATE puntuaciones SET puntuacion=64 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Dos Hermanas');
UPDATE puntuaciones SET puntuacion=80 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Dénia');
UPDATE puntuaciones SET puntuacion=55 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='El Paso');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='El Puerto de Santa María');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Elburgo / Landazuri');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Elche / Elx');
UPDATE puntuaciones SET puntuacion=74 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Enguera');
UPDATE puntuaciones SET puntuacion=62 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Escorca');
UPDATE puntuaciones SET puntuacion=89 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Espot');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Estepona');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Fisterra / Finisterre');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Fortuna');
UPDATE puntuaciones SET puntuacion=76 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Foz');
UPDATE puntuaciones SET puntuacion=66 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Frías');
UPDATE puntuaciones SET puntuacion=69 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Fuengirola / Mijas');
UPDATE puntuaciones SET puntuacion=82 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Galar / Pamplona');
UPDATE puntuaciones SET puntuacion=76 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Galende / Lago de Sanabria');
UPDATE puntuaciones SET puntuacion=76 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Gandía');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Gata / Hoyos');
UPDATE puntuaciones SET puntuacion=75 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Gorliz');
UPDATE puntuaciones SET puntuacion=68 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Granada');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Graus');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Grazalema');
UPDATE puntuaciones SET puntuacion=93 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Guardamar del Segura');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Guriezo');
UPDATE puntuaciones SET puntuacion=58 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Guía de Isora / San Cristóbal de la Laguna');
UPDATE puntuaciones SET puntuacion=66 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Güejar Sierra');
UPDATE puntuaciones SET puntuacion=82 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Haro');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Hospital de Órbigo');
UPDATE puntuaciones SET puntuacion=68 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Hoyos del Espino');
UPDATE puntuaciones SET puntuacion=65 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Humilladero');
UPDATE puntuaciones SET puntuacion=82 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Isla Cristina');
UPDATE puntuaciones SET puntuacion=85 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Javea / Xàbia');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Karrantza Harana / Valle de Carranza');
UPDATE puntuaciones SET puntuacion=85 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='L''Ametlla de Mar');
UPDATE puntuaciones SET puntuacion=75 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='La Iruela / Cazorla');
UPDATE puntuaciones SET puntuacion=80 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='La Seu d''Urgell');
UPDATE puntuaciones SET puntuacion=63 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='La Zubia');
UPDATE puntuaciones SET puntuacion=80 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Laredo');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Liérganes');
UPDATE puntuaciones SET puntuacion=92 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Llanes');
UPDATE puntuaciones SET puntuacion=76 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Malpartida de Plasencia / Monfragüe');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Manzanera');
UPDATE puntuaciones SET puntuacion=83 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Marbella');
UPDATE puntuaciones SET puntuacion=88 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Mazaricos');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Mazarrón');
UPDATE puntuaciones SET puntuacion=74 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Mendigorría');
UPDATE puntuaciones SET puntuacion=86 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Moguer / Palos de la Frontera');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Mojácar');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Moncofa');
UPDATE puntuaciones SET puntuacion=66 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Monesterio');
UPDATE puntuaciones SET puntuacion=96 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Mont-roig del Camp / Miami Platja');
UPDATE puntuaciones SET puntuacion=75 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Motril / Carchuna');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Mundaka');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Mutriku');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Muíños');
UPDATE puntuaciones SET puntuacion=64 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Mérida');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Navajas');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Navaluenga');
UPDATE puntuaciones SET puntuacion=74 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Nerja');
UPDATE puntuaciones SET puntuacion=90 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Noja');
UPDATE puntuaciones SET puntuacion=75 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Nuévalos');
UPDATE puntuaciones SET puntuacion=88 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Níjar / Cabo de Gata');
UPDATE puntuaciones SET puntuacion=91 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='O Grove');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Ochagavía');
UPDATE puntuaciones SET puntuacion=88 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Oliva');
UPDATE puntuaciones SET puntuacion=68 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Olvera');
UPDATE puntuaciones SET puntuacion=68 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Orea / Peralejos de las Truchas');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Orio');
UPDATE puntuaciones SET puntuacion=90 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Oropesa del Mar');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Ossa de Montiel');
UPDATE puntuaciones SET puntuacion=84 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Peñíscola');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Pinofranqueado / Las Hurdes');
UPDATE puntuaciones SET puntuacion=82 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Pont de Suert');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Porto do Son');
UPDATE puntuaciones SET puntuacion=82 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Potes');
UPDATE puntuaciones SET puntuacion=75 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Punta Umbría');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Puzol / Puçol');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Quintanar de la Sierra');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Riaza');
UPDATE puntuaciones SET puntuacion=74 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Riaño');
UPDATE puntuaciones SET puntuacion=83 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Ribadesella');
UPDATE puntuaciones SET puntuacion=79 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Ribamontán al Mar / Somo');
UPDATE puntuaciones SET puntuacion=80 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Ribeira / Aguiño');
UPDATE puntuaciones SET puntuacion=65 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Ribera de Cabanes');
UPDATE puntuaciones SET puntuacion=82 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Ribes de Freser');
UPDATE puntuaciones SET puntuacion=76 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Riezu / Valle de Yerri');
UPDATE puntuaciones SET puntuacion=75 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Riópar');
UPDATE puntuaciones SET puntuacion=100 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Roda de Berà');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Ronda');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Roquetas de Mar');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Ruidera');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Ruiloba');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Salamanca');
UPDATE puntuaciones SET puntuacion=83 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Sallent de Gállego / Formigal');
UPDATE puntuaciones SET puntuacion=98 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Salou');
UPDATE puntuaciones SET puntuacion=74 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='San Sebastián / Donostia');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Sant Antoni de Portmany');
UPDATE puntuaciones SET puntuacion=100 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Sant Pere Pescador');
UPDATE puntuaciones SET puntuacion=67 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Santa Elena');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Santa Eulària des Riu');
UPDATE puntuaciones SET puntuacion=74 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Santa Pola');
UPDATE puntuaciones SET puntuacion=80 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Santa Susanna');
UPDATE puntuaciones SET puntuacion=68 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Santiago-Pontones');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Santillana del Mar');
UPDATE puntuaciones SET puntuacion=76 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Santo Domingo de la Calzada / Bañares');
UPDATE puntuaciones SET puntuacion=86 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Sanxenxo');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Segovia');
UPDATE puntuaciones SET puntuacion=82 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Sitges');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Somiedo');
UPDATE puntuaciones SET puntuacion=80 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Sopela / Sopelana');
UPDATE puntuaciones SET puntuacion=84 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Sort');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Sotoserrano');
UPDATE puntuaciones SET puntuacion=92 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Tarifa');
UPDATE puntuaciones SET puntuacion=70 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Toledo');
UPDATE puntuaciones SET puntuacion=68 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Tordesillas');
UPDATE puntuaciones SET puntuacion=91 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Torla-Ordesa');
UPDATE puntuaciones SET puntuacion=92 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Torroella de Montgrí / L''Estartit');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Torrox');
UPDATE puntuaciones SET puntuacion=89 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Tossa de Mar');
UPDATE puntuaciones SET puntuacion=74 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Totana');
UPDATE puntuaciones SET puntuacion=68 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Tuéjar');
UPDATE puntuaciones SET puntuacion=84 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Val de San Vicente');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Valdegovía / Gaubea');
UPDATE puntuaciones SET puntuacion=75 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Valderrobres / Beceite');
UPDATE puntuaciones SET puntuacion=75 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Valdoviño');
UPDATE puntuaciones SET puntuacion=85 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Valdáliga / Oyambre');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Valdés / Luarca');
UPDATE puntuaciones SET puntuacion=68 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Vega de Espinareda');
UPDATE puntuaciones SET puntuacion=75 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Vejer de la Frontera');
UPDATE puntuaciones SET puntuacion=95 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Vilanova i la Geltrú');
UPDATE puntuaciones SET puntuacion=58 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Villafranca de Córdoba');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Villajoyosa / La Vila Joiosa');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Villanúa');
UPDATE puntuaciones SET puntuacion=80 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Villaviciosa');
UPDATE puntuaciones SET puntuacion=68 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Vinaròs');
UPDATE puntuaciones SET puntuacion=72 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Vinuesa');
UPDATE puntuaciones SET puntuacion=74 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Viveiro');
UPDATE puntuaciones SET puntuacion=64 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Vélez-Blanco');
UPDATE puntuaciones SET puntuacion=60 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Yaiza');
UPDATE puntuaciones SET puntuacion=84 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Zahara de los Atunes / Barbate');
UPDATE puntuaciones SET puntuacion=66 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Zaragoza');
UPDATE puntuaciones SET puntuacion=85 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Zarautz');
UPDATE puntuaciones SET puntuacion=80 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Águilas');
UPDATE puntuaciones SET puntuacion=78 WHERE categoria='Campings' AND codigo_ine IN (SELECT codigo_ine FROM municipios WHERE nombre='Órgiva');