-- Turismo Rural España - Anexo 4 - Municipios Nuevos
-- Añadir 116 municipios nuevos (evitando duplicados)

UPDATE puntuaciones SET puntuacion = 62 WHERE categoria='TurismoRural' AND codigo_ine = '24004';
UPDATE puntuaciones SET puntuacion = 55 WHERE categoria='TurismoRural' AND codigo_ine = '23019';
UPDATE puntuaciones SET puntuacion = 40 WHERE categoria='TurismoRural' AND codigo_ine = '23065';
UPDATE puntuaciones SET puntuacion = 35 WHERE categoria='TurismoRural' AND codigo_ine = '24016';
UPDATE puntuaciones SET puntuacion = 60 WHERE categoria='TurismoRural' AND codigo_ine = '18045';
UPDATE puntuaciones SET puntuacion = 58 WHERE categoria='TurismoRural' AND codigo_ine = '18070';
UPDATE puntuaciones SET puntuacion = 52 WHERE categoria='TurismoRural' AND codigo_ine = '18168';
UPDATE puntuaciones SET puntuacion = 50 WHERE categoria='TurismoRural' AND codigo_ine = '18176';
UPDATE puntuaciones SET puntuacion = 45 WHERE categoria='TurismoRural' AND codigo_ine = '18132';
UPDATE puntuaciones SET puntuacion = 35 WHERE categoria='TurismoRural' AND codigo_ine = '18123';
UPDATE puntuaciones SET puntuacion = 55 WHERE categoria='TurismoRural' AND codigo_ine = '29040';
UPDATE puntuaciones SET puntuacion = 50 WHERE categoria='TurismoRural' AND codigo_ine = '29033';
UPDATE puntuaciones SET puntuacion = 45 WHERE categoria='TurismoRural' AND codigo_ine = '29061';
UPDATE puntuaciones SET puntuacion = 40 WHERE categoria='TurismoRural' AND codigo_ine = '29036';
UPDATE puntuaciones SET puntuacion = 35 WHERE categoria='TurismoRural' AND codigo_ine = '29087';
UPDATE puntuaciones SET puntuacion = 60 WHERE categoria='TurismoRural' AND codigo_ine = '41080';
UPDATE puntuaciones SET puntuacion = 58 WHERE categoria='TurismoRural' AND codigo_ine = '40001';
UPDATE puntuaciones SET puntuacion = 55 WHERE categoria='TurismoRural' AND codigo_ine = '41048';
UPDATE puntuaciones SET puntuacion = 50 WHERE categoria='TurismoRural' AND codigo_ine = '41073';
UPDATE puntuaciones SET puntuacion = 40 WHERE categoria='TurismoRural' AND codigo_ine = '41078';
UPDATE puntuaciones SET puntuacion = 65 WHERE categoria='TurismoRural' AND codigo_ine = '10024';
UPDATE puntuaciones SET puntuacion = 60 WHERE categoria='TurismoRural' AND codigo_ine = '10080';
UPDATE puntuaciones SET puntuacion = 58 WHERE categoria='TurismoRural' AND codigo_ine = '10111';
UPDATE puntuaciones SET puntuacion = 55 WHERE categoria='TurismoRural' AND codigo_ine = '10100';
UPDATE puntuaciones SET puntuacion = 52 WHERE categoria='TurismoRural' AND codigo_ine = '10060';
UPDATE puntuaciones SET puntuacion = 48 WHERE categoria='TurismoRural' AND codigo_ine = '10029';
UPDATE puntuaciones SET puntuacion = 42 WHERE categoria='TurismoRural' AND codigo_ine = '10050';
UPDATE puntuaciones SET puntuacion = 60 WHERE categoria='TurismoRural' AND codigo_ine = '06051';
UPDATE puntuaciones SET puntuacion = 55 WHERE categoria='TurismoRural' AND codigo_ine = '06042';
UPDATE puntuaciones SET puntuacion = 50 WHERE categoria='TurismoRural' AND codigo_ine = '06062';
UPDATE puntuaciones SET puntuacion = 40 WHERE categoria='TurismoRural' AND codigo_ine = '06123';
UPDATE puntuaciones SET puntuacion = 65 WHERE categoria='TurismoRural' AND codigo_ine = '24106';
UPDATE puntuaciones SET puntuacion = 40 WHERE categoria='TurismoRural' AND codigo_ine = '24901';
UPDATE puntuaciones SET puntuacion = 35 WHERE categoria='TurismoRural' AND codigo_ine = '24101';
UPDATE puntuaciones SET puntuacion = 63 WHERE categoria='TurismoRural' AND codigo_ine = '42218';
UPDATE puntuaciones SET puntuacion = 58 WHERE categoria='TurismoRural' AND codigo_ine = '42162';
UPDATE puntuaciones SET puntuacion = 52 WHERE categoria='TurismoRural' AND codigo_ine = '42103';
UPDATE puntuaciones SET puntuacion = 35 WHERE categoria='TurismoRural' AND codigo_ine = '42076';
UPDATE puntuaciones SET puntuacion = 55 WHERE categoria='TurismoRural' AND codigo_ine = '05132';
UPDATE puntuaciones SET puntuacion = 45 WHERE categoria='TurismoRural' AND codigo_ine = '05163';
UPDATE puntuaciones SET puntuacion = 38 WHERE categoria='TurismoRural' AND codigo_ine = '05054';
UPDATE puntuaciones SET puntuacion = 50 WHERE categoria='TurismoRural' AND codigo_ine = '40208';
UPDATE puntuaciones SET puntuacion = 45 WHERE categoria='TurismoRural' AND codigo_ine = '40057';
UPDATE puntuaciones SET puntuacion = 48 WHERE categoria='TurismoRural' AND codigo_ine = '48001';
UPDATE puntuaciones SET puntuacion = 40 WHERE categoria='TurismoRural' AND codigo_ine = '49121';
UPDATE puntuaciones SET puntuacion = 65 WHERE categoria='TurismoRural' AND codigo_ine = '23009';
UPDATE puntuaciones SET puntuacion = 58 WHERE categoria='TurismoRural' AND codigo_ine = '50069';
UPDATE puntuaciones SET puntuacion = 48 WHERE categoria='TurismoRural' AND codigo_ine = '50267';
UPDATE puntuaciones SET puntuacion = 40 WHERE categoria='TurismoRural' AND codigo_ine = '50165';
UPDATE puntuaciones SET puntuacion = 45 WHERE categoria='TurismoRural' AND codigo_ine = '43157';
UPDATE puntuaciones SET puntuacion = 60 WHERE categoria='TurismoRural' AND codigo_ine = '12057';
UPDATE puntuaciones SET puntuacion = 52 WHERE categoria='TurismoRural' AND codigo_ine = '46099';
UPDATE puntuaciones SET puntuacion = 45 WHERE categoria='TurismoRural' AND codigo_ine = '46247';
UPDATE puntuaciones SET puntuacion = 64 WHERE categoria='TurismoRural' AND codigo_ine = '03075';
UPDATE puntuaciones SET puntuacion = 52 WHERE categoria='TurismoRural' AND codigo_ine = '30034';
UPDATE puntuaciones SET puntuacion = 48 WHERE categoria='TurismoRural' AND codigo_ine = '30011';
UPDATE puntuaciones SET puntuacion = 64 WHERE categoria='TurismoRural' AND codigo_ine = '19311';
UPDATE puntuaciones SET puntuacion = 62 WHERE categoria='TurismoRural' AND codigo_ine = '18184';
UPDATE puntuaciones SET puntuacion = 58 WHERE categoria='TurismoRural' AND codigo_ine = '18070';
UPDATE puntuaciones SET puntuacion = 56 WHERE categoria='TurismoRural' AND codigo_ine = '18168';
UPDATE puntuaciones SET puntuacion = 54 WHERE categoria='TurismoRural' AND codigo_ine = '18132';
UPDATE puntuaciones SET puntuacion = 49 WHERE categoria='TurismoRural' AND codigo_ine = '18123';
UPDATE puntuaciones SET puntuacion = 46 WHERE categoria='TurismoRural' AND codigo_ine = '18033';
UPDATE puntuaciones SET puntuacion = 43 WHERE categoria='TurismoRural' AND codigo_ine = '18030';
UPDATE puntuaciones SET puntuacion = 40 WHERE categoria='TurismoRural' AND codigo_ine = '18035';
UPDATE puntuaciones SET puntuacion = 65 WHERE categoria='TurismoRural' AND codigo_ine = '24004';
UPDATE puntuaciones SET puntuacion = 62 WHERE categoria='TurismoRural' AND codigo_ine = '23019';
UPDATE puntuaciones SET puntuacion = 57 WHERE categoria='TurismoRural' AND codigo_ine = '23065';
UPDATE puntuaciones SET puntuacion = 54 WHERE categoria='TurismoRural' AND codigo_ine = '24016';
UPDATE puntuaciones SET puntuacion = 51 WHERE categoria='TurismoRural' AND codigo_ine = '23903';
UPDATE puntuaciones SET puntuacion = 45 WHERE categoria='TurismoRural' AND codigo_ine = '24001';
UPDATE puntuaciones SET puntuacion = 42 WHERE categoria='TurismoRural' AND codigo_ine = '23018';
UPDATE puntuaciones SET puntuacion = 35 WHERE categoria='TurismoRural' AND codigo_ine = '23029';
UPDATE puntuaciones SET puntuacion = 59 WHERE categoria='TurismoRural' AND codigo_ine = '29040';
UPDATE puntuaciones SET puntuacion = 54 WHERE categoria='TurismoRural' AND codigo_ine = '29033';
UPDATE puntuaciones SET puntuacion = 51 WHERE categoria='TurismoRural' AND codigo_ine = '29061';
UPDATE puntuaciones SET puntuacion = 48 WHERE categoria='TurismoRural' AND codigo_ine = '29036';
UPDATE puntuaciones SET puntuacion = 45 WHERE categoria='TurismoRural' AND codigo_ine = '29087';
UPDATE puntuaciones SET puntuacion = 36 WHERE categoria='TurismoRural' AND codigo_ine = '29065';
UPDATE puntuaciones SET puntuacion = 35 WHERE categoria='TurismoRural' AND codigo_ine = '29077';
UPDATE puntuaciones SET puntuacion = 65 WHERE categoria='TurismoRural' AND codigo_ine = '24106';
UPDATE puntuaciones SET puntuacion = 59 WHERE categoria='TurismoRural' AND codigo_ine = '24901';
UPDATE puntuaciones SET puntuacion = 50 WHERE categoria='TurismoRural' AND codigo_ine = '24145';
UPDATE puntuaciones SET puntuacion = 44 WHERE categoria='TurismoRural' AND codigo_ine = '24202';
UPDATE puntuaciones SET puntuacion = 63 WHERE categoria='TurismoRural' AND codigo_ine = '42218';
UPDATE puntuaciones SET puntuacion = 61 WHERE categoria='TurismoRural' AND codigo_ine = '42103';
UPDATE puntuaciones SET puntuacion = 58 WHERE categoria='TurismoRural' AND codigo_ine = '42076';
UPDATE puntuaciones SET puntuacion = 43 WHERE categoria='TurismoRural' AND codigo_ine = '42097';
UPDATE puntuaciones SET puntuacion = 40 WHERE categoria='TurismoRural' AND codigo_ine = '42164';
UPDATE puntuaciones SET puntuacion = 37 WHERE categoria='TurismoRural' AND codigo_ine = '42085';
UPDATE puntuaciones SET puntuacion = 35 WHERE categoria='TurismoRural' AND codigo_ine = '09905';
UPDATE puntuaciones SET puntuacion = 65 WHERE categoria='TurismoRural' AND codigo_ine = '23009';
UPDATE puntuaciones SET puntuacion = 52 WHERE categoria='TurismoRural' AND codigo_ine = '12057';
UPDATE puntuaciones SET puntuacion = 60 WHERE categoria='TurismoRural' AND codigo_ine = '03006';
UPDATE puntuaciones SET puntuacion = 57 WHERE categoria='TurismoRural' AND codigo_ine = '03129';
UPDATE puntuaciones SET puntuacion = 54 WHERE categoria='TurismoRural' AND codigo_ine = '03112';
UPDATE puntuaciones SET puntuacion = 48 WHERE categoria='TurismoRural' AND codigo_ine = '03124';
UPDATE puntuaciones SET puntuacion = 65 WHERE categoria='TurismoRural' AND codigo_ine = '10024';
UPDATE puntuaciones SET puntuacion = 62 WHERE categoria='TurismoRural' AND codigo_ine = '10080';
UPDATE puntuaciones SET puntuacion = 60 WHERE categoria='TurismoRural' AND codigo_ine = '10111';
UPDATE puntuaciones SET puntuacion = 57 WHERE categoria='TurismoRural' AND codigo_ine = '10100';
UPDATE puntuaciones SET puntuacion = 54 WHERE categoria='TurismoRural' AND codigo_ine = '10060';
UPDATE puntuaciones SET puntuacion = 51 WHERE categoria='TurismoRural' AND codigo_ine = '10029';
UPDATE puntuaciones SET puntuacion = 48 WHERE categoria='TurismoRural' AND codigo_ine = '10050';
UPDATE puntuaciones SET puntuacion = 42 WHERE categoria='TurismoRural' AND codigo_ine = '10079';
UPDATE puntuaciones SET puntuacion = 64 WHERE categoria='TurismoRural' AND codigo_ine = '06051';
UPDATE puntuaciones SET puntuacion = 61 WHERE categoria='TurismoRural' AND codigo_ine = '06042';
UPDATE puntuaciones SET puntuacion = 59 WHERE categoria='TurismoRural' AND codigo_ine = '06062';
UPDATE puntuaciones SET puntuacion = 53 WHERE categoria='TurismoRural' AND codigo_ine = '06123';
UPDATE puntuaciones SET puntuacion = 50 WHERE categoria='TurismoRural' AND codigo_ine = '06036';
UPDATE puntuaciones SET puntuacion = 46 WHERE categoria='TurismoRural' AND codigo_ine = '06005';
UPDATE puntuaciones SET puntuacion = 38 WHERE categoria='TurismoRural' AND codigo_ine = '06102';
UPDATE puntuaciones SET puntuacion = 58 WHERE categoria='TurismoRural' AND codigo_ine = '45159';
UPDATE puntuaciones SET puntuacion = 60 WHERE categoria='TurismoRural' AND codigo_ine = '50073';
UPDATE puntuaciones SET puntuacion = 53 WHERE categoria='TurismoRural' AND codigo_ine = '50165';
UPDATE puntuaciones SET puntuacion = 35 WHERE categoria='TurismoRural' AND codigo_ine = '50069';

-- Actualizar why_json
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Acceso al paraje natural de | Acceso al paraje natural de') WHERE codigo_ine = '24004';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Desfiladero de Puerta | Desfiladero de Puerta') WHERE codigo_ine = '23019';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Piscinas naturales de Amurjo en el | Piscinas naturales de Amurjo en el') WHERE codigo_ine = '23065';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Pequeñas dehesas de la Sierra de | Pequeñas dehesas de la Sierra de') WHERE codigo_ine = '24016';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Casas cueva en el altiplano y | Casas cueva en el altiplano y') WHERE codigo_ine = '18045';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Senderos fluviales del río Aguas | Senderos fluviales del río Aguas') WHERE codigo_ine = '18070';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Entorno del embalse y caminos de | Entorno del embalse y caminos de') WHERE codigo_ine = '18168';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Proyecto etnográfico alpujarreño | Proyecto etnográfico alpujarreño') WHERE codigo_ine = '18176';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Ruta del escarabajo y pinturas | Ruta del escarabajo y pinturas') WHERE codigo_ine = '18132';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Acceso secundario al Bosque de las | Acceso secundario al Bosque de las') WHERE codigo_ine = '18123';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Falda de la Sierra de | Falda de la Sierra de') WHERE codigo_ine = '29040';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Acceso al puente | Acceso al puente') WHERE codigo_ine = '29033';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Manantiales de agua limpia del río | Manantiales de agua limpia del río') WHERE codigo_ine = '29061';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Aguas termales azufradas de | Aguas termales azufradas de') WHERE codigo_ine = '29036';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Entorno del Parque de Tejeda y | Entorno del Parque de Tejeda y') WHERE codigo_ine = '29087';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Castillo e itinerario del | Castillo e itinerario del') WHERE codigo_ine = '41080';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Dehesas de encinar maduro del | Dehesas de encinar maduro del') WHERE codigo_ine = '40001';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Sierra alta, dehesas y | Sierra alta, dehesas y') WHERE codigo_ine = '41048';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Senderos fluviales del arroyo de | Senderos fluviales del arroyo de') WHERE codigo_ine = '41073';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Embalses de | Embalses de') WHERE codigo_ine = '41078';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Termalismo romano | Termalismo romano') WHERE codigo_ine = '10024';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Valle del Ambroz profundo y | Valle del Ambroz profundo y') WHERE codigo_ine = '10080';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Garganta de Alardos y | Garganta de Alardos y') WHERE codigo_ine = '10111';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Arquitectura señorial de piedra de | Arquitectura señorial de piedra de') WHERE codigo_ine = '10100';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Cuevas kársticas calizas y | Cuevas kársticas calizas y') WHERE codigo_ine = '10060';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Geoparque Villuercas alto y | Geoparque Villuercas alto y') WHERE codigo_ine = '10029';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Tres culturas e interior | Tres culturas e interior') WHERE codigo_ine = '10050';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Capital de la | Capital de la') WHERE codigo_ine = '06051';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Isla y playa fluvial del Gran Lago de | Isla y playa fluvial del Gran Lago de') WHERE codigo_ine = '06042';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Cortados y | Cortados y') WHERE codigo_ine = '06062';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Capital del corcho | Capital del corcho') WHERE codigo_ine = '06123';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Desfiladero de los | Desfiladero de los') WHERE codigo_ine = '24106';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Puertos de montaña centrales de | Puertos de montaña centrales de') WHERE codigo_ine = '24901';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Reserva de la Biosfera | Reserva de la Biosfera') WHERE codigo_ine = '24101';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Tierras altas sorianas húmedas de | Tierras altas sorianas húmedas de') WHERE codigo_ine = '42218';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Románico | Románico') WHERE codigo_ine = '42162';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Torres defensivas y | Torres defensivas y') WHERE codigo_ine = '42103';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Aislamiento geográfico profundo en la | Aislamiento geográfico profundo en la') WHERE codigo_ine = '42076';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Castillo de los Duques de | Castillo de los Duques de') WHERE codigo_ine = '05132';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Puentes medievales y dehesas | Puentes medievales y dehesas') WHERE codigo_ine = '05163';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Gargantas de la vertiente sur | Gargantas de la vertiente sur') WHERE codigo_ine = '05054';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Castillo e iglesia integrados en la | Castillo e iglesia integrados en la') WHERE codigo_ine = '40208';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Castillo mudéjar y masas forestales | Castillo mudéjar y masas forestales') WHERE codigo_ine = '40057';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Comarca de Aliste frontera | Comarca de Aliste frontera') WHERE codigo_ine = '48001';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Torres románicas templarias de | Torres románicas templarias de') WHERE codigo_ine = '49121';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Selva de Oza y arquitectura del | Selva de Oza y arquitectura del') WHERE codigo_ine = '23009';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Cara oculta meridional indómita del | Cara oculta meridional indómita del') WHERE codigo_ine = '50069';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Conjunto gótico medieval de las | Conjunto gótico medieval de las') WHERE codigo_ine = '50267';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Pesca deportiva de interior y | Pesca deportiva de interior y') WHERE codigo_ine = '50165';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Desfiladero de Fraguerau en el | Desfiladero de Fraguerau en el') WHERE codigo_ine = '43157';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Bosques de alcornoque sobre | Bosques de alcornoque sobre') WHERE codigo_ine = '12057';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Muela caliza vertical y | Muela caliza vertical y') WHERE codigo_ine = '46099';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Nacimiento del río Tuéjar y piscinas | Nacimiento del río Tuéjar y piscinas') WHERE codigo_ine = '46247';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Castillo e iglesia colgados sobre | Castillo e iglesia colgados sobre') WHERE codigo_ine = '03075';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Oasis morisco del río Segura, | Oasis morisco del río Segura,') WHERE codigo_ine = '30034';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Meandros del Segura inferior y | Meandros del Segura inferior y') WHERE codigo_ine = '30011';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Arquitectura negra | Arquitectura negra') WHERE codigo_ine = '19311';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Desfiladero calizo de | Desfiladero calizo de') WHERE codigo_ine = '18184';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Cañón del río Aguas Blancas, | Cañón del río Aguas Blancas,') WHERE codigo_ine = '18070';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Entorno forestal del embalse, | Entorno forestal del embalse,') WHERE codigo_ine = '18168';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Ruta de las Pasarelas sobre el río | Ruta de las Pasarelas sobre el río') WHERE codigo_ine = '18132';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Acceso norte de alta montaña al | Acceso norte de alta montaña al') WHERE codigo_ine = '18123';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Trazado urbano bereber intacto | Trazado urbano bereber intacto') WHERE codigo_ine = '18033';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Nacimiento del río Guadalfeo | Nacimiento del río Guadalfeo') WHERE codigo_ine = '18030';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Valle de la Alpujarra media, | Valle de la Alpujarra media,') WHERE codigo_ine = '18035';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Desfiladero norte de Sierra | Desfiladero norte de Sierra') WHERE codigo_ine = '24004';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Parque de Sierra | Parque de Sierra') WHERE codigo_ine = '23019';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Complejo recreativo fluvial de las | Complejo recreativo fluvial de las') WHERE codigo_ine = '23065';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Pequeñas dehesas ganaderas de | Pequeñas dehesas ganaderas de') WHERE codigo_ine = '24016';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Campiña baja del Guadalquivir, | Campiña baja del Guadalquivir,') WHERE codigo_ine = '23903';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Olivares de pendiente | Olivares de pendiente') WHERE codigo_ine = '24001';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Valle del río Cambil, murallas de | Valle del río Cambil, murallas de') WHERE codigo_ine = '23018';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Pueblo colgado | Pueblo colgado') WHERE codigo_ine = '23029';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Falda norte de la Sierra de | Falda norte de la Sierra de') WHERE codigo_ine = '29040';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Acceso principal al | Acceso principal al') WHERE codigo_ine = '29033';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Manantiales y surgencias de agua | Manantiales y surgencias de agua') WHERE codigo_ine = '29061';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Aguas termales azufradas | Aguas termales azufradas') WHERE codigo_ine = '29036';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Vertiente norte del Parque de las | Vertiente norte del Parque de las') WHERE codigo_ine = '29087';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Valle del Genal central, rutas | Valle del Genal central, rutas') WHERE codigo_ine = '29065';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Bosque del cobre en la cabecera | Bosque del cobre en la cabecera') WHERE codigo_ine = '29077';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Desfiladero de los | Desfiladero de los') WHERE codigo_ine = '24106';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Puertos de montaña centrales de | Puertos de montaña centrales de') WHERE codigo_ine = '24901';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Valles glaciares llanos de | Valles glaciares llanos de') WHERE codigo_ine = '24145';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Reserva de la Biosfera de | Reserva de la Biosfera de') WHERE codigo_ine = '24202';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Tierras altas sorianas húmedas, | Tierras altas sorianas húmedas,') WHERE codigo_ine = '42218';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Torres defensivas | Torres defensivas') WHERE codigo_ine = '42103';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Aislamiento geográfico profundo de la | Aislamiento geográfico profundo de la') WHERE codigo_ine = '42076';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Colosal fortaleza califal medieval | Colosal fortaleza califal medieval') WHERE codigo_ine = '42097';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Bosques de pino | Bosques de pino') WHERE codigo_ine = '42164';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Dehesas ganaderas | Dehesas ganaderas') WHERE codigo_ine = '42085';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Cañones kársticos calizos | Cañones kársticos calizos') WHERE codigo_ine = '09905';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Selva de Oza, bosque atlántico | Selva de Oza, bosque atlántico') WHERE codigo_ine = '23009';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Corazón de la Sierra de Espadán, | Corazón de la Sierra de Espadán,') WHERE codigo_ine = '12057';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: El núcleo urbano más | El núcleo urbano más') WHERE codigo_ine = '03006';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Entorno del pantano histórico de Tibi | Entorno del pantano histórico de Tibi') WHERE codigo_ine = '03129';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Pasarela de madera aérea colgada | Pasarela de madera aérea colgada') WHERE codigo_ine = '03112';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Refugio de montaña a las faldas del | Refugio de montaña a las faldas del') WHERE codigo_ine = '03124';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Aguas termales | Aguas termales') WHERE codigo_ine = '10024';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Valle del Ambroz profundo, | Valle del Ambroz profundo,') WHERE codigo_ine = '10080';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Garganta fluvial de | Garganta fluvial de') WHERE codigo_ine = '10111';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Arquitectura señorial de piedra de | Arquitectura señorial de piedra de') WHERE codigo_ine = '10100';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Cuevas kársticas con | Cuevas kársticas con') WHERE codigo_ine = '10060';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Riscos de cuarcita del | Riscos de cuarcita del') WHERE codigo_ine = '10029';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Trazado urbano de las | Trazado urbano de las') WHERE codigo_ine = '10050';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Conjunto Histórico verato | Conjunto Histórico verato') WHERE codigo_ine = '10079';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Reserva de la | Reserva de la') WHERE codigo_ine = '06051';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Playa fluvial de interior con Bandera | Playa fluvial de interior con Bandera') WHERE codigo_ine = '06042';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Cortados | Cortados') WHERE codigo_ine = '06062';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Capital del | Capital del') WHERE codigo_ine = '06123';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Altiplano estepario de la comarca | Altiplano estepario de la comarca') WHERE codigo_ine = '06036';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Dehesas ganaderas de Sierra | Dehesas ganaderas de Sierra') WHERE codigo_ine = '06005';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Colosal fortaleza | Colosal fortaleza') WHERE codigo_ine = '06102';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Cuenca baja del río Tiétar, | Cuenca baja del río Tiétar,') WHERE codigo_ine = '45159';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Mares de viñedos viejos de la | Mares de viñedos viejos de la') WHERE codigo_ine = '50073';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Gran nudo fluvial del | Gran nudo fluvial del') WHERE codigo_ine = '50165';
UPDATE municipios SET why_json = json_array('🏡 TURISMO RURAL: Cara oculta e indómita meridional | Cara oculta e indómita meridional') WHERE codigo_ine = '50069';