-- Castillos extremadura_rioja

UPDATE puntuaciones SET puntuacion=96 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALBURQUERQUE' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=95 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='BADAJOZ' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=95 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='OLIVENZA' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=94 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='JEREZ DE LOS CABALLEROS' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=94 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MEDELLÍN' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=93 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='FERIA' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=93 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ZAFRA' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=92 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PUEBLA DE ALCOCER' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=91 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='FREGENAL DE LA SIERRA' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=91 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VILLALBA DE LOS BARROS' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=89 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='BURGUILLOS DEL CERRO' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=84 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALCONCHEL' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=82 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='HERRERA DEL DUQUE' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CABEZA DEL BUEY' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ORELLANA LA VIEJA' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=70 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='LLERENA' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=68 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='AZUAGA' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=58 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='SALVALEÓN' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=55 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MONESTERIO' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=52 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CASTUERA (ENTORNO RURAL DE LA' AND UPPER(TRIM(provincia))='BADAJOZ') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=100 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=100 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=96 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ESCORCA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=95 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALARÓ' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=95 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=94 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CAPDEPERA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=94 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='FERROL' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=93 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='FELANITX' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=92 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='FELANITX' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=92 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=91 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALCÚDIA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=91 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=91 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=91 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=90 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VIMIANZO' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=89 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ARTA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=89 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=88 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MOECHE' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=88 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=86 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=85 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=85 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=85 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PONTEDEUME' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=84 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='FELANITX' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=82 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ESCORCA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=82 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=80 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CIUTADELLA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=80 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=78 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CORCUBIÓN' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=75 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CEE' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=75 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=68 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ANDRATX' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=52 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='NEDA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=50 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALMA' AND UPPER(TRIM(provincia))='BALEARES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=96 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='TRUJILLO' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=94 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='GRANADILLA (MUNICIPALIDAD DE ZARZA DE' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=93 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MONTÁNCHEZ' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=92 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CÁCERES' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=91 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CORIA' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=91 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='TREVEJO' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=90 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='JARANDILLA DE LA VERA' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=89 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='JARANDILLA DE LA VERA' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=88 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALCÁNTARA' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=86 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='BROZAS' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=85 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='BROZAS' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=84 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PORTEZUELO' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=82 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ARROYOMOLINOS' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PLASENCIA' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=65 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALBURQUERQUE RURAL (ÁREA LIMÍTROFE' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=58 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='SEGURA DE TORO' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=54 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALBALÁ' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=52 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VALVERDE DEL FRESNO' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=50 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VILLANUEVA DE LA VERA' AND UPPER(TRIM(provincia))='CÁCERES') AND categoria='castillos';