-- Castillos castilla_leon

UPDATE puntuaciones SET puntuacion=98 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='FRÍAS' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=93 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PANCORBO' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=92 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MEDINA DE POMAR' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=91 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='BURGOS' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=89 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CASTROJERIZ' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=88 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='POZA DE LA SAL' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=86 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='COVARRUBIAS' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=85 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='SOTOPALACIOS (MERINDAD DE RÍO' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=84 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='OLMILLOS DE SASEMÓN (PEDANÍA DE' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=82 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PANCORBO' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ESPINOSA DE LOS MONTEROS' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PANCORBO' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=75 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CASTROJERIZ' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=74 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='TORREGALINDO' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=72 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VALLE DE MENA' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=68 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PUENTEDEY' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=65 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ESPINOSA DE LOS MONTEROS' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=58 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='SAN ZADORNIL' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=55 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALBICES (PEDANÍA DE VILLAQUIRÁN DE LOS' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=52 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='QUINTANILLA DE SAN GARCÍA' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=50 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VILLAQUIRÁN DE LOS INFANTES' AND UPPER(TRIM(provincia))='BURGOS') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=99 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PONFERRADA' AND UPPER(TRIM(provincia))='LEÓN') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=96 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VALENCIA DE DON JUAN' AND UPPER(TRIM(provincia))='LEÓN') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=94 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='GRAJAL DE CAMPOS' AND UPPER(TRIM(provincia))='LEÓN') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=93 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PRIARANZA DEL BIERZO' AND UPPER(TRIM(provincia))='LEÓN') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=91 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='LEÓN' AND UPPER(TRIM(provincia))='LEÓN') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=85 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='LAGUNA DE NEGRILLOS' AND UPPER(TRIM(provincia))='LEÓN') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=82 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CORULLÓN' AND UPPER(TRIM(provincia))='LEÓN') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALIJA DEL INFANTADO' AND UPPER(TRIM(provincia))='LEÓN') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=74 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALMANZA' AND UPPER(TRIM(provincia))='LEÓN') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=55 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CEBRONES DEL ÓRBIGO (ÁREA DE' AND UPPER(TRIM(provincia))='LEÓN') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=50 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MAQUEDA DE CAMPOS (PEDANÍA DE' AND UPPER(TRIM(provincia))='LEÓN') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=95 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='AMPUDIA' AND UPPER(TRIM(provincia))='PALENCIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=92 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='FUENTES DE VALDEPERO' AND UPPER(TRIM(provincia))='PALENCIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=91 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='BELMONTE DE CAMPOS' AND UPPER(TRIM(provincia))='PALENCIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=89 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='AGUILAR DE CAMPOO' AND UPPER(TRIM(provincia))='PALENCIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=88 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MONZÓN DE CAMPOS' AND UPPER(TRIM(provincia))='PALENCIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ASTUDILLO' AND UPPER(TRIM(provincia))='PALENCIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=68 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PALENZUELA' AND UPPER(TRIM(provincia))='PALENCIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=58 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALBA DE TORMES (SALAMANCA' AND UPPER(TRIM(provincia))='PALENCIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=55 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CASTROVIEJO' AND UPPER(TRIM(provincia))='PALENCIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=52 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MEDINA DEL CAMPO RURAL (VALLADOLID' AND UPPER(TRIM(provincia))='PALENCIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=96 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CIUDAD RODRIGO' AND UPPER(TRIM(provincia))='SALAMANCA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=92 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='SAN FELICES DE LOS GALLEGOS' AND UPPER(TRIM(provincia))='SALAMANCA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=91 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALBA DE TORMES' AND UPPER(TRIM(provincia))='SALAMANCA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=90 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MONTEMAYOR DEL RÍO' AND UPPER(TRIM(provincia))='SALAMANCA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=89 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='LEDESMA' AND UPPER(TRIM(provincia))='SALAMANCA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=88 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MONTEMAYOR DEL RÍO' AND UPPER(TRIM(provincia))='SALAMANCA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=80 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='SOBRADILLO' AND UPPER(TRIM(provincia))='SALAMANCA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=55 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALDEADÁVILA DE LA RIBERA (ARRIBES DEL' AND UPPER(TRIM(provincia))='SALAMANCA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=100 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='SEGOVIA' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=99 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='COCA' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=95 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PEDRAZA' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=94 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='TURÉGANO' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=92 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CUÉLLAR' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=82 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='SEPÚLVEDA' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='AYLLÓN' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='SEGOVIA' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=75 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MADERUELO' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=74 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VALDEPRADOS' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=65 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='SEPÚLVEDA' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=62 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='FRESNO DE CANTESPINO' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=60 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='OREJANA' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=58 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CONDADO DE CASTRALVO (PEDANÍA DE' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=55 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CASTILLEJO DE MESLEÓN' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=55 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VILLAVERDE DE ÍSCAR' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=54 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ARCONES' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=54 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PRÁDENA' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=52 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CASLA' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=52 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VEGANZONES' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=50 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VALLE DE TABLADILLO' AND UPPER(TRIM(provincia))='SEGOVIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=100 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='GORMAZ' AND UPPER(TRIM(provincia))='SORIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=96 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='BERLANGA DE DUERO' AND UPPER(TRIM(provincia))='SORIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=93 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALMENAR DE SORIA' AND UPPER(TRIM(provincia))='SORIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=90 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VOZMEDIANO' AND UPPER(TRIM(provincia))='SORIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=89 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='RELLO' AND UPPER(TRIM(provincia))='SORIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=88 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='GORMAZ' AND UPPER(TRIM(provincia))='SORIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=86 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ALMAZÁN' AND UPPER(TRIM(provincia))='SORIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=85 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='RELLO' AND UPPER(TRIM(provincia))='SORIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=84 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ÁGREDA' AND UPPER(TRIM(provincia))='SORIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=82 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='BERLANGA DE DUERO' AND UPPER(TRIM(provincia))='SORIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MEDINACELI' AND UPPER(TRIM(provincia))='SORIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=72 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='DEZA' AND UPPER(TRIM(provincia))='SORIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=70 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='SORIA' AND UPPER(TRIM(provincia))='SORIA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=100 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MEDINA DEL CAMPO' AND UPPER(TRIM(provincia))='VALLADOLID') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=99 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MEDINA DEL CAMPO' AND UPPER(TRIM(provincia))='VALLADOLID') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=95 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='TORRELOBATÓN' AND UPPER(TRIM(provincia))='VALLADOLID') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=93 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='SIMANCAS' AND UPPER(TRIM(provincia))='VALLADOLID') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=92 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ENCINAS DE ESGUEVA' AND UPPER(TRIM(provincia))='VALLADOLID') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=89 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VILLALONSO' AND UPPER(TRIM(provincia))='VALLADOLID') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=88 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PORTILLO' AND UPPER(TRIM(provincia))='VALLADOLID') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=86 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='TIEDRA' AND UPPER(TRIM(provincia))='VALLADOLID') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=85 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ISCAR' AND UPPER(TRIM(provincia))='VALLADOLID') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=84 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ENCINAS DE ESGUEVA' AND UPPER(TRIM(provincia))='VALLADOLID') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='TRIGUEROS DEL VALLE' AND UPPER(TRIM(provincia))='VALLADOLID') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=70 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CASTROMONTE' AND UPPER(TRIM(provincia))='VALLADOLID') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=55 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='SAN JOSÉ DE VALLE' AND UPPER(TRIM(provincia))='VALLADOLID') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=95 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='PUEBLA DE SANABRIA' AND UPPER(TRIM(provincia))='ZAMORA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=94 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ZAMORA' AND UPPER(TRIM(provincia))='ZAMORA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=93 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VILLALONSO' AND UPPER(TRIM(provincia))='ZAMORA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=91 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='BENAVENTE' AND UPPER(TRIM(provincia))='ZAMORA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=90 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='TORO' AND UPPER(TRIM(provincia))='ZAMORA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=89 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='CASTROTORAFE (MUNICIPALIDAD DE SAN' AND UPPER(TRIM(provincia))='ZAMORA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=76 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MOMBUEY' AND UPPER(TRIM(provincia))='ZAMORA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=74 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='FERMOSELLE' AND UPPER(TRIM(provincia))='ZAMORA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=72 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='VOZMEDIANO' AND UPPER(TRIM(provincia))='ZAMORA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=52 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='FUENTESÁUCO' AND UPPER(TRIM(provincia))='ZAMORA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=100 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ÁVILA' AND UPPER(TRIM(provincia))='ÁVILA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=95 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MOMBELTRÁN' AND UPPER(TRIM(provincia))='ÁVILA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=93 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ARÉVALO' AND UPPER(TRIM(provincia))='ÁVILA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=91 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ARENAS DE SAN PEDRO' AND UPPER(TRIM(provincia))='ÁVILA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=89 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='EL BARCO DE ÁVILA' AND UPPER(TRIM(provincia))='ÁVILA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=82 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='NAVAS DEL MARQUÉS' AND UPPER(TRIM(provincia))='ÁVILA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=78 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='MOMBELTRÁN' AND UPPER(TRIM(provincia))='ÁVILA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=72 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ÁVILA' AND UPPER(TRIM(provincia))='ÁVILA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=55 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='ÁVILA' AND UPPER(TRIM(provincia))='ÁVILA') AND categoria='castillos';
UPDATE puntuaciones SET puntuacion=50 WHERE codigo_ine IN (SELECT codigo_ine FROM municipios WHERE UPPER(TRIM(nombre))='SANTIAGO DEL COLLADO' AND UPPER(TRIM(provincia))='ÁVILA') AND categoria='castillos';