-- 0224: Municipios costeros que faltaban en la BD (para mostrar sus playas y el ranking).
-- Solo nombre/provincia/comunidad (el PDF de playas no trae coordenadas ni población).
-- Limpieza previa (idempotente): quita datos de playa y municipios sintéticos 9xxxx.
DELETE FROM entidades WHERE fuente='inventario_playas_pdf';
DELETE FROM puntuaciones WHERE categoria='Playas';
DELETE FROM municipios WHERE codigo_ine LIKE '9%';

INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90001','Ares','A Coruña','Galicia','ares');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90002','Arteixo','A Coruña','Galicia','arteixo');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90003','Bergondo','A Coruña','Galicia','bergondo');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90004','Cabana de Bergantiños','A Coruña','Galicia','cabana de bergantinos');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90005','Cabanas','A Coruña','Galicia','cabanas');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90006','Laxe','A Coruña','Galicia','laxe');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90007','Porto do Son','A Coruña','Galicia','porto do son');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90008','El Poble Nou de Benitatxell','Alicante','Comunitat Valenciana','el poble nou de benitatxell');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90009','L''Alfàs del Pi','Alicante','Comunitat Valenciana','l''alfas del pi');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90010','Caravia','Asturias','Asturias','caravia');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90011','Carreño','Asturias','Asturias','carreno');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90012','Castrillón','Asturias','Asturias','castrillon');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90013','Castropol','Asturias','Asturias','castropol');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90014','Coaña','Asturias','Asturias','coana');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90015','Colunga','Asturias','Asturias','colunga');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90016','Alaior','Baleares','Islas Baleares','alaior');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90017','Andratx','Baleares','Islas Baleares','andratx');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90018','Calvià','Baleares','Islas Baleares','calvia');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90019','Capdepera','Baleares','Islas Baleares','capdepera');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90020','Deià','Baleares','Islas Baleares','deia');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90021','Maó-Mahón','Baleares','Islas Baleares','mao-mahon');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90022','Sant Joan de Labritja','Baleares','Islas Baleares','sant joan de labritja');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90023','Sant Josep de sa Talaia','Baleares','Islas Baleares','sant josep de sa talaia');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90024','Badalona','Barcelona','Cataluña','badalona');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90025','Caldes d''Estrac','Barcelona','Cataluña','caldes d''estrac');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90026','Vilanova i la Geltrú','Barcelona','Cataluña','vilanova i la geltru');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90027','Alfoz de Lloredo','Cantabria','Cantabria','alfoz de lloredo');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90028','Arnuero','Cantabria','Cantabria','arnuero');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90029','Bareyo','Cantabria','Cantabria','bareyo');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90030','El Astillero','Cantabria','Cantabria','el astillero');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90031','Barbate','Cádiz','Andalucía','barbate');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90032','Chipiona','Cádiz','Andalucía','chipiona');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90033','Blanes','Girona','Cataluña','blanes');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90034','Calonge i Sant Antoni','Girona','Cataluña','calonge i sant antoni');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90035','Castell-Platja d''Aro','Girona','Cataluña','castell-platja d''aro');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90036','El Port de la Selva','Girona','Cataluña','el port de la selva');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90037','Albuñol','Granada','Andalucía','albunol');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90038','Gualchos / Castell de Ferro','Granada','Andalucía','gualchos / castell de ferro');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90039','Mutriku','Guipúzcoa','País Vasco','mutriku');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90040','Barreiros','Lugo','Galicia','barreiros');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90041','Cervo','Lugo','Galicia','cervo');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90042','Cangas do Morrazo','Pontevedra','Galicia','cangas do morrazo');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90043','O Rosal','Pontevedra','Galicia','o rosal');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90044','Poio','Pontevedra','Galicia','poio');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90045','Arona (Tenerife)','Santa Cruz de Tenerife','Canarias','arona (tenerife)');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90046','Breña Baja (La Palma)','Santa Cruz de Tenerife','Canarias','brena baja (la palma)');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90047','Alcanar','Tarragona','Cataluña','alcanar');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90048','Altafulla','Tarragona','Cataluña','altafulla');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90049','L''Ametlla de Mar','Tarragona','Cataluña','l''ametlla de mar');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90050','Mont-roig del Camp','Tarragona','Cataluña','mont-roig del camp');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90051','Vinyols i els Arcs','Tarragona','Cataluña','vinyols i els arcs');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90052','El Perelló','Valencia','Comunitat Valenciana','el perello');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90053','Puçol','Valencia','Comunitat Valenciana','pucol');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90054','Xeraco','Valencia','Comunitat Valenciana','xeraco');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90055','Bakio','Vizcaya','País Vasco','bakio');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90056','Muskiz','Vizcaya','País Vasco','muskiz');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90057','Plentzia','Vizcaya','País Vasco','plentzia');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90058','Santurtzi','Vizcaya','País Vasco','santurtzi');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90059','Sukarrieta','Vizcaya','País Vasco','sukarrieta');
INSERT OR IGNORE INTO municipios (codigo_ine,nombre,provincia,comunidad,nombre_search) VALUES ('90060','Zierbena','Vizcaya','País Vasco','zierbena');
