-- 0328 Hoteles con encanto: miembros de Relais & Châteaux España (8, municipio verificado web oficial + prensa).
DELETE FROM entidades WHERE fuente='hoteles_encanto' AND nivel_sello='Relais & Châteaux';

INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('29903','alojamiento','Finca La Donaira','Miembro de Relais & Châteaux · hotel con encanto de alta gama','hoteles_encanto','Hotel_Encanto','Relais & Châteaux');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('90016','alojamiento','Cap Menorca Relais & Châteaux','Miembro de Relais & Châteaux · hotel con encanto de alta gama','hoteles_encanto','Hotel_Encanto','Relais & Châteaux');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('07006','alojamiento','Faustino Gran Relais & Châteaux','Miembro de Relais & Châteaux · hotel con encanto de alta gama','hoteles_encanto','Hotel_Encanto','Relais & Châteaux');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('26061','alojamiento','Echaurren','Miembro de Relais & Châteaux · hotel con encanto de alta gama','hoteles_encanto','Hotel_Encanto','Relais & Châteaux');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('20069','alojamiento','Akelarre – Hotel','Miembro de Relais & Châteaux · hotel con encanto de alta gama','hoteles_encanto','Hotel_Encanto','Relais & Châteaux');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('90044','alojamiento','Pepe Vieira Restaurante & Hotel','Miembro de Relais & Châteaux · hotel con encanto de alta gama','hoteles_encanto','Hotel_Encanto','Relais & Châteaux');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('43154','alojamiento','Gran Hotel Mas d''en Bruno','Miembro de Relais & Châteaux · hotel con encanto de alta gama','hoteles_encanto','Hotel_Encanto','Relais & Châteaux');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('39056','alojamiento','Helguera Palacio Boutique','Miembro de Relais & Châteaux · hotel con encanto de alta gama','hoteles_encanto','Hotel_Encanto','Relais & Châteaux');
