-- 0343 Cuevas turísticas: entidades desde ACTE (Asociación de Cuevas Turísticas Españolas).
-- fuente=cuevas, tipo=cueva. 34 cuevas/minas turísticas.
DELETE FROM entidades WHERE fuente='cuevas';

INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('03046','cueva','Cueva Del Canelobre','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('04021','cueva','Geoda de Pulpí y mina Rica','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('06053','cueva','Mina de la Jayona','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('06055','cueva','Cuevas de Fuentes de León','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('09215','cueva','Cueva de Ojo Guareña','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('10060','cueva','Cueva del Castañar','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('10109','cueva','Mina Costanaza','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('12126','cueva','Rio Subterráneo de San José','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('14075','cueva','Cueva de los Murciélagos','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('17003','cueva','Cueva del Yeso','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('21014','cueva','Cueva de Oñati - Arrikrutz','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('22003','cueva','Cuevas de Alájar','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('22004','cueva','Gruta de las Maravillas','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('22250','cueva','Cuevas de las Güixas','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('24194','cueva','Cueva de Valporquero','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('30013','cueva','Cueva de El Puerto','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('31144','cueva','Cueva de Mendukilo','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('33031','cueva','Mina de El Socavón Emilia','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('34135','cueva','Cueva de los Franceses','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('38006','cueva','Cueva del Viento','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('39056','cueva','Cueva del Castillo','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('39063','cueva','Cueva El Soplao','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('39076','cueva','Cueva de Altamira','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('43025','cueva','Cueva Meravelles','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('43120','cueva','Cueva de Garrofet','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('44151','cueva','Grutas de Cristal','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('46142','cueva','Cueva de Don Juan','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('48022','cueva','Cueva de Pozalagua','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('51001','cueva','Cueva del Águila','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('90022','cueva','Cova de Can Marçà','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('90391','cueva','Cueva de las Calaveras','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('90651','cueva','Cueva de Campanet','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('90825','cueva','Parque Minero de Almadén','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
INSERT OR REPLACE INTO entidades (codigo_ine,tipo,nombre,descripcion,fuente,sello_oficial,nivel_sello) VALUES ('90839','cueva','Minas de Santa Marta','Cueva o mina turística visitable, miembro de la Asociación de Cuevas Turísticas Españolas (ACTE).','cuevas','Cueva_ACTE','Cueva turística');
