-- 0443 auditoría Comunidad de Madrid
-- === md (capital 28079) ===
DELETE FROM entidades WHERE id=78726; -- Plaza Mayor Chinchon copia BIC 2 (queda 205)
DELETE FROM entidades WHERE id=78738; -- Plaza Mayor Chinchon copia BIC (queda 205)
DELETE FROM entidades WHERE id=93949; -- Plaza Mayor Chinchon copia monumentos (queda 205)
DELETE FROM entidades WHERE id=93955; -- Recinto amurallado Buitrago copia monumentos (queda BIC 78728)
DELETE FROM entidades WHERE id=93969; -- Plaza Mayor Colmenar copia monumentos (queda BIC 78731)
DELETE FROM entidades WHERE id=167170; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167172; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167173; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167174; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167175; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167176; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167177; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167178; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167179; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167180; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167181; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167182; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167183; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167184; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167185; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167186; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167187; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167188; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167189; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167190; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167191; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167192; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167193; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167194; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167195; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167196; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167197; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167198; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167199; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167200; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167201; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167202; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167203; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167204; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167205; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167206; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167207; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167208; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167209; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167210; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167211; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167212; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167213; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167214; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167215; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167216; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167217; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167218; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167219; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167220; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167221; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167222; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167223; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167224; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167225; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167226; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167227; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167228; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167229; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167230; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167231; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167232; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167233; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167234; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167235; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167236; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167237; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167238; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167239; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167240; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167241; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167242; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167243; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167244; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167245; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167246; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167247; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167248; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167249; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167250; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167251; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167252; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167253; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167254; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167255; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167256; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167257; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167258; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167259; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167260; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167261; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167262; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167263; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167264; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167265; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167266; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167267; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167268; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167269; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167270; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167271; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167272; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167273; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167274; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167275; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167276; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167277; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167278; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167279; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167280; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167281; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167282; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167283; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167284; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167285; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167286; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167287; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167288; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167289; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167290; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167291; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167292; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167293; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167294; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167295; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167296; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167297; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167298; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167299; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167300; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167301; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167302; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167303; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167304; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167305; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167306; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167307; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167308; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167309; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167310; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167311; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167312; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167313; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167314; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167315; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167316; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167317; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167318; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167319; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167320; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167321; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167322; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167323; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167324; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167325; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167326; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167327; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167328; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167329; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167330; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167331; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167332; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167333; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167334; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167335; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167336; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167337; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167338; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167339; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167340; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167341; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167342; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167343; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167344; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167345; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167347; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167348; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167349; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167350; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167351; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167352; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167353; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167354; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167355; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167356; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167357; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167358; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167359; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167360; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167361; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167362; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167363; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167364; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167365; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167366; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167367; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167368; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167369; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167370; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167371; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167372; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167373; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167374; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167375; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167376; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167377; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167378; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167379; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167380; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167381; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167382; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167383; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167384; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167385; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167386; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167387; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167388; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167389; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167390; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167391; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167392; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167393; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167394; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167395; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167396; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167397; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167398; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167399; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167400; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167401; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167402; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167403; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167404; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167405; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167406; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167407; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167408; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167409; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167410; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167411; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167412; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167413; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167414; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167415; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167416; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167417; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167418; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167419; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167420; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167421; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167422; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167423; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167424; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=167425; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=168944; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=168945; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=168946; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=168947; -- alojamiento urbano de la capital en turismo rural
DELETE FROM entidades WHERE id=173512; -- Bar El Cano dup OSM (queda El Cano con enye 173513)
DELETE FROM entidades WHERE id=182956; -- Parador de Alcala como religioso (queda hoteles_encanto 141660)
DELETE FROM entidades WHERE id=186389; -- Don Juan en Alcala copia en fiestas (queda festival 184055)
DELETE FROM entidades WHERE id=190276; -- calle/carrer como oleoturismo
DELETE FROM entidades WHERE id=190277; -- calle/carrer como oleoturismo
DELETE FROM entidades WHERE id=190278; -- calle/carrer como oleoturismo
DELETE FROM entidades WHERE id=190280; -- calle/carrer como oleoturismo
DELETE FROM entidades WHERE id=190281; -- calle/carrer como oleoturismo
DELETE FROM entidades WHERE id=190282; -- calle/carrer como oleoturismo
DELETE FROM entidades WHERE id=190283; -- calle/carrer como oleoturismo
DELETE FROM entidades WHERE id=190284; -- calle/carrer como oleoturismo
DELETE FROM entidades WHERE id=190285; -- calle/carrer como oleoturismo
DELETE FROM entidades WHERE id=190287; -- calle/carrer como oleoturismo
DELETE FROM entidades WHERE id=190290; -- calle/carrer como oleoturismo
DELETE FROM entidades WHERE id=78739; -- dup-ficha 29004: ya existe en 28027
DELETE FROM entidades WHERE id=80770; -- dup-ficha 29004: ya existe en 28027
DELETE FROM entidades WHERE id=80771; -- dup-ficha 29005: ya existe en 28038
UPDATE entidades SET codigo_ine='28052' WHERE id=205; -- movida de 29006
UPDATE entidades SET codigo_ine='28052' WHERE id=206; -- movida de 29006
DELETE FROM entidades WHERE id=80772; -- dup-ficha 29006: ya existe en 28052
DELETE FROM entidades WHERE id=80773; -- dup-ficha 29007: ya existe en 28045
DELETE FROM entidades WHERE id=80774; -- dup-ficha 29008: ya existe en 28054
DELETE FROM entidades WHERE id=80775; -- dup-ficha 29010: ya existe en 28058
DELETE FROM entidades WHERE id=80776; -- dup-ficha 29011: ya existe en 28065
DELETE FROM entidades WHERE id=80777; -- dup-ficha 29012: ya existe en 28074
DELETE FROM entidades WHERE id=80778; -- dup-ficha 29013: ya existe en 28087
DELETE FROM entidades WHERE id=78736; -- dup-ficha 29014: ya existe en 28079
DELETE FROM entidades WHERE id=78737; -- dup-ficha 29014: ya existe en 28079
DELETE FROM entidades WHERE id=80779; -- dup-ficha 29014: ya existe en 28079
UPDATE entidades SET codigo_ine='28079' WHERE id=141661; -- movida de 29014
UPDATE entidades SET codigo_ine='28079' WHERE id=141662; -- movida de 29014
DELETE FROM entidades WHERE id=80780; -- dup-ficha 29015: ya existe en 28082
DELETE FROM entidades WHERE id=80781; -- dup-ficha 29016: ya existe en 28092
DELETE FROM entidades WHERE id=80782; -- dup-ficha 29017: ya existe en 28093
DELETE FROM entidades WHERE id=78740; -- dup-ficha 29018: ya existe en 28107
DELETE FROM entidades WHERE id=80783; -- dup-ficha 29018: ya existe en 28107
DELETE FROM entidades WHERE id=80784; -- dup-ficha 29019: ya existe en 28120
DELETE FROM entidades WHERE id=80785; -- dup-ficha 29020: ya existe en 28131
