-- playas_real.sql
-- 129 entradas

UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 95) WHERE codigo_ine = '07040' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07040', 'playas', 95);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Palma — Playas top Mallorca, Es Trenc, Cala Major') WHERE codigo_ine='07040' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 95) WHERE codigo_ine = '07002' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07002', 'playas', 95);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Alcúdia — Playa de Alcúdia, una de las mejores de España') WHERE codigo_ine='07002' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '07013' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07013', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Andratx — Calas espectaculares, Camp de Mar') WHERE codigo_ine='07013' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '07017' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07017', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Artà — Cala Mesquida, Cala Torta') WHERE codigo_ine='07017' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '07020' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07020', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Calvià — Magaluf, Santa Ponça, Peguera — gran destino') WHERE codigo_ine='07020' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '07025' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07025', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Capdepera — Cala Ratjada, Cala Mesquida') WHERE codigo_ine='07025' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '07032' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07032', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Felanitx — Cala d''Or, Calas del sur') WHERE codigo_ine='07032' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '07038' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07038', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Llucmajor — S''Arenal, playas del sur') WHERE codigo_ine='07038' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 95) WHERE codigo_ine = '07042' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07042', 'playas', 95);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Pollença — Formentor (una de las mejores playas del mundo), Pollença') WHERE codigo_ine='07042' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '07048' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07048', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Santanyí — Cala Mondragó, Es Trenc') WHERE codigo_ine='07048' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '07054' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07054', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Ciutadella — Playas vírgenes de Menorca') WHERE codigo_ine='07054' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '07026' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07026', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Es Mercadal — Cala Pregonda, Arenal den Castell') WHERE codigo_ine='07026' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '07063' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07063', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Sa Pobla — Port de Pollença') WHERE codigo_ine='07063' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 95) WHERE codigo_ine = '07005' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07005', 'playas', 95);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Eivissa — Ses Salines (Ibiza), playa icónica') WHERE codigo_ine='07005' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '07048' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07048', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Formentera — Ses Illetes, playa más bonita de Europa') WHERE codigo_ine='07048' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '07028' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('07028', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Formentera — Playa de Levant, Migjorn') WHERE codigo_ine='07028' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 93) WHERE codigo_ine = '35016' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('35016', 'playas', 93);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Las Palmas de Gran Canaria — Playa de Las Canteras, icónica urbana') WHERE codigo_ine='35016' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 95) WHERE codigo_ine = '35005' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('35005', 'playas', 95);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: San Bartolomé de Tirajana — Maspalomas, Playa del Inglés, dunas') WHERE codigo_ine='35005' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '35006' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('35006', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Mogán — Puerto de Mogán, playas del suroeste GC') WHERE codigo_ine='35006' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '35017' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('35017', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Santa Lucía de Tirajana — Playas del sur') WHERE codigo_ine='35017' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '38001' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('38001', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Adeje — Playa de Las Américas, Los Cristianos') WHERE codigo_ine='38001' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '38023' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('38023', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Candelaria — Playas del este Tenerife') WHERE codigo_ine='38023' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '38026' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('38026', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Puerto de la Cruz — Playa Jardín, Lago Martiánez') WHERE codigo_ine='38026' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '38038' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('38038', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Santa Cruz de Tenerife — Playa de Las Teresitas (arena del Sáhara)') WHERE codigo_ine='38038' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '38050' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('38050', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Arona — Costa del Silencio, Ten-Bel') WHERE codigo_ine='38050' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '35003' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('35003', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Agüimes — Pozo Izquierdo, playas del este') WHERE codigo_ine='35003' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '35013' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('35013', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Pájara — Morro Jable, Cofete (playa virgen)') WHERE codigo_ine='35013' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '35023' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('35023', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: La Oliva — Corralejo, playas con dunas Fuerteventura') WHERE codigo_ine='35023' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 95) WHERE codigo_ine = '35026' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('35026', 'playas', 95);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Puerto del Rosario — Playa de Sotavento (kitesurf mundial)') WHERE codigo_ine='35026' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '38033' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('38033', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: San Sebastián de La Gomera — Playa de San Sebastián') WHERE codigo_ine='38033' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '29067' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('29067', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Málaga — Playas urbanas, paseo marítimo') WHERE codigo_ine='29067' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 95) WHERE codigo_ine = '29042' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('29042', 'playas', 95);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Marbella — Puerto Banús, playa del Faro, destino lujo') WHERE codigo_ine='29042' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '29069' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('29069', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Estepona — Playa del Arroyo Vaquero, playa de la Rada') WHERE codigo_ine='29069' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '29054' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('29054', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Nerja — Playa de Burriana, Maro') WHERE codigo_ine='29054' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '29032' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('29032', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Benalmádena — Playa Bil-Bil') WHERE codigo_ine='29032' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '29050' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('29050', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Fuengirola — Playa de Los Boliches') WHERE codigo_ine='29050' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '29051' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('29051', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Manilva — Duquesa, Castillo') WHERE codigo_ine='29051' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '29052' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('29052', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Mijas — Cala del Moral') WHERE codigo_ine='29052' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '29055' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('29055', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Rincón de la Victoria — Playa de la Cala') WHERE codigo_ine='29055' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '29058' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('29058', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Torremolinos — Playa de la Carihuela, los Álamos') WHERE codigo_ine='29058' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 93) WHERE codigo_ine = '11032' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('11032', 'playas', 93);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Sanlúcar de Barrameda — Playa de Bajo de Guía, carreras de caballos') WHERE codigo_ine='11032' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '11015' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('11015', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Chiclana de la Frontera — La Barrosa, una de las mejores de España') WHERE codigo_ine='11015' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '11005' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('11005', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Barbate — Playa de Zahara de los Atunes') WHERE codigo_ine='11005' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '11026' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('11026', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: El Puerto de Santa María — Playa de Valdelagrana') WHERE codigo_ine='11026' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '11022' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('11022', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: La Línea de la Concepción — Playa') WHERE codigo_ine='11022' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 95) WHERE codigo_ine = '11029' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('11029', 'playas', 95);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Tarifa — Playas de Los Lances, kitesurf, viento') WHERE codigo_ine='11029' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '11030' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('11030', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Vejer de la Frontera — El Palmar, Caños de Meca') WHERE codigo_ine='11030' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '21032' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('21032', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Punta Umbría — Playas de Huelva') WHERE codigo_ine='21032' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '21036' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('21036', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Cartaya — El Rompido') WHERE codigo_ine='21036' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '21039' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('21039', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Isla Cristina — Playa de Isla Cristina') WHERE codigo_ine='21039' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 85) WHERE codigo_ine = '21040' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('21040', 'playas', 85);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Lepe — Playas onubenses') WHERE codigo_ine='21040' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '21046' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('21046', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Moguer — Mazagón') WHERE codigo_ine='21046' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '17079' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('17079', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Girona — acceso Costa Brava') WHERE codigo_ine='17079' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '17033' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('17033', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Castelló d''Empúries — Empuriabrava, playa de la Rubina') WHERE codigo_ine='17033' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 85) WHERE codigo_ine = '17046' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('17046', 'playas', 85);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: La Jonquera — acceso Costa Brava norte') WHERE codigo_ine='17046' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 93) WHERE codigo_ine = '17057' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('17057', 'playas', 93);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Begur — Calas espectaculares, Aiguafreda, Sa Tuna') WHERE codigo_ine='17057' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '17096' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('17096', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Palafrugell — Calella, Llafranc, Tamariu — top calas España') WHERE codigo_ine='17096' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '17105' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('17105', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Palamós — Playa de La Fosca, cala S''Alguer') WHERE codigo_ine='17105' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '17107' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('17107', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Peralada — zona costera norte') WHERE codigo_ine='17107' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '17131' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('17131', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Roses — Golf de Roses, Cala Montjoi') WHERE codigo_ine='17131' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '17139' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('17139', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Sant Feliu de Guíxols — Playa de Sant Pol') WHERE codigo_ine='17139' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '17148' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('17148', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Tossa de Mar — Playa Gran, una de las más bonitas de España') WHERE codigo_ine='17148' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 95) WHERE codigo_ine = '17154' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('17154', 'playas', 95);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Cadaqués — Playa Es Pianc, Cala Es Llaner, la más pintoresca Costa Brava') WHERE codigo_ine='17154' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '43011' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('43011', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Cambrils — Playa de Cambrils') WHERE codigo_ine='43011' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '43041' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('43041', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Cunit — Playa de Cunit') WHERE codigo_ine='43041' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '43047' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('43047', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: L''Ametlla de Mar — Calas') WHERE codigo_ine='43047' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '43065' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('43065', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Salou — Port Aventura, playas') WHERE codigo_ine='43065' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '43100' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('43100', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Torredembarra — Playa de Torredembarra') WHERE codigo_ine='43100' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '43148' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('43148', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Tarragona — Playa del Miracle, La Arrabassada') WHERE codigo_ine='43148' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '43151' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('43151', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Vandellòs i l''Hospitalet de l''Infant — Playas del Riu') WHERE codigo_ine='43151' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '46131' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('46131', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Gandia — Playa de Gandia, larga y famosa') WHERE codigo_ine='46131' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '46070' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('46070', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Cullera — Playa de Marenys de Rafalcaïd') WHERE codigo_ine='46070' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '46249' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('46249', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Valencia — Playa de la Malvarrosa, playa de Las Arenas') WHERE codigo_ine='46249' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '46023' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('46023', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Benidorm — destino playero icónico Levante y Poniente') WHERE codigo_ine='46023' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 95) WHERE codigo_ine = '03024' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('03024', 'playas', 95);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Benidorm — Playa de Levante (una de las más concurridas del mundo)') WHERE codigo_ine='03024' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '03099' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('03099', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Alicante — Playa del Postiguet') WHERE codigo_ine='03099' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '03082' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('03082', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Guardamar del Segura — Playa de Guardamar') WHERE codigo_ine='03082' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '03089' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('03089', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: La Vila Joiosa — Playa Centro') WHERE codigo_ine='03089' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '03105' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('03105', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Santa Pola — Playa de Santa Pola, Gran Playa') WHERE codigo_ine='03105' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '03110' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('03110', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Torrevieja — Playa de Los Locos, El Cura') WHERE codigo_ine='03110' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 85) WHERE codigo_ine = '03138' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('03138', 'playas', 85);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Villena — interior') WHERE codigo_ine='03138' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '12054' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('12054', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Oropesa del Mar — Playa de la Concha, Marina d''Or') WHERE codigo_ine='12054' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '12094' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('12094', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Peñíscola — Playa Norte, playa Sur') WHERE codigo_ine='12094' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '12095' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('12095', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Torreblanca — Playa de Torre la Sal') WHERE codigo_ine='12095' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '33024' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('33024', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Gijón — Playa de San Lorenzo (la mejor urbana del norte)') WHERE codigo_ine='33024' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '33060' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('33060', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Llanes — Playa de Toró, Gulpiyuri, Ballota') WHERE codigo_ine='33060' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 85) WHERE codigo_ine = '33044' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('33044', 'playas', 85);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Oviedo — acceso playas') WHERE codigo_ine='33044' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '33067' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('33067', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Avilés — Playa de Salinas') WHERE codigo_ine='33067' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '33017' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('33017', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Cudillero — Playa del Silencio, Aguilar') WHERE codigo_ine='33017' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '33040' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('33040', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Navia — Playa de Navia') WHERE codigo_ine='33040' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '33050' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('33050', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Ribadesella — Playa de Santa Marina') WHERE codigo_ine='33050' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '39075' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('39075', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Santander — El Sardinero, Las Magdalenas') WHERE codigo_ine='39075' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '39019' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('39019', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: San Vicente de la Barquera — Playa de Merón') WHERE codigo_ine='39019' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '39012' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('39012', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Castro-Urdiales — Playa de Brazomar') WHERE codigo_ine='39012' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '39037' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('39037', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Laredo — Playa de La Salvé, una de las mejores del norte') WHERE codigo_ine='39037' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '39044' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('39044', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Noja — Playas de Ris y Trengandín') WHERE codigo_ine='39044' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '39052' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('39052', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Santoña — Playas de Berria') WHERE codigo_ine='39052' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '39058' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('39058', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Suances — Playa de La Concha') WHERE codigo_ine='39058' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '20069' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('20069', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: San Sebastián — La Concha (la playa urbana más bonita del mundo)') WHERE codigo_ine='20069' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '20065' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('20065', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Zarautz — Playa larga de surf') WHERE codigo_ine='20065' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 85) WHERE codigo_ine = '20046' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('20046', 'playas', 85);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Getaria — Playa de Getaria') WHERE codigo_ine='20046' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '48052' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('48052', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Lekeitio — Playa de Lekeitio, Isla de San Nicolás') WHERE codigo_ine='48052' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '48064' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('48064', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Mundaka — Mundaka (ola de surf famosa mundialmente)') WHERE codigo_ine='48064' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '48078' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('48078', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Ondarroa — Playa de Saturrarán') WHERE codigo_ine='48078' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '20030' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('20030', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Hondarribia — Playa de Hondarribia') WHERE codigo_ine='20030' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '15030' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('15030', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: A Coruña — Playa de Riazor, Orzan') WHERE codigo_ine='15030' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 95) WHERE codigo_ine = '15040' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('15040', 'playas', 95);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Carnota — Playa de Carnota (la más larga de Galicia)') WHERE codigo_ine='15040' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '15050' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('15050', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Fisterra — Playa de Mar de Fora, fin del mundo') WHERE codigo_ine='15050' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '15006' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('15006', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: A Baña — zona interior') WHERE codigo_ine='15006' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '15060' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('15060', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Muros — Playa de Area Longa') WHERE codigo_ine='15060' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '36001' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('36001', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: A Guarda — Playa de O Muíño') WHERE codigo_ine='36001' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '36046' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('36046', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Sanxenxo — Playa de Silgar (top España)') WHERE codigo_ine='36046' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '36010' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('36010', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Bueu — Playa de Agrelo, Lapamán') WHERE codigo_ine='36010' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '27060' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('27060', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Viveiro — Playa de Covas, Area Maior') WHERE codigo_ine='27060' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '27026' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('27026', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Foz — Playa de Llas, playa de Altar') WHERE codigo_ine='27026' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '30016' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('30016', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Murcia — acceso Mar Menor') WHERE codigo_ine='30016' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '30006' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('30006', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Águilas — Playas vírgenes, Cala Cerrada') WHERE codigo_ine='30006' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '30008' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('30008', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Cartagena — Playa de Calblanque, parque natural') WHERE codigo_ine='30008' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '30017' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('30017', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: La Unión — Mar Menor') WHERE codigo_ine='30017' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '30030' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('30030', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Mazarrón — Playa de Bolnuevo (piedras de yeso), Puerto de Mazarrón') WHERE codigo_ine='30030' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '30032' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('30032', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: San Javier — Los Alcázares, Mar Menor') WHERE codigo_ine='30032' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '30034' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('30034', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: San Pedro del Pinatar — Playas del Mar Menor, lodazales') WHERE codigo_ine='30034' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '04013' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('04013', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Almería — Playa de El Palmeral') WHERE codigo_ine='04013' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 95) WHERE codigo_ine = '04049' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('04049', 'playas', 95);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Níjar — Cabo de Gata, playas vírgenes más bonitas de España') WHERE codigo_ine='04049' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '04058' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('04058', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Roquetas de Mar — Playa de La Romanilla') WHERE codigo_ine='04058' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 92) WHERE codigo_ine = '04082' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('04082', 'playas', 92);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Vera — Playa de Vera, turismo nudista') WHERE codigo_ine='04082' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '04086' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('04086', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Adra — Playa de Poniente') WHERE codigo_ine='04086' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 88) WHERE codigo_ine = '04901' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('04901', 'playas', 88);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: El Ejido — Playa de Almerimar') WHERE codigo_ine='04901' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
UPDATE puntuaciones SET puntuacion = MAX(puntuacion, 90) WHERE codigo_ine = '04902' AND categoria = 'playas';
INSERT OR IGNORE INTO puntuaciones (codigo_ine, categoria, puntuacion) VALUES ('04902', 'playas', 90);
UPDATE municipios SET why_json = json_insert(COALESCE(why_json,'[]'),'$[#]','🏖️ Playas: Mojácar — Playa de Mojácar, Costa de Almería') WHERE codigo_ine='04902' AND COALESCE(why_json,'[]') NOT LIKE '%🏖️ Playas:%';
